### PR TITLE
Closes #307: solrQueryResponse missing methods fix

### LINKED ISSUE #307: My data should be retrieved by jsf instead of api endpoint

### PR DESCRIPTION
**Pull request by dbojanek**

### CODE REVIEW

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/SolrQueryResponse.java [hunk 1]
```diff
@@ -25,6 +21,8 @@
     private Map<String, List<String>> spellingSuggestionsByToken;
     private List<FacetCategory> facetCategoryList;
     private List<FacetCategory> typeFacetCategories;
+    private Map<String, String> datasetfieldFriendlyNamesBySolrField = new HashMap<>();
+    private Map<String, String> staticSolrFieldFriendlyNamesBySolrField;
```
Comment (MrK191) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/SolrQueryResponse.java]: Shouldn't this also be initilized?

Comment (MrK191) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/SolrQueryResponse.java]: Also should the keyword static be here since it is not static field :P?

**Review by MrK191 — CHANGES_REQUESTED** [review]

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/SolrQueryResponse.java (hunk 1 above)
Comment (dbojanek) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/SolrQueryResponse.java]: I'm gonna leave the name as it is. This fields are probably connected with translations on 'Publication Status' facet which changed during development of My Data page and requires fix on this new page now.
Possibly they might get deleted but that requires a closer look.

**Review by MrK191 — APPROVED** [review]
