### PR TITLE
Closes #525: Correct inconsistency with field naming in advanced sear…

### LINKED ISSUE #525: Advanced search works incorrectly
If I enter "100" in "Wavelength [angstroms]" field, search finds datasets with "100" in other fields, such as "Temperature" or "Notes".

### PR DESCRIPTION
**Pull request by madryk**

### CODE REVIEW

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/SearchServiceBean.java [hunk 1]
```diff
@@ -604,7 +573,7 @@ public SolrQueryResponse search(DataverseRequest dataverseRequest, List<Datavers
         }
 
         List<FacetCategory> facetCategoryList = new ArrayList<>();
-        List<FacetCategory> typeFacetCategories = new ArrayList<>();
+        FacetCategory typeFacetCategory = null;
```
Comment (MrK191) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/SearchServiceBean.java]: We can use Option.none() here, at least 1km down the method we will know that it can be missing :P.

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/SearchServiceBean.java [hunk 2]
```diff
@@ -756,7 +725,7 @@ public SolrQueryResponse search(DataverseRequest dataverseRequest, List<Datavers
         solrQueryResponse.setSolrSearchResults(solrSearchResults);
         solrQueryResponse.setSpellingSuggestionsByToken(spellingSuggestionsByToken);
         solrQueryResponse.setFacetCategoryList(facetCategoryList);
-        solrQueryResponse.setTypeFacetCategories(typeFacetCategories);
+        solrQueryResponse.setTypeFacetCategory(typeFacetCategory);
```
Comment (MrK191) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/SearchServiceBean.java]: and option.getOrNull here.

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/SearchUtil.java [hunk 3]
```diff
@@ -1,49 +1,29 @@
...
-                 * Because we want to support advanced search queries like
-                 * "title:foo" we can't simply escape the whole query with
-                 * `ClientUtils.escapeQueryChars(query)`:
-                 *
-                 * http://lucene.apache.org/solr/4_6_0/solr-solrj/org/apache/solr/client/solrj/util/ClientUtils.html#escapeQueryChars%28java.lang.String%29
-                 */
-            }
-        }
-        return query;
+    private static final String ASCENDING = "asc";
```
Comment (MrK191) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/SearchUtil.java]: Maybe SearchOrder should be outside enum, then you would have those string inside enums and then you can also use them here.

**Review by MrK191 — CHANGES_REQUESTED** [review]

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/SearchServiceBean.java (hunk 1 above)
Comment (madryk) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/SearchServiceBean.java]: ok

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/SearchServiceBean.java (hunk 2 above)
Comment (madryk) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/SearchServiceBean.java]: ok

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/SearchUtil.java (hunk 3 above)
Comment (madryk) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/SearchUtil.java]: :+1:

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/SolrQuerySanitizer.java [hunk 4]
```diff
@@ -0,0 +1,143 @@
...
+        }
+        return fieldNamesMapping;
+    }
+    
+    private void transferString(StringBuilder source, StringBuilder target) {
+        target.append(source);
+        source.setLength(0);
+    }
+    
+    private String replaceQueryFieldNames(String query, Map<String, String> fieldNamesMapping) {
```
Comment (MrK191) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/SolrQuerySanitizer.java:79]: After giving it some thought, I think this is good place for javadoc explaining the process.

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/SolrQuerySanitizer.java [hunk 5]
```diff
@@ -0,0 +1,143 @@
...
+                }
+            }
+
+            if (insideQuotation) {
+                transformedQuery.append(currentChar);
+                continue;
+            }
+
+            if (currentChar == ':') {
+                String fieldName = currentSegmentWithoutSpecialCharacters.toString();
```
Comment (MrK191) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/SolrQuerySanitizer.java]: Maybe fieldNameForView.

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/SolrQuerySanitizer.java [hunk 6]
```diff
@@ -0,0 +1,143 @@
...
+                
+                if (fieldNamesMapping.containsKey(fieldName)) {
+                    fieldName = fieldNamesMapping.get(fieldName);
```
Comment (MrK191) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/SolrQuerySanitizer.java]: And here solrFieldName, I know the logic will be kinda "bigger" and you would have to use ternary operator when appending, but it could be more explanatory.

**Review by MrK191 — CHANGES_REQUESTED** [review]

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/SolrQuerySanitizer.java (hunk 6 above)
Comment (madryk) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/SolrQuerySanitizer.java]: You mean:
```
            if (currentChar == ':') {
                String fieldNameForView = currentSegmentWithoutSpecialCharacters.toString();
                
                String solrFieldName = fieldNamesMapping.containsKey(fieldNameForView) ? 
                        fieldNamesMapping.get(fieldNameForView) : fieldNameForView;
                
                transformedQuery.append(solrFieldName);
                currentSegmentWithoutSpecialCharacters.setLength(0);
                transformedQuery.append(currentChar);
                continue;
            }
```
?

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/SolrQuerySanitizer.java (hunk 5 above)
Comment (madryk) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/SolrQuerySanitizer.java]: doesn't it be rather `fieldNameFromView`?

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/SolrQuerySanitizer.java (hunk 4 above)
Comment (madryk) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/SolrQuerySanitizer.java:79]: You mean how method is implemented? I'm not sure if this wouldn't be more confusing then it would explain things. I could add some description what it does, why it is done and maybe some example.
As for implementation details it probably will be better to have side comments inside method or nothing added at all (I can't think how to write it in the way that will add some value)

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/SolrQuerySanitizer.java (hunk 5 above)
Comment (MrK191) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/SolrQuerySanitizer.java]: Yeah, it could be better.

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/SolrQuerySanitizer.java (hunk 4 above)
Comment (MrK191) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/SolrQuerySanitizer.java:79]: Hmm, I guess some description would do, I would avoid comments. Private methods with javadocs would be better but I don't think they would help in this case.

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/SolrQuerySanitizer.java (hunk 6 above)
Comment (MrK191) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/SolrQuerySanitizer.java]: Something more like :
```
if (currentChar == ':') {
                String fieldNameFromView = currentSegmentWithoutSpecialCharacters.toString();
                Option<String> solrFieldName = Option.none();
                
                if (fieldNamesMapping.containsKey(fieldNameFromView)) {
                    solrFieldName = Option.of(fieldNamesMapping.get(fieldNameFromView));
                }
                
                transformedQuery.append(solrFieldName.getOrElse(fieldNameFromView));
                currentSegmentWithoutSpecialCharacters.setLength(0);
                transformedQuery.append(currentChar);
                continue;
            }
```

**Review by MrK191 — APPROVED** [review]
