### PR TITLE
Closes #2417: Fix citation data in harvested datasets

### LINKED ISSUE #2417: In search results' tiles of harvested datasets year should be equal to the actual publication year (as shown in the original repository) and not the year of the dataset harvest
We may use: 

JSON: `"publicationDate"`
DublinCore: year from `<dcterms:issued>`
Datacite: `<publicationYear>
`
We should check where we import data from these fields and use this year when building search result tiles for harvested datasets.

### PR DESCRIPTION
**Pull request by diasf**
On harvested data we used `distributionDate` as citation date inside the citation block, which is filled very rarely. This meant that in  most cases the import time was displayed inside the citation block.

Here we're changing the date inside the citation block to be resolved as follows: `productionDate` -> `publicationDate` -> import time. Those are the dates which should be present in most harvested formats and should reasonably well match the citation date of the remote server.

Issue: #2417

### CODE REVIEW

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/imports/HarvestedJsonParser.java [hunk 1]
```diff
@@ -101,7 +102,7 @@ private DatasetVersion parseDatasetVersion(JsonObject obj, DatasetVersion dsv) t
             if (versionStateStr != null) {
                 dsv.setVersionState(DatasetVersion.VersionState.valueOf(versionStateStr));
             }
-            dsv.setReleaseTime(parseDate(obj.getString("releaseDate", null)));
+            dsv.setReleaseTime(parseDate(obj.getString("releaseTime", null)));
```
Comment (diasf) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/imports/HarvestedJsonParser.java:105]: There's a similar mismatch in `JsonParser`: https://github.com/CeON/dataverse/blob/develop/dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/util/json/JsonParser.java#L270

While I was able to verify here that we use `releaseTime` instead of `releaseDate` in the harvest export/import process, I'm not sure about the clients to the above one, which among other places, is exposed through the API.

**Review by madryk — APPROVED** [review]
