### PR TITLE
Closes #1794: Fix Oai Server incorrectly mark dataset as deleted on GetRecord

### LINKED ISSUE #1794: Oai server can incorrectly mark record as deleted when using verb GetRecord
Assuming below situtation:
 - we have defined two oai sets - first default and the second one with query definition lets say `subject:*` (oai set will contain all datasets that have subject defined - most probably all datasets).
 - we narrow the second oai set definition to 'subject:Chemistry`
 - as a result the second oai set will contain a lot of removed records
After the last step oai server can produce information that some records were removed:
`http://localhost:8080/oai?verb=GetRecord&metadataPrefix=oai_ddi&identifier=<identifier>`
Do note that `GetRecord` verb does not support `set` param - so information about removed records
is not per oai set.
Currently `GetRecord` can return information that record was deleted because we have two entries
in `oairecord` table - one for each set.

See: https://github.com/CeON/dataverse/blob/6bbffbd34c8c629de33d3b0c0a73d1673e96c41a/dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/harvest/server/xoai/XitemRepository.java#L49-L74

### PR DESCRIPTION
**Pull request by madryk**

### CODE REVIEW

File: dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/harvest/OAIRecordRepository.java [hunk 1]
```diff
@@ -23,6 +30,47 @@ public OAIRecordRepository() {
...
+    }
+    
+    public List<OAIRecord> findByGlobalId(String globalId) {
+        return em.createQuery("SELECT r from OAIRecord r where r.globalId = :globalId", OAIRecord.class)
+                .setParameter("globalId", globalId)
+                .getResultList();
+    }
+    
+    public List<OAIRecord> findByGlobalIds(List<String> globalIds) {
+        return em.createQuery("SELECT r from OAIRecord r where r.globalId in :globalId", OAIRecord.class)
```
Comment (MrK191) [inline dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/harvest/OAIRecordRepository.java]: Isn't there a syntax error? In paremeter there is 'globalIds' here is 'globalId'

**Review by MrK191 — CHANGES_REQUESTED** [review]

File: dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/harvest/OAIRecordRepository.java (hunk 1 above)
Comment (madryk) [reply dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/harvest/OAIRecordRepository.java]: Yes. Very good catch. It was last minute refactor and I didn,'t notice that. I will also add integration test for this method so it will be easier to spot if something is wrong

**Review by MrK191 — APPROVED** [review]
