### PR TITLE
Closes #1439: Fix clone template cancelling

### LINKED ISSUE #1439: Cancel copy dataset template - creates new template instead of cancel
After click on copy icon :
1. success message  Success! – The template has been copied 
2. Available buttons: Save changes and Cancel

image

### PR DESCRIPTION
**Pull request by wtr-icm**

### CODE REVIEW

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/dataverse/template/TemplatePage.java [hunk 1]
```diff
@@ -22,38 +20,47 @@
...
 /**
  * @author skraffmiller
  */
 @ViewScoped
 @Named("TemplatePage")
 public class TemplatePage implements java.io.Serializable {
 
+    private static final Logger logger = Logger.getLogger(TemplatePage.class.getCanonicalName());
+
+    public enum EditMode {
```
Comment (MrK191) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/dataverse/template/TemplatePage.java:45]: Ideally we should just have separate pages with common template. But that's for future refactor.

**Review by MrK191 — APPROVED** [review]
