### PR TITLE
Closes #1867: Fix issue with fetching datasetfieldtypes multiple times on search page

### LINKED ISSUE #1867: Fetch datasetFieldTypes only once while searching

### PR DESCRIPTION
**Pull request by madryk**

### CODE REVIEW

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/SearchIncludeFragment.java [hunk 1]
```diff
@@ -706,7 +702,7 @@ private void setDisplayCardValues(String dataversePath) {
                 if (dataverse.getId().equals(result.getParentIdAsLong())) {
                     // definitely NOT linked:
                     result.setIsInTree(true);
-                } else if (result.getParentIdAsLong() == dataverseDao.findRootDataverse().getId()) {
+                } else if (result.getParentIdAsLong().equals(dataverseDao.findRootDataverse().getId())) {
```
Comment (dbojanek) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/SearchIncludeFragment.java:705]: ? We `.equals` numeric values?

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/response/FacetCategory.java [hunk 2]
```diff
@@ -1,11 +1,12 @@
 package edu.harvard.iq.dataverse.search.response;
 
+import java.util.ArrayList;
 import java.util.List;
 
 public class FacetCategory {
 
     private String name;
-    private List<FacetLabel> facetLabel;
+    private List<FacetLabel> facetLabel = new ArrayList<>(); // TODO: should be plural
```
Comment (dbojanek) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/response/FacetCategory.java]: Did you forget about it or is it more complicated than just a simple refactor?

**Review by dbojanek — APPROVED** [review]

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/SearchIncludeFragment.java (hunk 1 above)
Comment (madryk) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/SearchIncludeFragment.java:705]: Because both are `Long`: https://www.baeldung.com/java-compare-long-values

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/response/FacetCategory.java (hunk 2 above)
Comment (madryk) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/response/FacetCategory.java]: Actually, I noticed that at the last moment. I will correct this

**Review by dbojanek — APPROVED** [review]
