### PR TITLE
Closes #616: Fix displaying null's when there are no dataverses, datasets or files in search

### LINKED ISSUE #616: Fix facets problems when no dataverses, datasets or files is available in search

### PR DESCRIPTION
**Pull request by madryk**

### CODE REVIEW

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/query/SearchObjectType.java [hunk 1]
```diff
@@ -0,0 +1,45 @@
...
+        return solrValue;
+    }
+    
+    // -------------------- LOGIC --------------------
+    
+    /**
+     * Returns enum based on value from solr index.
+     */
+    public static SearchObjectType fromSolrValue(String solrValue) {
+        return Arrays.asList(SearchObjectType.values()).stream()
```
Comment (wtr-icm) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/query/SearchObjectType.java]: Maybe ```Arrays.stream(SearchObjectType.values())```?

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/query/SearchObjectType.java [hunk 2]
```diff
@@ -0,0 +1,45 @@
...
+    public String getSolrValue() {
+        return solrValue;
+    }
+    
+    // -------------------- LOGIC --------------------
+    
+    /**
+     * Returns enum based on value from solr index.
+     */
+    public static SearchObjectType fromSolrValue(String solrValue) {
```
Comment (wtr-icm) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/query/SearchObjectType.java:37]: If we have so tight correspondence between solr values and enum names, maybe we could just use ```Enum#valueOf```:
```java
public static SearchObjectType fromSolrValue(String solrValue) {
    return valueOf(solrValue.toUpperCase());
}
```

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/query/SearchPublicationStatus.java [hunk 3]
```diff
@@ -0,0 +1,51 @@
...
+ * Enum containing all possible publication statuses that
+ * can be assigned to dvObject in search.
+ * <p>
+ * Some of publication statuses can be overlapped
+ * (single dvObject can have more than one status).
+ * For example (dvObject with DRAFT status can be in IN_REVIEW status)
+ * 
+ * @author madryk
+ */
+public enum SearchPublicationStatus {
```
Comment (wtr-icm) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/query/SearchPublicationStatus.java:15]: Same comments as in ```SearchObjectType.java```

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/response/PublicationStatusCounts.java [hunk 4]
```diff
@@ -0,0 +1,129 @@
...
+            unpublishedCount = count;
+            break;
+        case DRAFT:
+            draftCount = count;
+            break;
+        case IN_REVIEW:
+            inReviewCount = count;
+            break;
+        case DEACCESSIONED:
+            deaccessionedCount = count;
```
Comment (wtr-icm) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/response/PublicationStatusCounts.java:81]: It's not mandatory here, but I would add ```break``` nonetheless.

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/mydata/MyDataSearchFragment.java [hunk 5]
```diff
@@ -460,25 +425,41 @@ public boolean hasValidFilterQueries() {
...
-            }
-
-        }
-        if (selectedTypesList.contains(typeClicked)) {
-
+    public boolean selectedTypesContainsDataverse() {
+        return selectedTypesList.contains(SearchObjectType.DATAVERSES);
+    }
+    public boolean selectedTypesContainsDataverseOnly() {
+        return selectedTypesList.size() == 1 && selectedTypesList.get(0) == SearchObjectType.DATAVERSES;
```
Comment (wtr-icm) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/mydata/MyDataSearchFragment.java]: This expression could be extracted into a method.

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/mydata/MyDataSearchFragment.java [hunk 6]
```diff
@@ -736,18 +717,11 @@ public String retrieveMyData() {
...
-        selectedTypesList.addAll(Arrays.asList(parts));
-
-        String[] arr = selectedTypesList.toArray(new String[selectedTypesList.size()]);
-        String selectedTypesHumanReadable = combine(arr, " OR ");
-        if (!selectedTypesHumanReadable.isEmpty()) {
-            typeFilterQuery = SearchFields.TYPE + ":(" + selectedTypesHumanReadable + ")";
-        }
+        
+        selectedTypesList = Lists.newArrayList(selectedTypesString.split(":"))
+                .stream()
```
Comment (wtr-icm) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/mydata/MyDataSearchFragment.java]:
```java
selectedTypesList = Arrays.stream(selectedTypesString.split(":")) …
```

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/SearchIncludeFragment.java [hunk 7]
```diff
@@ -226,34 +232,31 @@ public void search() {
...
         
-        
-        if (StringUtils.isNotEmpty(selectedTypesString)) {
-            
-            String selectedTypesHumanReadable = StringUtils.join(selectedTypesString.split(":"), " OR ");
-            typeFilterQuery = SearchFields.TYPE + ":(" + selectedTypesHumanReadable + ")";
-        }
-        selectedTypesList = Lists.newArrayList(selectedTypesString.split(":"));
+        selectedTypesList = Lists.newArrayList(selectedTypesString.split(":"))
+                .stream()
```
Comment (wtr-icm) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/SearchIncludeFragment.java]: As previously: ```Arrays#stream```

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/SearchIncludeFragment.java [hunk 8]
```diff
@@ -226,34 +232,31 @@ public void search() {
...
-        List<String> filterQueriesFinal = new ArrayList<>(filterQueriesWithoutType);
-        filterQueriesFinal.add(typeFilterQuery);
-        
-        List<String> filterQueriesFinalAllTypes = new ArrayList<>(filterQueriesWithoutType);
-        filterQueriesFinalAllTypes.add(SearchFields.TYPE + ":(dataverses OR datasets OR files)");
+//        List<String> filterQueriesFinal = new ArrayList<>(filterQueriesWithoutType);
+//        filterQueriesFinal.add(typeFilterQuery);
+//        
+//        List<String> filterQueriesFinalAllTypes = new ArrayList<>(filterQueriesWithoutType);
+//        filterQueriesFinalAllTypes.add(SearchFields.TYPE + ":(dataverses OR datasets OR files)");
```
Comment (wtr-icm) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/SearchIncludeFragment.java]: If we do not have very strong reason to keep this lines commented it would be better to remove them.

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/SearchIncludeFragment.java [hunk 9]
```diff
@@ -755,22 +750,41 @@ public boolean hasValidFilterQueries() {
...
+        if (newTypesSelected.contains(typeClicked)) {
+            newTypesSelected.remove(typeClicked);
         } else {
             newTypesSelected.add(typeClicked);
         }
-        return StringUtils.join(newTypesSelected, ":");
+        
+        return newTypesSelected.stream()
+                .map(t -> t.getSolrValue())
+                .collect(Collectors.joining(":"));
```
Comment (wtr-icm) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/SearchIncludeFragment.java]: If we have again the same methods as in ```MyDataSerarchFragment.java``` maybe we should extract them into another class or create more specialized class for ```selectedTypesList```?

File: dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/search/query/SearchForTypesTest.java [hunk 10]
```diff
@@ -0,0 +1,44 @@
...
+        // then
+        assertThat(typesToSearch.getTypes(), containsInAnyOrder(SearchObjectType.DATAVERSES, SearchObjectType.FILES));
+    }
+
+    @Test
+    public void byType__multiple_same_types() {
+        // when
+        SearchForTypes typesToSearch = SearchForTypes.byTypes(SearchObjectType.DATAVERSES, SearchObjectType.DATAVERSES);
+        // then
+        assertThat(typesToSearch.getTypes(), containsInAnyOrder(SearchObjectType.DATAVERSES));
```
Comment (wtr-icm) [inline dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/search/query/SearchForTypesTest.java]: If we are testing whether the result has only one occurrence of DATAVERSES element, then this assertion is insufficient.

**Review by wtr-icm — CHANGES_REQUESTED** [review]
Only my question concerning one of the tests seems important.

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/SearchIncludeFragment.java (hunk 9 above)
Comment (madryk) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/SearchIncludeFragment.java]: As for extraction to specialized class - I could use `SearchForTypes` object instead of `selectedTypesList` and extend it with methods `contains(SearchObjectType)`, `containsOnly(SearchObjectType)`, `toggleType(SearchObjectType)` then on xhtml use it like `SearchIncludeFragment.selectedTypes.contains(searchObjectTypeEnum.DATAVERSES)`.
What do you think?

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/mydata/MyDataSearchFragment.java (hunk 5 above)
Comment (madryk) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/mydata/MyDataSearchFragment.java]: Depends on what we would do with `selectedTypesList` according to suggestion below

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/query/SearchPublicationStatus.java (hunk 3 above)
Comment (madryk) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/query/SearchPublicationStatus.java:15]: Don't really understand. The comments for `SearchPublicationStatus.java` and `SearchObjectType.java` are not the same

File: dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/search/query/SearchForTypesTest.java (hunk 10 above)
Comment (madryk) [reply dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/search/query/SearchForTypesTest.java]: Actually it is. Javadoc says that `containsInAnyOrder()` checks for collection sizes. To avoid further confusion I can change it to `contains()`

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/query/SearchPublicationStatus.java (hunk 3 above)
Comment (wtr-icm) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/query/SearchPublicationStatus.java:15]: Ok, sorry for being unclear – I thought about method ```fromSolrValue``` that could be modified in similar way as the one from ```SearchObjectType``` class.

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/SearchIncludeFragment.java (hunk 9 above)
Comment (wtr-icm) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/SearchIncludeFragment.java]: Yes, that's ok (alternatively – if I'm not wrong – we could use some kind of interface with default methods for this ```…Fragment``` classes).

File: dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/search/query/SearchForTypesTest.java (hunk 10 above)
Comment (wtr-icm) [reply dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/search/query/SearchForTypesTest.java]: My fault then.

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/query/SearchForTypes.java [hunk 11]
```diff
@@ -31,6 +31,37 @@ private SearchForTypes(Set<SearchObjectType> types) {
...
+     * <p>
+     * additional type if original {@link SearchForTypes}
+     * does not contain it.
+     * <p>
+     * removed type if original {@link SearchForTypes} does
+     * contain it.
+     * <p>
+     * Method do not modify original {@link SearchForTypes}
+     */
+    public SearchForTypes toogleType(SearchObjectType type) {
```
Comment (wtr-icm) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/query/SearchForTypes.java]: toggleType?

**Review by wtr-icm — APPROVED** [review]
