### PR TITLE
Closes #1434: Fix ddi export

### LINKED ISSUE #1434: Unable to export dataset using DDI format for oai when metadata contains related material or related dataset

### PR DESCRIPTION
**Pull request by madryk**
Fixes problems with:
 - invalid ddi xml
 - situations when we had multiple controlled vocabulary and exporter expected single value
 - situations when exported expected primitive value in relatedMaterial and relatedDatasets 

Implemented data access as described in:
https://github.com/CeON/dataverse/issues/1436#issuecomment-784030364

### CODE REVIEW

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/imports/ImportDDIServiceBean.java [hunk 1]
```diff
@@ -471,6 +447,49 @@ private void processOthrStdyMat(XMLStreamReader xmlr, DatasetVersionDTO dvDTO) t
...
+                                int event3 = xmlr.next();
+                                if (event3 == XMLStreamConstants.START_ELEMENT) {
+                                    if (xmlr.getLocalName().equals("IDNo")) {
+                                        set.add(FieldDTO.createVocabFieldDTO(DatasetFieldConstant.publicationIDType, xmlr.getAttributeValue(null, "agency")));
+                                        addToSet(set, DatasetFieldConstant.publicationIDNumber, parseText(xmlr));
+                                    }
+                                }
+                            } else if (xmlr.getLocalName().equals("biblCit")) {
+                                if (event2 == XMLStreamConstants.START_ELEMENT) {
+                                    if (xmlr.getLocalName().equals("biblCit")) {
```
Comment (wtr-icm) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/imports/ImportDDIServiceBean.java]: Either these `if`s are redundant (at least the first) or we should read the next event as in previous branch.

Maybe it would be a good idea to break this method into smaller ones, reducing the nesting.

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/imports/ImportDDIServiceBean.java [hunk 2]
```diff
@@ -664,6 +683,52 @@ private void processNotes(XMLStreamReader xmlr, DatasetVersionDTO dvDTO) throws
...
+        // Add notes, if they exist
+        String attrVal = parseText(xmlr, "notes");
+        if ((attrVal != null) && (!attrVal.isEmpty())){
+            notesText  = FieldDTO.createPrimitiveFieldDTO("datasetLevelErrorNotes", attrVal);
+            getSocialScience(dvDTO).addField(notesText);
+        }
+    }
+
+    private void processNotesSocialScience(XMLStreamReader xmlr, DatasetVersionDTO dvDTO) throws XMLStreamException {
+        //String formattedNotes = this.formatNotesfromXML(xmlr);
```
Comment (wtr-icm) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/imports/ImportDDIServiceBean.java]: to remove (also similar lines below)

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/imports/ImportDDIServiceBean.java [hunk 3]
```diff
@@ -471,6 +447,49 @@ private void processOthrStdyMat(XMLStreamReader xmlr, DatasetVersionDTO dvDTO) t
...
     }
 
+    private void processRelPubl(XMLStreamReader xmlr, DatasetVersionDTO dvDTO,  List<Set<FieldDTO>> publications) throws XMLStreamException {
+        HashSet<FieldDTO> set = new HashSet<>();
+        for (int event = xmlr.next(); event != XMLStreamConstants.END_DOCUMENT; event = xmlr.next()) {
+            if (event == XMLStreamConstants.START_ELEMENT) {
+                if (xmlr.getLocalName().equals("citation")) {
+                    for (int event2 = xmlr.next(); event2 != XMLStreamConstants.END_DOCUMENT; event2 = xmlr.next()) {
+                        if (event2 == XMLStreamConstants.START_ELEMENT) {
+                            if (xmlr.getLocalName().equals("titlStmt")) {
```
Comment (wtr-icm) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/imports/ImportDDIServiceBean.java:457]: It would be cleaner and possibly a bit safer to change the order of comparison here and in similar places. It's only a suggestion as the amount of needed changes would be considerable.

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/imports/ImportDDIServiceBean.java [hunk 4]
```diff
@@ -697,23 +766,41 @@ private void processSumDscr(XMLStreamReader xmlr, DatasetVersionDTO dvDTO) throw
...
                         dateOfCollectionEnd = FieldDTO.createPrimitiveFieldDTO("dateOfCollectionEnd", parseDate(xmlr, "collDate"));
+                        dateOfCollection.add(FieldDTO.createMultipleCompoundFieldDTO("dateOfCollection", dateOfCollectionStart, dateOfCollectionEnd ));
                     }
 
                 } else if (xmlr.getLocalName().equals("nation")) {
-                    Set<FieldDTO> set = new HashSet<>();
-                    set.add(FieldDTO.createVocabFieldDTO("country", parseText(xmlr)));
-                    geoCoverages.add(set);
+                    if (otherGeographicCoverage != null && !otherGeographicCoverage.equals("")) {
+                        geoCoverageSet.add(FieldDTO.createPrimitiveFieldDTO("otherGeographicCoverage", otherGeographicCoverage));
```
Comment (wtr-icm) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/imports/ImportDDIServiceBean.java:777]: Is it possible that `geoCoverageSet` is `null` when we get here?

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/imports/ImportDDIServiceBean.java [hunk 5]
```diff
@@ -1141,7 +1237,16 @@ private void processDataAccs(XMLStreamReader xmlr, DatasetVersionDTO dvDTO) thro
                     String noteType = xmlr.getAttributeValue(null, "type");
                     if (NOTE_TYPE_TERMS_OF_USE.equalsIgnoreCase(noteType)) {
                         if (LEVEL_DV.equalsIgnoreCase(xmlr.getAttributeValue(null, "level"))) {
-                            dvDTO.setTermsOfUse(parseText(xmlr, "notes"));
+                            String termOfUse = parseText(xmlr, "notes");
+                            if (termOfUse != null && termOfUse.trim().equals("CC0 Waiver") ) {
+                                dvDTO.setLicense("CC0");
+                            } else if (termOfUse != null && !termOfUse.trim().equals("")){
```
Comment (wtr-icm) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/imports/ImportDDIServiceBean.java]: `isNotBlank()`?

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/imports/ImportDDIServiceBean.java [hunk 6]
```diff
@@ -1141,7 +1237,16 @@ private void processDataAccs(XMLStreamReader xmlr, DatasetVersionDTO dvDTO) thro
                     String noteType = xmlr.getAttributeValue(null, "type");
                     if (NOTE_TYPE_TERMS_OF_USE.equalsIgnoreCase(noteType)) {
                         if (LEVEL_DV.equalsIgnoreCase(xmlr.getAttributeValue(null, "level"))) {
-                            dvDTO.setTermsOfUse(parseText(xmlr, "notes"));
+                            String termOfUse = parseText(xmlr, "notes");
+                            if (termOfUse != null && termOfUse.trim().equals("CC0 Waiver") ) {
```
Comment (wtr-icm) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/imports/ImportDDIServiceBean.java]: `… && "CC0 Waiver".equals(…)`

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/export/ddi/DdiDataAccessWriter.java [hunk 7]
```diff
@@ -0,0 +1,120 @@
...
+    }
+    
+    private boolean hasRestrictedFile(List<FileDTO> files) {
+        return files
+                .stream()
+                .anyMatch(fileDTO -> isOfTermsOfUseType(fileDTO, FileTermsOfUse.TermsOfUseType.RESTRICTED));
+    }
+    
+
+    private boolean isOfTermsOfUseType(FileDTO fileDTO, FileTermsOfUse.TermsOfUseType allRightsReserved) {
```
Comment (wtr-icm) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/export/ddi/DdiDataAccessWriter.java]: `allRightsReserved` – strange name for a variable :)

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/export/ddi/DdiVariableWriter.java [hunk 8]
```diff
@@ -0,0 +1,212 @@
...
+            writeAttribute(xmlw, "RecSegNo", dataVariable.getRecordSegmentNumber().toString());
+        }
+
+        writeAttribute(xmlw, "fileid", "f" + dataVariable.getDataTable().getDataFile().getId().toString());
+    }
+
+    private void writeInvalrng(XMLStreamWriter xmlw, DataVariable dataVariable) throws XMLStreamException {
+        boolean invalrngAdded = false;
+        for (VariableRange range : dataVariable.getInvalidRanges()) {
+            //if (range.getBeginValueType() != null && range.getBeginValueType().getName().equals(DB_VAR_RANGE_TYPE_POINT)) {
```
Comment (wtr-icm) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/export/ddi/DdiVariableWriter.java]: to remove (also at line 201)

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/export/openaire/OpenAireExportUtil.java [hunk 9]
```diff
@@ -1724,41 +1739,28 @@ private static boolean areAllFilesUnderSameLincese(List<FileDTO> files) {
...
+    
+    
+    public static boolean hasRestrictedFile(List<FileDTO> files) {
         return files
                 .stream()
                 .anyMatch(fileDTO -> isOfTermsOfUseType(fileDTO, FileTermsOfUse.TermsOfUseType.RESTRICTED));
     }
+    
+
+    public static boolean isOfTermsOfUseType(FileDTO fileDTO, FileTermsOfUse.TermsOfUseType allRightsReserved) {
```
Comment (wtr-icm) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/export/openaire/OpenAireExportUtil.java]: `allRights…` – strange variable name

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/util/xml/XmlStreamWriterUtils.java [hunk 10]
```diff
@@ -0,0 +1,63 @@
...
+                xmlw.writeAttribute(attribute.getAttributeName(), attribute.getAttributeValue());
+            }
+        }
+        xmlw.writeEndElement();
+    }
+    
+    public static void writeFullElementWithAttributes(XMLStreamWriter xmlw, String name, String value, XmlAttribute ...attributes) throws XMLStreamException {
+        if (StringUtils.isNotEmpty(value)) {
+            xmlw.writeStartElement(name);
+            for (int i=0; i<attributes.length; ++i) {
```
Comment (wtr-icm) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/util/xml/XmlStreamWriterUtils.java]: It seems that we can use for-each here.

File: dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/export/DDIExporterTest.java [hunk 11]
```diff
@@ -1,163 +1,275 @@
...
+  "productionDate": "Production Date",
+  "lastUpdateTime": "2019-07-10T13:51:01Z",
+  "releaseTime": "2019-07-10T13:51:01Z",
+  "createTime": "2019-07-10T13:24:13Z",
+  "license": "CC0",
+  "termsOfUse": "CC0 Waiver",
+  "fileAccessRequest": false,
+}
+
+     */
```
Comment (wtr-icm) [inline dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/export/DDIExporterTest.java]: Is this commented temporarily?

File: dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/export/ExportServiceTest.java [hunk 12]
```diff
@@ -256,8 +236,8 @@ private void enableExcludingEmails() {
         when(settingsService.isTrueForKey(SettingsServiceBean.Key.ExcludeEmailFromExport)).thenReturn(true);
         when(systemConfig.getDataverseSiteUrl()).thenReturn("https://localhost");
 
-        exportService = new ExportService(settingsService, systemConfig);
-        exportService.loadAllExporters();
+//        exportService = new ExportService(settingsService, systemConfig);
+//        exportService.loadAllExporters();
```
Comment (wtr-icm) [inline dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/export/ExportServiceTest.java]: to remove?

**Review by wtr-icm — CHANGES_REQUESTED** [review]

File: dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/export/ExportServiceTest.java (hunk 12 above)
Comment (madryk) [reply dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/export/ExportServiceTest.java]: :+1:

File: dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/export/DDIExporterTest.java (hunk 11 above)
Comment (madryk) [reply dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/export/DDIExporterTest.java]: No - forgot to remove this

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/util/xml/XmlStreamWriterUtils.java (hunk 10 above)
Comment (madryk) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/util/xml/XmlStreamWriterUtils.java]: I can use for-each loop here (`for (XmlAttribute attribute: Arrays.asList(attributes))`). Can't use neither `Arrays.asList(...).forEach(...)` nor `Stream.filter(...).forEach(...)` without some workarounds because `XMLStreamWriter.writeAttribute` throws checked exception.

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/imports/ImportDDIServiceBean.java (hunk 1 above)
Comment (madryk) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/imports/ImportDDIServiceBean.java]: This two `if`s are not needed.
I don't want to make much changes in this class as in the end we will have to adjust it to our needs (especially make it to match our changes in citation and social metadata blocks)
The only changes I did in this class is ctrl-c + ctrl+v changes that dataverse introduced from the time we have forked dataverse repository

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/imports/ImportDDIServiceBean.java (hunk 4 above)
Comment (madryk) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/imports/ImportDDIServiceBean.java:777]: I don't want to spend more time on anlyzing this - in our solution we will be changing it (we want different behaviour). It was taken from original dataverse as is.

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/imports/ImportDDIServiceBean.java (hunk 3 above)
Comment (madryk) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/imports/ImportDDIServiceBean.java:457]: Not sure what you mean by `change the order`. Something like:
```
if (event2 == XMLStreamConstants.START_ELEMENT) {
    if (xmlr.getLocalName().equals("titlStmt")) {
```
 ->
```
if (xmlr.getLocalName().equals("titlStmt")) {
    if (event2 == XMLStreamConstants.START_ELEMENT) {
```
Either way I don't think that it should be as part of this task.

Comment (wtr-icm) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/imports/ImportDDIServiceBean.java:457]: I thought about changing `xmlr.getLocalName().equals("titlStmt")` to `"titlStmt".equals(xmlr.getLocalName())`, but it's not crucial here.

**Review by wtr-icm — APPROVED** [review]
