### PR TITLE
Closes #2689: Redirect user to failedLogin page in case of unknown saml-id

### LINKED ISSUE #2689: Graceful handling of unknown SAML id
When SAML sends a different ID for a given user and the one we have in dataverse, we would get the following error:

```
Caused by: java.lang.NullPointerException
        at edu.harvard.iq.dataverse.authorization.providers.saml.SamlConvertAccountPage.init(SamlConvertAccountPage.java:93)
```

We should handle this case gracefully and redirect the user the the failed login page. A log about the occurrence would also be helpful in the diagnosis of the issue.

### PR DESCRIPTION
**Pull request by diasf**
Also log the occurrence to better diagnose the issue.

Issue: #2689

### CODE REVIEW

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/authorization/providers/saml/SamlConvertAccountPage.java [hunk 1]
```diff
@@ -129,6 +131,13 @@ private SamlUserData getSamlUserDataFromSession() {
         return samlUser;
     }
 
+    private static String failedLogin(SamlLoginIssue.Type authenticationError, SamlUserData samlUser) {
+        HttpSession session = JsfHelper.getCurrentSession();
+        session.setAttribute(SamlAuthenticationServlet.SAML_LOGIN_ISSUE_SESSION_PARAM,
+                new SamlLoginIssue(authenticationError).addMessage(samlUser.printLoginData()));
+        return "/failedLogin.xhtml";
```
Comment (JakubNejmanICM) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/authorization/providers/saml/SamlConvertAccountPage.java]: This could be extracted to a constant

**Review by JakubNejmanICM — APPROVED** [review]
