### PR TITLE
Closes #1365: Fix oai set update with draft and deaccessioned dataset versions

### LINKED ISSUE #1365: Update of the default OAI set lasts forever
I'm on Dashboard/Manage Harversting Server. 

When I try to update the default set by clicking "Run Export", I see information "update in progress" which lasts and lasts...

The buttons remain inactive and I can do nothing with the set.

### PR DESCRIPTION
**Pull request by madryk**

### CODE REVIEW

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/harvest/server/OAIRecordServiceBean.java [hunk 1]
```diff
@@ -36,87 +33,84 @@
...
-                    setUpdateLogger.fine("found published dataset.");
+        for (Long datasetId : datasetIds) {
+            setUpdateLogger.fine("processing dataset id=" + datasetId);
 
-                    updateOaiRecordForDataset(dataset, setName, recordMap, setUpdateLogger);
-                }
-            }
+            datasetRepository.findById(datasetId)
+                .filter(Dataset::containsReleasedVersion)
+                .ifPresent(dataset -> {
```
Comment (MrK191) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/harvest/server/OAIRecordServiceBean.java]: I think extracting ifPresent could be more readable

**Review by MrK191 — CHANGES_REQUESTED** [review]

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/harvest/server/OAIRecordServiceBean.java [hunk 2]
```diff
@@ -64,9 +65,11 @@ public void updateOaiRecords(String setName, List<Long> datasetIds, Logger setUp
...
             setUpdateLogger.fine("processing dataset id=" + datasetId);
 
-            datasetRepository.findById(datasetId)
-                .filter(Dataset::containsReleasedVersion)
-                .ifPresent(dataset -> {
+            Optional<Dataset> datasetWithReleasedVersion = datasetRepository
+                                            .findById(datasetId)
+                                            .filter(Dataset::containsReleasedVersion);
+
+            datasetWithReleasedVersion.ifPresent(dataset -> {
```
Comment (MrK191) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/harvest/server/OAIRecordServiceBean.java:72]: I meant the code inside ifPresent, i was kinda unprecise ;) so
```			
ifPresent(dataset -> {
                    setUpdateLogger.fine("found published dataset.");
                    OAIRecord record = recordMap.remove(dataset.getGlobalIdString());

                    if (record == null) {
                        createOaiRecordForDataset(dataset, setName, setUpdateLogger);
                    } else {
                        updateOaiRecordForDataset(dataset, record, setUpdateLogger);
                    })
```
would be

```
ifPresent(this::someMethod);
```

**Review by MrK191 — CHANGES_REQUESTED** [review]

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/harvest/server/OAIRecordServiceBean.java (hunk 2 above)
Comment (madryk) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/harvest/server/OAIRecordServiceBean.java:72]: I'm not so sure if this is a good idea. Mainly because we would have to hide modifications of `recordMap` map. This will introduce side effect on passed arguments to method. Maybe if we could name it somewhow that it would be clear enough that such side effect is present. But I can't think of the name that will be understood -`updateOaiRecordForDatasetAndRemoveFromMapOrCreateIfNotPresent`. What do you think?

Comment (MrK191) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/harvest/server/OAIRecordServiceBean.java:72]: Hmmm, yeah it is kinda difficult. I think it should be left as it is then, it is probably needed to refactor the whole class in order to make things consistent.

**Review by MrK191 — APPROVED** [review]
