### PR TITLE
Closes #2579 When there is an author identifier, but no identifier scheme, validation is not working properly

### LINKED ISSUE #2579: When there is an author identifier, but no identifier scheme, validation is not working properly

### PR DESCRIPTION
**Pull request by lbownik**
https://git.icm.edu.pl/dariah/archeo/-/issues/12

### CODE REVIEW

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/validation/field/validators/AuthorIdentifierValidator.java [hunk 1]
```diff
@@ -1,46 +1,60 @@
...
+    public FieldValidationResult validateValue(String value, ValidatableField field,
+            Map<String, Object> params,
+            Map<String, ? extends List<? extends ValidatableField>> fieldIndex) {
+
         if (isSelectedIdentifierScheme(field, params)) {
             return validateIdentifier(value, field, params, fieldIndex);
+        } else {
+            return isEmpty(value) ? ok()
+                    : invalid(field,
+                            getStringFromBundle("identifier.scheme.required"));
```
Comment (diasf) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/validation/field/validators/AuthorIdentifierValidator.java]: Isn't this case already handled by the `required_dependant` validator you've added? There's no check whether `authorIdType` is empty or not, at this point the only thing we know is that it's not equal to whatever `authorIdentifierScheme` has been configured with.

File: dataverse-persistence/src/main/resources/db/migration/V79_add_depentent_validation_to_authorIdetifierScheme.sql [hunk 2]
```diff
@@ -0,0 +1,2 @@
+update datasetfieldtype set validation = '[{"name":"standard_input"}, {"name":"required_dependant","parameters":{"context":["DATASET"], "dependantField": "authorIdentifier"}}]'
+where id  = 11 and name = 'authorIdentifierScheme';
```
Comment (diasf) [inline dataverse-persistence/src/main/resources/db/migration/V79_add_depentent_validation_to_authorIdetifierScheme.sql]: Why that specific id? Referencing by name should be enough.

File: dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/validation/field/validators/OrcidFieldValidatorTest.java [hunk 3]
```diff
@@ -75,9 +75,9 @@ public void validateValue__non_matching_identifier_type() {
         FieldValidationResult result = validator.validateValue(isni, identifier, params, Collections.emptyMap());
 
         // then
-        assertThat(result.isOk()).isTrue();
-        assertThat(result.getField()).isNull();
-        assertThat(result.getMessage()).isEmpty();
+        assertThat(result.isOk()).isFalse();
```
Comment (diasf) [inline dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/validation/field/validators/OrcidFieldValidatorTest.java]: Why should this be false? We don't know whether the ISNI number is valid or not.

**Review by diasf — CHANGES_REQUESTED** [review]

File: dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/validation/field/validators/OrcidFieldValidatorTest.java (hunk 3 above)
Comment (lbownik) [reply dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/validation/field/validators/OrcidFieldValidatorTest.java]: In this test we give it ISNI but require to validate ORCID. The result shall be 'failure' because of the mismatch, regardless of given identifier validity.

File: dataverse-persistence/src/main/resources/db/migration/V79_add_depentent_validation_to_authorIdetifierScheme.sql (hunk 2 above)
Comment (lbownik) [reply dataverse-persistence/src/main/resources/db/migration/V79_add_depentent_validation_to_authorIdetifierScheme.sql]: So that we are 200% safe. It is better not to update, than potentially update to much (if only name = 'authorIdentifierScheme' was used) or update a wrong record ,if for some reason id values change (if only where id  = 11).

In case of DB migrations, better safe than sorry.

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/validation/field/validators/AuthorIdentifierValidator.java (hunk 1 above)
Comment (lbownik) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/validation/field/validators/AuthorIdentifierValidator.java]: If identifier sheme is NOT selected and identifier is empty, then validation should succeed as both fields are optional.
identifier scheme selected  AND identifier NOT empty -> result = validate identifier;
identifier scheme selected  AND identifier empty -> result = failure
identifier scheme NOT selected  AND identifier NOT empty -> result = failure
identifier scheme NOT selected  AND identifier empty -> result = success/ignore

Comment (diasf) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/validation/field/validators/AuthorIdentifierValidator.java]: > identifier scheme selected AND identifier empty -> result = failure
> identifier scheme NOT selected AND identifier NOT empty -> result = failure

Aren't those cases already handled by the `required_dependant` validator? At least that's the intended purpose of that validator.

To note that `isSelectedIdentifierScheme` will be false for an `orcid_validator` when the user selects an other identifier scheme than ORCID. And in that case the `orcid_validator` would now show `identifier.scheme.required` message even though it shouldn't.

File: dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/validation/field/validators/OrcidFieldValidatorTest.java (hunk 3 above)
Comment (diasf) [reply dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/validation/field/validators/OrcidFieldValidatorTest.java]: But there is no mismatch, the ORCID validator should only validate identifiers of type ORCID. It's explained in the javadoc: https://github.com/CeON/dataverse/pull/2583/files#diff-8be394bff9bf9e86e56425c19dfb2eb06a1835f0d579bca8a3ac62384e13d24dR17

Identifiers of type ISNI would be validated by an isni validator, if we had one :)

If the orcid validator would fail the validation for any other scheme, the user wouldn't be able to use them.

**Review by diasf — CHANGES_REQUESTED** [review]

File: dataverse-persistence/src/main/resources/db/migration/V79_add_depentent_validation_to_authorIdetifierScheme.sql (hunk 2 above)
Comment (diasf) [reply dataverse-persistence/src/main/resources/db/migration/V79_add_depentent_validation_to_authorIdetifierScheme.sql]: But we want to catch them all, don't we? But not insisting because either way, it remains error prone. To be 100% correct one would need to ensure that there exists a sibling named `authorIdentifier` and instead of verifying by id ensure that the parent is `author` and that `author` doesn't have any parent himself.

That being said, don't we want to have a `required_dependant` validator on `authorIdentifier` as well? So that if either one is filled the other one needs to be filled as well.

File: dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/validation/field/validators/OrcidFieldValidatorTest.java (hunk 3 above)
Comment (lbownik) [reply dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/validation/field/validators/OrcidFieldValidatorTest.java]: The test is what it is.
Tt seems that it doesn't test a valid scenario, so meybe I'll remove it?

Comment (diasf) [reply dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/validation/field/validators/OrcidFieldValidatorTest.java]: It is a valid scenario and it should probably stay. The validator will be executed for any selected identifier scheme, and the purpose of `isSelectedIdentifierScheme` is to return true when a supported scheme for the given validator has been selected. ISNI is not supported by the `orcid_validator` so no validation should take place.

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/validation/field/validators/AuthorIdentifierValidator.java (hunk 1 above)
Comment (lbownik) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/validation/field/validators/AuthorIdentifierValidator.java]: fixed

File: dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/validation/field/validators/OrcidFieldValidatorTest.java (hunk 3 above)
Comment (lbownik) [reply dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/validation/field/validators/OrcidFieldValidatorTest.java]: fiexd - reverted changes

File: dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/validation/field/validators/OrcidFieldValidatorTest.java [hunk 4]
```diff
@@ -75,9 +75,6 @@ public void validateValue__non_matching_identifier_type() {
         FieldValidationResult result = validator.validateValue(isni, identifier, params, Collections.emptyMap());
 
         // then
-        assertThat(result.isOk()).isTrue();
-        assertThat(result.getField()).isNull();
-        assertThat(result.getMessage()).isEmpty();
```
Comment (diasf) [inline dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/validation/field/validators/OrcidFieldValidatorTest.java]: Don't forget to add those assertions back in.

Comment (lbownik) [reply dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/validation/field/validators/OrcidFieldValidatorTest.java]: fixed

File: dataverse-persistence/src/main/resources/Bundle_en.properties [hunk 5]
```diff
@@ -347,6 +347,7 @@ user.orcid=ORCID
 user.orcid.tip=ORCID is an open digital identifier allowing distinction between researchers having the same or similar name and surname.
 user.orcid.invalid.format=Invalid ORCID format.
 user.orcid.invalid.checksum=Invalid ORCID checksum.
+identifier.scheme.required="\"Identifier Scheme\" is required because \"Identifier\" is not empty."
```
Comment (diasf) [inline dataverse-persistence/src/main/resources/Bundle_en.properties]: Not used anymore.

File: dataverse-persistence/src/main/resources/Bundle_pl.properties [hunk 6]
```diff
@@ -3035,6 +3035,7 @@ ror.invalid.format=Pole "{0}" nie zawiera poprawnie zbudowanego identyfikatora R
 ror.invalid.checksum=Pole "{0}" nie zawiera prawid\u0142owego identyfikatora ROR.
 orcid.invalid.format=Pole "{0}" nie zawiera poprawnie zbudowanego identyfikatora ORCID.
 orcid.invalid.checksum=Pole "{0}" nie zawiera prawid\u0142owego identyfikatora ORCID.
+identifier.scheme.required="Pole \"Typ identyfikatora\" jest wymagane, poniewa\u017C wprowadzono identyfikator."
```
Comment (diasf) [inline dataverse-persistence/src/main/resources/Bundle_pl.properties]: Not used anymore.

**Review by diasf — APPROVED** [review]
LGTM, but please remove the un-used bundle keys before merging.

File: dataverse-persistence/src/main/resources/Bundle_pl.properties (hunk 6 above)
Comment (lbownik) [reply dataverse-persistence/src/main/resources/Bundle_pl.properties]: fixed
