### PR TITLE
Closes #941: AdvancedSearchPage DateRange custom validations

### LINKED ISSUE #941: Extend validation for dates in advanced search
Currently we only check if the date is in valid format: 

image

The other problem is that currently the information is show under both of these fields, so a user may not know in which field the format is incorrect. We also do not chec if there is a proper date range created for the query. 

We would like to have:

1. Check if we have valid date format in both fields (including if the date is in fact a date, and not, for instance 1984-84-44 or 2020-04-31). If not:

Pole "Od" zawiera niepoprawną datę. Oczekiwane formaty daty to (-)YYYY, (-)YYYY-MM lub (-)YYYY-MM-DD. 

Pole "Do" zawiera niepoprawną datę. Oczekiwane formaty daty to (-)YYYY, (-)YYYY-MM lub (-)YYYY-MM-DD. 

"From" filed contains an invalid date. Valid date formats are (-)YYYY or (-)YYYY-MM or (-)YYYY-MM-DD

"To" filed contains an invalid date. Valid date formats are (-)YYYY or (-)YYYY-MM or (-)YYYY-MM-DD

The error message should be shown under specific field, and not under both of them. 

2. If we have valid date format in both fields, check if we have a proper date range. By proper we mean that the beginnig of date range in the "From" field should be smaller than the end of the the date range in "To" field. Examples:

2012 TO 2012 is a valid date. 
2012-03-12 TO 2012-03-12 is a valid date.
-1000-12-31 TO -999-01-01 is a valid date.   
2012 TO 2012-14 is not a valid date, but it should be validated negatively on the previous stage. 
2013 TO 2012-12-31 is not a valid date. 
-1000 TO -1001 is not a valid date. 
-2000-10 TO -3000-05 is not a valid date. 

If the date is not valid:

* Daty w polach "Od" i "Do" nie tworzą prawidłowego zakresu dat. 

* Dates in "From" and "To" fields do not create a valid date range. 

This validation message should be the same for both fields, but it should be shown separately under "From" and "To" fields. (A user may fix this by changing date in only one of them.)

### PR DESCRIPTION
**Pull request by dbojanek**

### CODE REVIEW

**Comment by dbojanek** [comment]
If possible, perform some manual tests.

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/advanced/DateRangeValidator.java [hunk 1]
```diff
@@ -0,0 +1,106 @@
...
+
+        String datePattern = "^(\\-?)[0-9]{4}((\\-)([0-9]{2})){0,2}$";
+        if(!value.toString().matches(datePattern)) {
+            ((UIInput) comp).setValid(false);
+            FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_ERROR, "", BundleUtil.getStringFromBundle("advanced.search.wrong.daterange.format"));
+            context.addMessage(comp.getClientId(context), message);
+            return null;
+        }
+
+        String[] dateFormats = {"yyyy", "-yyyy", "yyyy-MM", "-yyyy-MM", "yyyy-MM-dd", "-yyyy-MM-dd"};
```
Comment (wtr-icm) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/advanced/DateRangeValidator.java]: It would be better to make this array `static final` IMO.

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/advanced/DateRangeValidator.java [hunk 2]
```diff
@@ -0,0 +1,106 @@
...
+        }
+    }
+
+    // -------------------- PRIVATE ---------------------
+    private LocalDate validateDateField(FacesContext context, UIComponent comp, Object value) {
+        if(value == null || value.toString().isEmpty()) {
+            return null;
+        }
+
+        String datePattern = "^(\\-?)[0-9]{4}((\\-)([0-9]{2})){0,2}$";
```
Comment (wtr-icm) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/advanced/DateRangeValidator.java]: Good candidate for a constant.

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/advanced/DateRangeValidator.java [hunk 3]
```diff
@@ -0,0 +1,106 @@
...
+            dateFromInput.setValid(false);
+            dateToInput.setValid(false);
+            FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_ERROR, "", BundleUtil.getStringFromBundle("advanced.search.wrong.daterange.badRange"));
+            context.addMessage(dateFromInput.getClientId(context), message);
+            context.addMessage(dateToInput.getClientId(context), message);
+        }
+    }
+
+    // -------------------- PRIVATE ---------------------
+    private LocalDate validateDateField(FacesContext context, UIComponent comp, Object value) {
```
Comment (wtr-icm) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/advanced/DateRangeValidator.java]: There are too many different types of logic here in this method: validation, view and parsing.

**Review by wtr-icm — CHANGES_REQUESTED** [review]

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/advanced/DateRangeValidator.java (hunk 3 above)
Comment (dbojanek) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/advanced/DateRangeValidator.java]: What's your suggestion then?

Comment (wtr-icm) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/advanced/DateRangeValidator.java]: 1. One method only for validation
2. Another method for display
3. The result of the first is passed to second in main method of the class.

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/advanced/DateRangeValidator.java [hunk 4]
```diff
@@ -0,0 +1,114 @@
...
+    }
+
+    // -------------------- PRIVATE ---------------------
+    private Optional<LocalDate> validateDate(FacesContext context, UIComponent comp, Object value) {
+        if(value == null || value.toString().isEmpty()) {
+            return Optional.empty();
+        }
+
+        try {
+            isDatePatternCorrect(value);
```
Comment (wtr-icm) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/advanced/DateRangeValidator.java]: Consider using `Either` or some similar construct instead of throwing an exception.

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/advanced/DateRangeValidator.java [hunk 5]
```diff
@@ -70,14 +69,20 @@ private boolean isValidDateRange(LocalDate dateFrom, LocalDate dateTo, String da
...
+            DateUtils.parseDateStrictly(value.toString(), DATE_FORMATS);
+        } catch(ParseException  pe) {
+            return Either.left("Invalid date inserted. Given value: " + value.toString() + ". Acceptable formats: " + DATE_FORMATS);
+        }
+        return Either.right(true);
     }
 
-    private void isDatePatternCorrect(Object value) throws ParseException {
+    private Either<String, Boolean> isDatePatternCorrect(Object value) {
         if(!value.toString().matches(DATE_PATTERN)) {
```
Comment (wtr-icm) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/advanced/DateRangeValidator.java]: Suggestion: in that kind of methods with simple if-else one could use `? : ` operator instead.

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/advanced/DateRangeValidator.java [hunk 6]
```diff
@@ -70,14 +69,20 @@ private boolean isValidDateRange(LocalDate dateFrom, LocalDate dateTo, String da
...
 
-    private void isDateValueCorrect(Object value) throws ParseException {
-        DateUtils.parseDateStrictly(value.toString(), DATE_FORMATS);
+    private Either<String, Boolean> isDateValueCorrect(Object value) {
+        try {
+            DateUtils.parseDateStrictly(value.toString(), DATE_FORMATS);
+        } catch(ParseException  pe) {
+            return Either.left("Invalid date inserted. Given value: " + value.toString() + ". Acceptable formats: " + DATE_FORMATS);
+        }
+        return Either.right(true);
```
Comment (wtr-icm) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/advanced/DateRangeValidator.java]: Suggestion: we could move this `return` to `try` clause, so the flow would be a bit clearer IMO. But it's also ok as is.

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/advanced/DateRangeValidator.java [hunk 7]
```diff
@@ -50,13 +51,11 @@ public void validate(FacesContext context, UIComponent component, Object value)
             return Optional.empty();
         }
 
-        try {
-            isDatePatternCorrect(value);
-            isDateValueCorrect(value);
-        } catch(ParseException  pe) {
+        if(isDatePatternCorrect(value).isLeft() || isDateValueCorrect(value).isLeft()) {
```
Comment (wtr-icm) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/advanced/DateRangeValidator.java:54]: That's better than previous versions I think.
Maybe it would be possible to transform the rest of method in more functional way with either, but as for now it's ok.

**Review by wtr-icm — APPROVED** [review]
