### PR TITLE
Closes #1326: A superuser should able to rerun automatic analysis via API

### LINKED ISSUE #1326: A superuser should able to rerun automatic analysis via API
For now, reanalysis via API should be enough – we will not perform this operation frequently. 

Possible scenarios: 

1. There is a new version of XDS, which fixes a major bug – we should make wholesale reanalysis, as all previous analyses became dubious. 
2. We've extended our analyses and now we are able to analyse dataset versions where the analysis was not performed. 
3. We've made a fix on our side and we believe that some analyses that previously failed, this time won't.
4. A superuser curated metadata in a way that may change the results of the previous analysis. 

Requirements: 

1. Rerun should be possible for superuser only, so we should identify him/her by a token. 
2. It should be possible to declare what should be analysed:
2.1. All latest published versions of all datasets for which the analysis was not performed.  
2.2. All latest published versions of all datasets for which the analysis failed. 
2.3. Specific version of a specific datasets. 

As a result, selected dataset versions should be queued for the reanalysis.

### PR DESCRIPTION
**Pull request by tomaszblazejczyk**
Moved from https://github.com/CeON/mxrdr-extension/pull/75

### CODE REVIEW

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/WorkflowsAdmin.java [hunk 1]
```diff
@@ -189,4 +213,92 @@ public Response deleteIpWhitelist() {
...
+            if (!user.isSuperuser()) {
+                return error(Response.Status.FORBIDDEN, "Only superusers can run workflow");
+            }
+            if (type == null) {
+                return error(Response.Status.BAD_REQUEST, "Missing processing type - 'type=failedOnly' or 'type=notPerformedOnly' is required");
+            }
+
+            int datasetProcessed = 0;
+            for (Dataset dataset:datasetRepository.findAll()) {
+                if (dataset.isLockedFor(DatasetLock.Reason.Workflow)) {
```
Comment (madryk) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/WorkflowsAdmin.java]: Imo - check should be little later. Now we will return error if dataset have running workflow.

**Review by madryk — CHANGES_REQUESTED** [review]

**Review by madryk — APPROVED** [review]
