### PR TITLE
Closes #2847: Prevent multiple executions of save method

### LINKED ISSUE #2847: In some rare cases, S3 references in Dataverse database are not consistent with the actual file ids on S3
The result is that it is impossible to download files – they are missing from the user's point of view.

But the files in fact are not missing – they are alive and well and can be found on S3 by file size. The problem is just the invalid reference. 

The problem is occurring for years and I have no idea how to reproduce it and what may cause it. Sometimes it just happens.

### PR DESCRIPTION
**Pull request by diasf**
The issue that occurred with wrong S3 references in the Database was the following.

On the "Upload files" screen:
1. User uploads a couple of big files
2. User clicks `save`
3. During save files are transfered one by one to S3. Local temporary files which have already been transferred are removed. For big files, and/or if there are many files the whole process can take a lot of time.
4. If the save process takes longer than the configured timeout on the gateway (apache, nginx, ..) the client receives a 502
5. UI is unblocked, user doesn't see any information so clicks again on save
6. Save process is executed again, some files have already been removed locally which causes the save to fail. The S3 reference in the DataFile objects has been updated though
7. Once the first save has transferred all the files, the DB is updated with S3 references set by the 2nd save process

This is a temporary quick fix, which includes:
* Ensure that the save method is not executed multiple times simultaneously
* Ensure the UI remains blocked until the save finishes

Should the connection get interrupted by the gateway with a 502:
1. The UI will remain blocked until save finishes
2. The UI starts to poll the backing bean to check the status of the save process
3. A message is shown to the user "Saving in progress"
4. Once the save terminates the form refreshes

To note:
In 4. we're not redirecting to the dataset edit page as would normally happen without the 502. This could still be achieved but it would require some convoluted hacks. This is because once the initial save method returns with the redirect string, JSF terminates the ViewScope and all state is lost. I opted to provide a first quick and simple fix to prevent the corruption from happening again.

A more complete fix will require a bit more refactoring on the backing bean to make the save process completely asynchronous. I would propose to do that in a follow-up PR.

### CODE REVIEW

**Comment by wfenrich** [comment]
:face_holding_back_tears:

File: fairchive-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/IngestServiceBean.java [hunk 1]
```diff
@@ -190,76 +187,78 @@ public List<DataFile> saveAndAddFilesToDataset(DatasetVersion version, List<Data
...
                 storageIO.savePath(tempLocationPath);
 
                 dataFile.setFilesize(storageIO.getSize());
                 savedSuccess = true;
-                logger.fine("Success: permanently saved file " + dataFile.getFileMetadata().getLabel());
+                logger.debug("Success: permanently saved file {}", dataFile.getFileMetadata().getLabel());
 
             } catch (IOException ioex) {
-                logger.warning("Failed to save the file, storage id " + dataFile.getStorageIdentifier() + " (" + ioex.getMessage() + ")");
+                logger.debug("Failed to save the file, storage id {}", dataFile.getStorageIdentifier(), ioex);
```
Comment (madryk) [inline fairchive-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/IngestServiceBean.java]: Are we sure that we want to change it to debug?

**Review by madryk — APPROVED** [review]

File: fairchive-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/IngestServiceBean.java (hunk 1 above)
Comment (diasf) [reply fairchive-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/IngestServiceBean.java]: Good catch. Fixed it.
