### PR TITLE
Closes #817: dataset download count fix

### LINKED ISSUE #817: Fix bug with whole dataset downloads counter and versions consisting of a single file
Current behavior: 

If there is a published dataset version containing only a single file, downloading this file does not increment the counter. 

Expected behavior: 

If there is a published dataset version containing only a single file, downloading this single file increments the counter.

### PR DESCRIPTION
**Pull request by wtr-icm**

### CODE REVIEW

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/DownloadInstanceWriter.java [hunk 1]
```diff
@@ -361,18 +361,22 @@ public void writeTo(DownloadInstance di, Class<?> clazz, Type type, Annotation[]
...
                         }
                     } else {
                         logger.fine("not writing guestbook response");
 
-                        // If we're downloading preprocessed metadata then we should not check for whole dataset download
-                        checkForWholeDatasetDownload = false;
+                        // Although the guestbook is not present we may still want to log downloading of the whole
+                        // dataset and that depends on the type of file being downloaded (ie. thumbnails and
+                        // preprocessed metadata are excluded)
+                        checkForWholeDatasetDownload = meaningfulDownload;
```
Comment (dbojanek) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/DownloadInstanceWriter.java]: I don't think that's the root of the problem. Although it fixes counting datasets we should aim to fix its cause.

**Review by dbojanek — COMMENTED** [review]
I think the problem here lies in `Access.datafile` endpoint.  I don't think this enpoint is properly documented, but i believe `qbrecs` param indicates that if `true` then user passes guestbook response record (gbrec). If `false` or `null` then no gbrec has been passed. 

This endpoint is REALLY inconsistent with application because in no way there is a validation for passed guestbook response record. 
In current form, the way I think it should work is: just ignore value of `qbrecs` param since we are not doing anything with it.
So experiment with modifying line `if (gbrecs == null && df.isReleased())` to just ` if (df.isReleased())`. 
`gbr = guestbookResponseService.initAPIGuestbookResponse(df.getOwner(), df, session, apiTokenUser);` will take care of setting guestbook for dataset. 

In the future we should parse guestbook sent by user and validate it against actual guestbook set on a dataset.

**Review by dbojanek — APPROVED** [review]

**Review by dbojanek — APPROVED** [review]
