### PR TITLE
Closes #1180: Fix error on sending email notification

### LINKED ISSUE #1180: Error when sending notification email
```
Caused by: org.jboss.weld.context.ContextNotActiveException: WELD-001303: No active contexts for scope type javax.enterprise.context.SessionScoped
        at org.jboss.weld.manager.BeanManagerImpl.getContext(BeanManagerImpl.java:708)
        at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.getIfExists(ContextualInstanceStrategy.java:90)
        at org.jboss.weld.bean.ContextualInstanceStrategy$CachingContextualInstanceStrategy.getIfExists(ContextualInstanceStrategy.java:165)
        at org.jboss.weld.bean.ContextualInstance.getIfExists(ContextualInstance.java:63)
        at org.jboss.weld.bean.proxy.ContextBeanInstance.getInstance(ContextBeanInstance.java:83)
        at org.jboss.weld.bean.proxy.ProxyMethodHandler.getInstance(ProxyMethodHandler.java:125)
        at edu.harvard.iq.dataverse.DataverseSession$Proxy$_$$_WeldClientProxy.getLocaleCode(Unknown Source)
        at edu.harvard.iq.dataverse.util.SystemConfig.getGuidesBaseUrl(SystemConfig.java:155)
        at sun.reflect.GeneratedMethodAccessor546.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:1081)
        at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:1153)
        at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4786)
        at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:656)
        at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
        at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:608)
        at org.jboss.weld.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:64)
        at org.jboss.weld.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
```

### PR DESCRIPTION
**Pull request by dbojanek**

### CODE REVIEW

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/mail/MailMessageCreator.java [hunk 1]
```diff
@@ -261,7 +261,7 @@ private String dataverseMessage(EmailNotificationDto notificationDto, Dataverse
                                                                                         parentDataverse != null ? parentDataverse.getDisplayName() : "",
                                                                                         parentDataverse != null ? getDataverseLink(
                                                                                                 parentDataverse) : "",
-                                                                                        systemConfig.getGuidesBaseUrl(),
+                                                                                        systemConfig.getGuidesBaseUrl(session.getLocale()),
```
Comment (madryk) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/mail/MailMessageCreator.java]: Also here there can be no `SessionScope`.
It will be better to do: `notificationDto.getNotificationReceiver().getNotificationsLanguage()`
As we would point to guide in language that is the same as email content.

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/mail/MailMessageCreator.java [hunk 2]
```diff
@@ -370,7 +370,7 @@ private String datasetVersionMessage(EmailNotificationDto notificationDto, Datas
                                                                                       getDatasetLink(version.getDataset()),
                                                                                       version.getDataset().getOwner().getDisplayName(),
                                                                                       getDataverseLink(version.getDataset().getOwner()),
-                                                                                      systemConfig.getGuidesBaseUrl(),
+                                                                                      systemConfig.getGuidesBaseUrl(session.getLocale()),
```
Comment (madryk) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/mail/MailMessageCreator.java]: same as above

Comment (madryk) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/mail/MailMessageCreator.java]: Also it would be good idea to extract `notificationDto.getNotificationReceiver().getNotificationsLanguage()` to some variable - for example `notificationEmailLanguage` in methods.
And get rid of `private DataverseSession session;` in this class.

**Review by madryk — CHANGES_REQUESTED** [review]
Can you check that emails are sending and WELD-001303: No active contexts for scope type javax.enterprise.context.SessionScoped is not thrown? For example in case of publish dataset operation

**Review by madryk — APPROVED** [review]
