### PR TITLE
Closes #2340: Fix NPE when exporting dataset with empty vocabulary field

### LINKED ISSUE #2340: NPE when exporting dataset with empty controlled vocabulary field
Stacktrace:
```
[2023-03-24T13:53:02.153+0000] [glassfish 4.1] [SEVERE] [] [] [tid: _ThreadID=32 _ThreadName=Thread-9] [timeMillis: 1679665982153] [levelValue: 1000] [[
  java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:657)
        at java.util.ArrayList.get(ArrayList.java:433)
        at edu.harvard.iq.dataverse.api.dto.DatasetFieldDTO$Creator.extractValue(DatasetFieldDTO.java:269)
        at edu.harvard.iq.dataverse.api.dto.DatasetFieldDTO$Creator.extractChildren(DatasetFieldDTO.java:258)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
        at edu.harvard.iq.dataverse.api.dto.DatasetFieldDTO$Creator.create(DatasetFieldDTO.java:226)
        at edu.harvard.iq.dataverse.api.dto.MetadataBlockWithFieldsDTO$Creator.create(MetadataBlockWithFieldsDTO.java:52)
        at edu.harvard.iq.dataverse.api.dto.DatasetVersionDTO$Converter.lambda$extractMetadatablocks$1(DatasetVersionDTO.java:258)
```

Solution: if `DatasetFieldDTO$Creator` finds controlled vocabulary with no values assigned it should skip this field in the final result.

### PR DESCRIPTION
**Pull request by wtr-icm**

### CODE REVIEW

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/dto/DatasetFieldDTO.java [hunk 1]
```diff
@@ -225,6 +225,9 @@ public List<DatasetFieldDTO> create(List<DatasetField> datasetFields) {
                             .map(this::extractChildren)
                             .collect(Collectors.toList());
                 }
+                if (values.isEmpty()) {
+                    continue;
+                }
```
Comment (madryk) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/dto/DatasetFieldDTO.java:230]: From th stacktrace we see that we had problems also with `extractChildren` -> `extractValue`. And this fix doesn't address that

**Review by madryk — CHANGES_REQUESTED** [review]

**Review by madryk — APPROVED** [review]
