### PR TITLE
Closes #938: Fixed Fallback on Compound Labels

### LINKED ISSUE #938: Fix improper fallback of compound labels (crystallographic metadata)
Currently we fallback to child label, while we should do the old way (Parent Child). As a result, in advanced search we have fields labeled A, B and C.

### PR DESCRIPTION
**Pull request by dbojanek**

### CODE REVIEW

File: dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/dataset/DatasetFieldType.java [hunk 1]
```diff
@@ -438,7 +438,7 @@ public boolean isHasRequiredChildren() {
         return false;
     }
 
-    public boolean isHasParent() {
+    public boolean hasParent() {
```
Comment (madryk) [inline dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/dataset/DatasetFieldType.java]: `Is` allows for field to be interpreted in xhtml as getter. So it probably breaks xhtml in some places (`#{dsft.hasParent}` will not work - it has to be changed to `#{dsft.hasParent()}`)

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/SearchServiceBean.java [hunk 2]
```diff
@@ -792,11 +792,7 @@ public String getLocaleFacetLabelName(String facetLabelName, String facetCategor
     }
 
     private String getDatasetFieldFacetCategoryName(DatasetFieldType matchedDatasetField) {
-        if (matchedDatasetField.isFacetable()) {
-            if (matchedDatasetField.getParentDatasetFieldType() != null) {
-                return matchedDatasetField.getLocaleTitleWithParent();
-            }
-
+        if (matchedDatasetField.isFacetable() && !matchedDatasetField.hasParent()) {
             return getStringFromBundle(format(FACETBUNDLE_MASK_VALUE, matchedDatasetField.getName()));
```
Comment (madryk) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/SearchServiceBean.java]: We can't be sure that extra label `facets.search.fieldtype.%s.label` will exists. Consider for example situations with custom metadata blocks

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/SearchServiceBean.java [hunk 3]
```diff
@@ -792,11 +792,7 @@ public String getLocaleFacetLabelName(String facetLabelName, String facetCategor
     }
 
     private String getDatasetFieldFacetCategoryName(DatasetFieldType matchedDatasetField) {
-        if (matchedDatasetField.isFacetable()) {
-            if (matchedDatasetField.getParentDatasetFieldType() != null) {
-                return matchedDatasetField.getLocaleTitleWithParent();
-            }
-
+        if (matchedDatasetField.isFacetable() && !matchedDatasetField.hasParent()) {
```
Comment (madryk) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/SearchServiceBean.java]: Not really sure what for there is check for parent field. But in old version check was inverse to what it is now. Is it intentional?

**Review by madryk — CHANGES_REQUESTED** [review]

File: dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/dataset/DatasetFieldType.java (hunk 1 above)
Comment (dbojanek) [reply dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/dataset/DatasetFieldType.java]: I'll refactor it back then for clearance.

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/SearchServiceBean.java (hunk 3 above)
Comment (dbojanek) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/SearchServiceBean.java]: Overall logic here was not changed. I only moved code a little to avoid calling `matchedDatasetField.getDisplayName();` twice since we are no longer using `matchedDatasetField.getLocaleTitleWithParent();`.

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/SearchServiceBean.java [hunk 4]
```diff
@@ -792,12 +793,12 @@ public String getLocaleFacetLabelName(String facetLabelName, String facetCategor
     }
 
     private String getDatasetFieldFacetCategoryName(DatasetFieldType matchedDatasetField) {
-        if (matchedDatasetField.isFacetable()) {
-            if (matchedDatasetField.getParentDatasetFieldType() != null) {
-                return matchedDatasetField.getLocaleTitleWithParent();
+        if (matchedDatasetField.isFacetable() && !matchedDatasetField.isHasParent()) {
+            try {
+                return getStringFromBundle(format(FACETBUNDLE_MASK_VALUE, matchedDatasetField.getName()));
```
Comment (madryk) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/SearchServiceBean.java]: Now you will get empty string for some datasetfield types - Check `getStringFromBundle` implementation

**Review by madryk — CHANGES_REQUESTED** [review]

**Review by madryk — APPROVED** [review]
