### PR TITLE
Closes #550: Fix for obtaining app version

### LINKED ISSUE #550: SystemConfig.getVersion don't return proper version

### PR DESCRIPTION
**Pull request by madryk**

### CODE REVIEW

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/util/SystemConfig.java [hunk 1]
```diff
@@ -54,102 +59,27 @@ public String getVersion(boolean withBuildNumber) {
...
+            // version.properties file using resource filtering
+            
+            Try<String> appVersionTry = Try.withResources(() -> getClass().getResourceAsStream(VERSION_PROPERTIES_CLASSPATH))
+                    .of(is -> {
+                        Properties properties = new Properties();
+                        properties.load(is);
+                        return properties;
+                    })
+                    .map(p -> p.getProperty(VERSION_PROPERTIES_KEY));
+
```
Comment (wtr-icm) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/util/SystemConfig.java:72]: I wonder if we can somehow get rid of the following ```if```?
Maybe we could create Tuple of {result, logging function}, so after line 71 (we would have also to change the type of variable we're assigning that result to) we'd have sth like:
```java
.map(v -> StringUtils.equals(v, VERSION_PLACEHOLDER)
    ? Tuple.of(VERSION_FALLBACK, () -> logger.warning(…))
    : Tuple.of(v, () -> {})
.getOrElse(Tuple.of(VERSION_FALLBACK, () -> logger.warning(…));

// call result._2
return result._1;
```
The only problem of this approach could be proper handling of generic parameters.

**Review by wtr-icm — APPROVED** [review]
