### PR TITLE
Closes #1625: Fixed order change while dis/enabling guestbooks + some refactor

### LINKED ISSUE #1625: De/activation button for one questbook changes status of some other guestbook, but not the one it seems to be related to ;-)
image

### PR DESCRIPTION
**Pull request by dbojanek**
I added some refactor to make page less dynamic. Making full data reload on disabling/enabling guestbook and on deselecting guestbooks from root seemed unnecessary. 
Too many db calls were made and I don't think that the purpose of this page requires that fresh data to be handled each time user performs some operation on it.

### CODE REVIEW

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/guestbook/ManageGuestbooksPage.java [hunk 1]
```diff
@@ -110,7 +110,8 @@ public String init() {
             displayDownloadAll = true;
         }
 
-        refreshGuestbooks();
+        dataverse = dvService.find(dataverseId);
```
Comment (madryk) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/guestbook/ManageGuestbooksPage.java]: Why we obtain dataverse for the second time? We already did it in this method.

File: dataverse-webapp/src/main/webapp/manage-guestbooks.xhtml [hunk 2]
```diff
@@ -112,46 +112,44 @@
                                         </h:outputFormat>
                                     </em>
                                 </div>
-                                <div class="button-block">
+                                <div class="btn-group" role="group">
                                     <p:commandLink type="button" styleClass="btn btn-default btn-access"
-                                                   value="#{bundle['dataset.manageGuestbooks.tab.action.btn.enable']}"
-                                                   rendered="#{manageGuestbooksPage.dataverse.id eq guestbook.dataverse.id and !guestbook.enabled}"
```
Comment (madryk) [inline dataverse-webapp/src/main/webapp/manage-guestbooks.xhtml:118]: `manageGuestbooksPage.dataverse.id eq guestbook.dataverse.id` part of rendered was causing that button wasn't rendered in case guestbook was defined in parent dataverse. Now admin of child dataverse will be able to turn on/off guestbooks in parent dataverse

File: dataverse-webapp/src/main/webapp/manage-guestbooks.xhtml [hunk 3]
```diff
@@ -112,46 +112,44 @@
                                         </h:outputFormat>
                                     </em>
                                 </div>
-                                <div class="button-block">
+                                <div class="btn-group" role="group">
```
Comment (madryk) [inline dataverse-webapp/src/main/webapp/manage-guestbooks.xhtml]: This change in hierarchy of buttons is causing different rendering than before.

**Review by madryk — CHANGES_REQUESTED** [review]

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/guestbook/ManageGuestbooksPage.java (hunk 1 above)
Comment (dbojanek) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/guestbook/ManageGuestbooksPage.java]: A remnant from `refreshGuestbooks` method.

File: dataverse-webapp/src/main/webapp/manage-guestbooks.xhtml (hunk 2 above)
Comment (dbojanek) [reply dataverse-webapp/src/main/webapp/manage-guestbooks.xhtml:118]: Yeah, my bad. I didn't realize you should not be able to turn inherited guestbook on/off..

**Review by madryk — APPROVED** [review]
