### PR TITLE
Closes #2189: Fix Unpublished badge on search results

### LINKED ISSUE #2189: If a dataset has a deaccessioned version, in search results files from this dataset are labeled as "Unpublished", while they may still be accessible in some other version

### PR DESCRIPTION
**Pull request by wtr-icm**

### CODE REVIEW

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/index/IndexServiceBean.java [hunk 1]
```diff
@@ -598,21 +617,23 @@ private String addOrUpdateDataset(IndexableDataset indexableDataset) {
...
         if (state.equals(IndexableDataset.DatasetState.PUBLISHED)) {
             solrInputDocument.addField(SearchFields.PUBLICATION_STATUS, SearchPublicationStatus.PUBLISHED.getSolrValue());
+            SolrInputField field = solrInputDocument.getField(SearchFields.PUBLICATION_STATUS);
+            if (field.getValues().stream().anyMatch(v -> SearchPublicationStatus.UNPUBLISHED.getSolrValue().equals(v))) {
+                List<Object> values = field.getValues().stream()
+                        .filter(v -> !SearchPublicationStatus.UNPUBLISHED.getSolrValue().equals(v))
+                        .collect(Collectors.toList());
+                solrInputDocument.removeField(SearchFields.PUBLICATION_STATUS);
+                solrInputDocument.addField(SearchFields.PUBLICATION_STATUS, values);
+            }
```
Comment (madryk) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/index/IndexServiceBean.java]: Its hard for me to think up an example when this code would have any effect.
`SearchPublicationStatus.UNPUBLISHED` will be present only if indexable dataset have state `IndexableDataset.DatasetState.WORKING_COPY` and `majorVersionReleaseDate` is null.
This code runs only in indexable dataset have state `IndexableDataset.DatasetState.PUBLISHED` so it cancels each other out

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/index/IndexServiceBean.java [hunk 2]
```diff
@@ -547,6 +549,23 @@ private String deleteDraftFiles(List<String> solrDocIdsForDraftFilesToDelete) {
...
+        }
+        Long major = currentVersion.getVersionNumber();
+        for (DatasetVersion version : dataset.getVersions()) {
+            if (Objects.equals(version.getVersionNumber(), major)
+                && Objects.equals(version.getMinorVersionNumber(), 0L)) {
+                return version.getReleaseTime();
+            }
+        }
+        return dataset.getMostRecentMajorVersionReleaseDate();
+    }
```
Comment (madryk) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/index/IndexServiceBean.java]: I would rather have this logic without the use of `getMostRecentMajorVersionReleaseDate`. Keeping track what is going on here is rather complex.

**Review by madryk — CHANGES_REQUESTED** [review]

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/index/IndexServiceBean.java (hunk 2 above)
Comment (wtr-icm) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/index/IndexServiceBean.java]: I've added some clarifying comments, because I think, that it's better to not duplicate code from `getMostRecentMajorVersionReleaseDate()`. On the other hand, current method was written in order to circumvent some deficiencies of `getMostRecentMajorVersionReleaseDate`.

Comment (madryk) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/index/IndexServiceBean.java]: Also there is an option of change the way we look at `getMostRecentMajorVersionReleaseDate`. Maybe by `releaseDate` we could think about not the state of version `PUBLISHED` but if version was ever released `.getReleaseTime() != null`. That way we could still use `getMostRecentMajorVersionReleaseDate` but instead of checking `if (version.isReleased()` we would check `if (version.getReeleaseTime() != null`. It's just a thought.
I will accept the pull request either way and let you decide.

**Review by madryk — APPROVED** [review]

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/index/IndexServiceBean.java (hunk 2 above)
Comment (wtr-icm) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/index/IndexServiceBean.java]: Ok, somehow I was not aware that `getMostRecentMajorVersionReleaseDate` was used only in that single place. So I've followed your idea and ultimately removed `findReleaseDate`, having replaced it by corrected version of `getMostRecentMajorVersionReleaseDate` (which was also moved from `Dataset` to `IndexServiceBean`).
