### PR TITLE
Closes #2133: Fix upload

### LINKED ISSUE #2133: Upload of large files while creating new dataset fails

### PR DESCRIPTION
**Pull request by wtr-icm**

### CODE REVIEW

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/IngestServiceBean.java [hunk 1]
```diff
@@ -155,6 +155,7 @@
     // DataFileCategory objects, if any were already assigned to the files).
     // It must be called before we attempt to permanently save the files in
     // the database by calling the Save command on the dataset and/or version.
+    @TransactionAttribute(TransactionAttributeType.NOT_SUPPORTED)
     public List<DataFile> saveAndAddFilesToDataset(DatasetVersion version, List<DataFile> newFiles) {
```
Comment (madryk) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/IngestServiceBean.java:159]: Did we check that removing transaction here doesn't cause any problems with file replacing through UI (`ReplaceFileHandler.integrateFileWithDataset`)?

Comment (wtr-icm) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/IngestServiceBean.java:159]: I've checked (on three different files) and it seems to work properly.

**Review by madryk — APPROVED** [review]
