### PR TITLE
Closes #534: Fix advanced page not rendering when no session is active

### LINKED ISSUE #534: Advanced search page not rendering when it is the first page what user visits

### PR DESCRIPTION
**Pull request by madryk**

### CODE REVIEW

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/AdvancedSearchPage.java [hunk 1]
```diff
@@ -87,12 +95,16 @@ public void init() {
      * @throws IOException
      */
     public String find() throws IOException {
+        Map<String, Object> sessionMap = FacesContext.getCurrentInstance().getExternalContext().getSessionMap();
+        Object context = FacesContext.getCurrentInstance().getExternalContext().getContext();
+//        System.out.println("SESSION: " + FacesContext.getCurrentInstance().getExternalContext().getSessionMap());
+//        System.out.println("CONTEXT: " + FacesContext.getCurrentInstance().getExternalContext().getContext());
```
Comment (dbojanek) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/AdvancedSearchPage.java]: Remove commented code.

**Review by dbojanek — CHANGES_REQUESTED** [review]

**Review by dbojanek — APPROVED** [review]
