### PR TITLE
Closes #406: Command and Group Exceptions made Runtime

### LINKED ISSUE #406: Make CommandException and GroupException a RuntimeException

### PR DESCRIPTION
**Pull request by dbojanek**

### CODE REVIEW

**Review by MrK191 — CHANGES_REQUESTED** [review]
Since those are runtime now, you should also find and remove throws clause next to the methods, so you don't force anyone to take care of it when using method.

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/engine/command/impl/AbstractDatasetCommand.java [hunk 1]
```diff
@@ -93,10 +93,10 @@ protected void createDatasetUser(CommandContext ctxt) {
      * @param dsv     The dataset version whose fields we validate
      * @param lenient when {@code true}, invalid fields are populated with N/A
      *                value.
-     * @throws CommandException if and only if {@code lenient=false}, and field
+     * @ if and only if {@code lenient=false}, and field
```
Comment (MrK191) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/engine/command/impl/AbstractDatasetCommand.java]: I think you can leave the comment, when will CommandException occur.

File: dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/group/ExplicitGroup.java [hunk 2]
```diff
@@ -154,10 +154,10 @@ public void add(User u) {
      * Adds the {@link RoleAssignee} to {@code this} group.
      *
      * @param ra the role assignee to be added to this group.
-     * @throws GroupException if {@code ra} is a group, and is either an ancestor of {@code this},
+     * @ if {@code ra} is a group, and is either an ancestor of {@code this},
```
Comment (MrK191) [inline dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/group/ExplicitGroup.java]: I think you can leave the comment, when will CommandException occur.

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/engine/command/impl/ImportDatasetCommand.java [hunk 3]
```diff
@@ -44,10 +44,10 @@ public ImportDatasetCommand(Dataset theDataset, DataverseRequest aRequest) {
      * Validate that the PID of the dataset, if any, exists.
      *
      * @param ctxt
-     * @throws CommandException
+     * @
```
Comment (MrK191) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/engine/command/impl/ImportDatasetCommand.java]: you can remove @ now.

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/workflow/WorkflowServiceBean.java [hunk 4]
```diff
@@ -97,10 +97,10 @@ public WorkflowServiceBean() {
      *
      * @param wf   the workflow to execute.
      * @param ctxt the context in which the workflow is executed.
-     * @throws CommandException If the dataset could not be locked.
+     * @ If the dataset could not be locked.
```
Comment (MrK191) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/workflow/WorkflowServiceBean.java]: I think you can leave the comment, when will CommandException occur.

**Review by MrK191 — CHANGES_REQUESTED** [review]

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/engine/command/impl/AbstractDatasetCommand.java [hunk 5]
```diff
@@ -154,9 +154,9 @@ protected void tidyUpFields(DatasetVersion dsv) {
      *
      * @param theDataset
```
Comment (MrK191) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/engine/command/impl/AbstractDatasetCommand.java]: I think this doc can be removed since it doesn't contribute anything.

**Review by MrK191 — CHANGES_REQUESTED** [review]

**Review by MrK191 — APPROVED** [review]
