### PR TITLE
Closes #1363: Fix DDI exporter – allow multiple collMode

### LINKED ISSUE #1363: Exporting metadata in DDI format sometimes results in 403

### PR DESCRIPTION
**Pull request by wtr-icm**

### CODE REVIEW

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/export/ddi/DdiExportUtil.java [hunk 1]
```diff
@@ -50,52 +54,57 @@
     public static final String NOTE_TYPE_CONTENTTYPE = "DATAVERSE:CONTENTTYPE";
     public static final String NOTE_SUBJECT_CONTENTTYPE = "Content/MIME Type";
 
-    public static String datasetDtoAsJson2ddi(String datasetDtoAsJson, String dataverseUrl) {
+    public static String datasetDtoAsJson2ddi(String datasetDtoAsJson, String dataverseUrl,
+                                              Map<String, Map<String, String>> localizedVocabularyIndex) {
```
Comment (madryk) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/export/ddi/DdiExportUtil.java:58]: IMO we should convert this to real class (not static oriented) ASAP. Traversing in methods with more and more arguments seems to add extra complexity that IMO should not be present here.

Actually it seems that this is not a impossible task to do.
Usage of this class is inside two places `DDIExporter` and `OAI_DDIExporter`

If we would make every method in this class non static (with additional change of class name), then we could change `ExportService.loadAllExporters` in a way that it would create instance of this class (or in another aproach we could make this a Stateless class - and inject it in ExportService or in third option we could make `DDIExporter` and `OAI_DDIExporter` stateless that would inject this class and in `ExportService.loadAllExporters` just add them to the map)

That way we could avoid chaining `dataverseUrl` and `localizedVocabularyIndex` through method arguments and obtain what we need when they are needed.

What do you think about that?

File: dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/export/VocabularyValuesIndexerTest.java [hunk 2]
```diff
@@ -0,0 +1,77 @@
...
+
+        // when
+        Map<String, Map<String, String>> index = indexer.indexLocalizedNamesOfUsedKeysByTypeAndValue(
+                datasetVersion, Locale.ENGLISH);
+
+        // then
+        assertThat(index.keySet()).containsExactlyInAnyOrder(vocabularyType1, vocabularyType2);
+
+        assertThat(index.get(vocabularyType1)).hasSize(3);
+        assertThat(index.get(vocabularyType1).get("value 1-1")).isEqualTo("value 1-1");
```
Comment (madryk) [inline dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/export/VocabularyValuesIndexerTest.java]: Test doesn't really reveal the intention behind this class and relies on `NullPointerException` catch inside `getLocaleStrValue` of the class - and this is more uncommon usage in real environment (actually catch on npe is only done for tests). To really test it we should use real bundle translation.

**Review by madryk — CHANGES_REQUESTED** [review]

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/export/ddi/DdiExportUtil.java (hunk 1 above)
Comment (madryk) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/export/ddi/DdiExportUtil.java:58]: We decided to move this into separate task: #1391

**Review by madryk — APPROVED** [review]
