### PR TITLE
Closes #1486: Fixed licenses and tags editing on released dataset.

### LINKED ISSUE #1486: Changin of licenses of files, deleting files or editing tags  in a published dataset not having a draft results in an unknown error

### PR DESCRIPTION
**Pull request by MrK191**

### CODE REVIEW

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/datafile/file/FileMetadataService.java [hunk 1]
```diff
@@ -96,7 +97,8 @@ public FileMetadata updateFileMetadataWithProvFreeForm(FileMetadata fileMetadata
     }
 
     public List<FileMetadata> findFileMetadata(Long...fileMetadataId) {
-        return fileMetadataRepository.findFileMetadata(Arrays.stream(fileMetadataId).collect(Collectors.toList()));
+        List<Long> fileIds = Arrays.stream(fileMetadataId).collect(Collectors.toList());
```
Comment (madryk) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/datafile/file/FileMetadataService.java]: We could omit stream and use `Arrays.toList` directly

**Review by madryk — CHANGES_REQUESTED** [review]

**Review by madryk — APPROVED** [review]
