### PR TITLE
Closes #1589: Fixed missing facet translation for harvested datasets

### LINKED ISSUE #1589: Some Polish translations are missing for harversted datasets

### PR DESCRIPTION
**Pull request by dbojanek**

### CODE REVIEW

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/response/SolrSearchResult.java [hunk 1]
```diff
@@ -147,21 +147,12 @@ public void setHarvested(boolean harvested) {
     }
 
     public String getHarvestingDescription() {
```
Comment (wtr-icm) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/response/SolrSearchResult.java]: Probably will clash with your changes from the first merge request.

**Review by wtr-icm — APPROVED** [review]
