### PR TITLE
 Closes #1496: Fix integration tests config

### LINKED ISSUE #1496: Fix asm classpath issues and configuration of integration tests

### PR DESCRIPTION
**Pull request by madryk**
To fix the issues:
 - library `asm` in version `> 3` was excluded from the project (glassfish was complaining that `org.objectweb.asm.ClassVisitor` is a class instead of interface)
   - for tika-parsers it was excluded - it is used only in https://github.com/apache/tika/blob/main/tika-parsers/tika-parsers-classic/tika-parsers-classic-modules/tika-parser-code-module/src/main/java/org/apache/tika/parser/asm/XHTMLClassVisitor.java . Alongside this change maybe one of the tika parser will be throwing some errors (`ClassParser` - used for some parsing of `.class` java files) (maybe in future we could configure tika to just skip this parser if it would be necessary) but it is not likely that we will use this parser.
   - for oidc library - dependent library json-smart was downgraded `2.3` -> `2.1.1` - from oidc lib it should be ok as they define it as valid lib version - in oidc lib pom.xml:
```
		<dependency>
			<groupId>net.minidev</groupId>
			<artifactId>json-smart</artifactId>
			<version>[1.3.1,2.3]</version>
		</dependency>
```
 - in webapp integration test config `WorkflowExecutionWorker.class` was removed from deployment because it was causing problems (not existing jms queues). If we would like to make integration tests that will use workflows we would probably need to include queues for workflows in `glassfish-resources.xml`
 - updated solr schema used in int tests to exacly the same as in `dataverse/conf/solr/7.3.1/schema.xml`
 - some corrections to tests that was failing (due to incorrect initial test db setup, transaction support, etc.)

### CODE REVIEW

File: dataverse-persistence/src/test/java/edu/harvard/iq/dataverse/persistence/datafile/FileMetadataRepositoryIT.java [hunk 1]
```diff
@@ -28,8 +28,8 @@ public void findFileMetadataByDatasetVersionIdWithPagination() {
         //then
         assertEquals(foundFiles.size(), 3);
         assertEquals(110, foundFiles.get(0).getId().longValue());
-        assertEquals(113, foundFiles.get(1).getId().longValue());
-        assertEquals(112, foundFiles.get(2).getId().longValue());
+        assertEquals(112, foundFiles.get(1).getId().longValue());
+        assertEquals(113, foundFiles.get(2).getId().longValue());
```
Comment (wtr-icm) [inline dataverse-persistence/src/test/java/edu/harvard/iq/dataverse/persistence/datafile/FileMetadataRepositoryIT.java:32]: Here and in the next test we could use jassert with `extracting(…).containsExactlyInAnyOrder(…)`.

**Review by wtr-icm — APPROVED** [review]
