### PR TITLE
Closes #3207: Fix assign role email for collection sent twice

### LINKED ISSUE #3207: Curator role assignment notification is sent twice
The You have been assigned a role email notification is sent twice for the Curator role. The second email is received a couple seconds after the first (15:11:41 vs 15:11:56). Email recipient and the content is exactly the same:

```
Hello,

You are now Curator for the dataverse "Institut de Biologia Evolutiva (CSIC-UPF)" (view at https://fairbirds-test.icm.edu.pl/dataverse/csic-upf ).

You may contact us for support at fairbirds-test@icm.edu.pl.

Thank you,
FAIRBiRDS Support
```

Context: I am the Depositor and Curator of a dataset (draft, unpublished). When I try to publish it, a window pops up that says that the admin should first publish the collection before I can publish the dataset.
After the admin of this collection publishes the collection, I get an email that I have been assigned Depositor/Curator for the collection. However, I was already assigned this role and was already informed by email (in this very instance 1 hour ago). The emails are virtually identical. This is confusing.

### PR DESCRIPTION
**Pull request by madryk**
The problem occurred because of the mismatch in conditions used in `PublishDataverseCommad` and `ManagePermissionsService`.

I've changed the condition a little bit. The only reason why we should not send notification to user about assigned role is when the user do not have the ability to see the collection (url to collection is inside the email). That is when collection is unpublished and the user do not have a permission to view unpublished collection.

In such cases we postpone sending the notification until the collection is published.

### CODE REVIEW

File: fairchive-webapp/src/main/java/edu/harvard/iq/dataverse/permission/ManagePermissionsService.java [hunk 1]
```diff
@@ -69,14 +69,20 @@ public RoleAssignment assignRoleWithNotification(DataverseRole role, RoleAssigne
     }
 
     /***
-     * For FILE_DOWNLOADER role we don't notify user if dataset is unpublished since with FILE_DOWNLOADER role
-     * user is not able to access dataset.
-     * @param role - role to be assigned
-     * @param object - object to which we assign role
-     * @return false if role is FILE_DOWNLOADER and dataverse is unpublished
+     * For unpublished dataverses and datasets we do not send a notification
+     * if the assigned role do not allow to go to the dataverse or dataset page.
```
Comment (sniewczas) [inline fairchive-webapp/src/main/java/edu/harvard/iq/dataverse/permission/ManagePermissionsService.java]:
```suggestion
     * if the assigned role does not allow to go to the dataverse or dataset page.
```

File: fairchive-webapp/src/main/java/edu/harvard/iq/dataverse/permission/ManagePermissionsService.java [hunk 2]
```diff
@@ -69,14 +69,20 @@ public RoleAssignment assignRoleWithNotification(DataverseRole role, RoleAssigne
...
+     * If we would send such notification then the user would obtain a notification
+     * with a link that he cannot access.
+     * Sending this notification will be postponed when objects will be published.
```
Comment (sniewczas) [inline fairchive-webapp/src/main/java/edu/harvard/iq/dataverse/permission/ManagePermissionsService.java]:
```suggestion
     * Sending this notification will be postponed until the object is published.
```

**Review by sniewczas — APPROVED** [review]

**Comment by madryk** [comment]
I forgot to run the integration tests - and it turned out to not pass. So I've corrected it.
