### PR TITLE
Closes #538: Fixed redirection while logging with O2Auth

### LINKED ISSUE #538: Fix redirect when logging with google - /oauth/dataverseuser.xhtml

### PR DESCRIPTION
**Pull request by dbojanek**

### CODE REVIEW

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/authorization/providers/oauth2/OAuth2LoginBackingBean.java [hunk 1]
```diff
@@ -62,6 +62,9 @@
     OAuth2FirstLoginPage newAccountPage;
 
     public String linkFor(String idpId, String redirectPage) {
+        if(redirectPage.equals("dataverseuser.xhtml")) {
+            redirectPage = "/dataverseuser.xhtml?selectTab=dataRelatedToMe";
+        }
```
Comment (madryk) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/authorization/providers/oauth2/OAuth2LoginBackingBean.java]: Are you sure that we can't do something similar on DataverseUserPage.init ? That way we could fix every problem that we have with dataverseuser.xhtml page in one sweep. Currently when we try to go to register page when we are logged in (with entering url by hand) we have weird behaviour.
```
public void init() {
    if (session.getUser().isAuthenticated() && (mode == CREATE || mode == FORGOT)) {
        Faces.redirect("/");
        return;
    }
    if (!session.getUser().isAuthenticated() && (mode == EDIT || mode == CHANGE_PASSWORD)) {
        Faces.redirect("loginpage.xhtml")    
        return;
    }
}
```
--- OUTDATED --- WILL NOT WORK ---

**Review by madryk — CHANGES_REQUESTED** [review]

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/authorization/providers/oauth2/OAuth2LoginBackingBean.java (hunk 1 above)
Comment (madryk) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/authorization/providers/oauth2/OAuth2LoginBackingBean.java]: Ok. I don't think it touches the root of the problem. The real problem is that when going on login page from register we got:
https://.../loginpage.xhtml?redirectPage=dataverseuser.xhtml
but redirectPage param should have encoded slash
`%2Fdataverseuser.xhtml`

**Review by madryk — APPROVED** [review]
