### PR TITLE
2795 fix various issues with saving search results to file feature

### LINKED ISSUE #2795: Fix various issues with saving search results to file feature
Label on the button. IS: Save to file SHOULD BE: Save To File

        
      We should never disclose e-mail of a contact person (we hide it on UI), so Superuser should not be able to select citation→Contact→E-mail.

        
      For compound fields, the parent field should not be shown in the CSV – it will not have any value independent of the values of its child fields that may already be there. For instance, there is nothing to show for "citation->Author". If there is "citation->Author->Name", "citation->Author->Identifier Scheme" etc. – these child fields will provide all the information there may be.

        
      There are clearly some (many) values missing in the CSV. For instance all datasets will have at least one author and a description, but they are missing in the CSV. So something is not exporting.

### PR DESCRIPTION
**Pull request by lbownik**
Closes #2795 Fix various issues with saving search results to file feature

### CODE REVIEW

**Review by rscipien — APPROVED** [review]

File: dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/dataset/DatasetFieldType.java [hunk 1]
```diff
@@ -196,6 +197,10 @@ public String getDisplayFormat() {
         return displayFormat;
     }
     
+    public boolean isExportableToFile() {
+        return !this.fieldType.equals(EMAIL);
```
Comment (diasf) [inline dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/dataset/DatasetFieldType.java:201]: Nit: To make the "why?" more obvious, what about renaming the method to `isAccessRestricted` or `isConfidential`?

File: dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/dataset/DatasetFieldType.java [hunk 2]
```diff
@@ -196,6 +197,10 @@ public String getDisplayFormat() {
...
+    }
+    
 
     public boolean isExportToFile() {
```
Comment (diasf) [inline dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/dataset/DatasetFieldType.java:206]: Do we need to have a migration script to unset this flag for EMAIL fields on running instances?

**Review by diasf — APPROVED** [review]
.

File: dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/dataset/DatasetFieldType.java (hunk 2 above)
Comment (lbownik) [reply dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/dataset/DatasetFieldType.java:206]: No. this feature is not in production yet.
