### PR TITLE
Closes #3227 Automatic translation of metadata does not work

### LINKED ISSUE #3227: Automatic translation of metadata does not work
https://git.icm.edu.pl/dariah/archeo/-/issues/237

### PR DESCRIPTION
**Pull request by lbownik**

### CODE REVIEW

File: fairchive-webapp/src/main/java/edu/harvard/iq/dataverse/dataset/tab/DatasetMetadataTab.java [hunk 1]
```diff
@@ -219,13 +223,18 @@ private List<DatasetFieldsByType> translateByType(List<DatasetFieldsByType> fiel
...
+			final List<String> flatValues = flatten(fields);
+			
+			final List<String> translated = DatasetMetadataTab.this.translator.
+					translate(flatValues, this.selectedLanguageCode);
+			
+			int index = 0;
 			for (final DatasetField field : fields) {
 				final DatasetField newField = field.copy();
-				newField.setValue(translate(field.getValue()));
+				newField.setValue(translated.get(index++));
```
Comment (rscipien) [inline fairchive-webapp/src/main/java/edu/harvard/iq/dataverse/dataset/tab/DatasetMetadataTab.java:234]: In case when translation was not found there is a chance that datasetfield list size will not match translations list size?

eq
Jan - John
Piotr - Peter

vs

Jan - John
Test123 - ?Peter? (translation was not found)
Piotr - [Translation for Piotr will be matched with Test123]

Comment (lbownik) [reply fairchive-webapp/src/main/java/edu/harvard/iq/dataverse/dataset/tab/DatasetMetadataTab.java:234]: no - translation list  size and order will always mach source texts list size and order - if something goes wrong translation service will sibmply return source text

**Review by rscipien — APPROVED** [review]
