### PR TITLE
Closes #2049: Fix search results incorrectly marked as linked

### LINKED ISSUE #2049: In search results, datasets from subdataverses are incorrectly marked as linked

### PR DESCRIPTION
**Pull request by wtr-icm**

### CODE REVIEW

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/SearchIncludeFragment.java [hunk 1]
```diff
@@ -262,7 +261,14 @@ public void search(Dataverse dataverse) {
...
          * @todo centralize this into SearchServiceBean
          */
-        Optional<String> filterDownToSubtree = buildSubtreeFilterIfNeeded(dataverse);
+        Optional<String> filterDownToSubtree;
+        if (!dataverse.isRoot()) {
+            dataversePath = dataverseDao.determineDataversePath(dataverse);
+            filterDownToSubtree = Optional.of(SearchFields.SUBTREE + ":\"" + dataversePath + "\"");
+        } else {
+            filterDownToSubtree = Optional.empty();
+        }
```
Comment (madryk) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/SearchIncludeFragment.java:270]: Keeping `Optional<String> filterDownToSubtree` variable is kind of pointless now. Just making:
```
if (!dataverse.isRoot()) {
  dataversePath = dataverseDao.determineDataversePath(dataverse);
  filterQueriesFinal.add(SearchFields.SUBTREE + ":\"" + dataversePath + "\"");
}
```
is a little simpler

**Review by madryk — CHANGES_REQUESTED** [review]

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/SearchIncludeFragment.java (hunk 1 above)
Comment (wtr-icm) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/SearchIncludeFragment.java:270]: Yes, but unfortunately `filterDownToSubtree` is also used later in the code:
```
        if (filterDownToSubtree.isPresent()) {
            this.responseFilterQueries = solrQueryResponse.getFilterQueries().stream()
                    .filter(filter -> !filterDownToSubtree.get().equals(filter.getQuery()))
                    .collect(toList());
        } else {
            this.responseFilterQueries = solrQueryResponse.getFilterQueries();
        }
```
so I think we cannot remove it altogether.

Comment (madryk) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/SearchIncludeFragment.java:270]: Oh, sorry. I didn't notice.

**Review by madryk — APPROVED** [review]
