### PR TITLE
Closes #1540: Fixed featuring dataverse by dataverse linking it

### LINKED ISSUE #1540: Fix error regarding featuring a Dataverse to which a Dataverse is linked
If I link a dataverse A to a dataverse B, it is possible to feature a dataverse B in a dataverse A. It does not make sense, as the linking goes the other way around.

### PR DESCRIPTION
**Pull request by dbojanek**
I hope i understood business logic behind it correctly..
Also fixed a small spelling mistake

### CODE REVIEW

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/FeaturedDataverseServiceBean.java [hunk 1]
```diff
@@ -86,7 +86,6 @@
     public List<Dataverse> findFeaturableDataverses(Long dataverseId) {
         List<Dataverse> featurableDataverses = new ArrayList<>();
         featurableDataverses.addAll(dataverseRepository.findPublishedByOwnerId(dataverseId));
-        featurableDataverses.addAll(linkingService.findLinkingDataverses(dataverseId));
```
Comment (madryk) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/FeaturedDataverseServiceBean.java:89]: I don't think that it is exactly what we want to achieve.
Let's say we have situation:
Dataverse A is linked to Dataverse B (that means that search results of B will include A)
When selecting dataverses that can be featured we want:
For Dataverse A: empty list
For Dataverse B: A
When we will apply these change then:
For Dataverse A: empty
For Dataverse B: empty
Maybe `linkingService.findLinkedDataverses` is what we want instead of `linkingService.findLinkingDataverses`?

Comment (madryk) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/FeaturedDataverseServiceBean.java:89]: I know - it's confusing

**Review by madryk — CHANGES_REQUESTED** [review]

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/FeaturedDataverseServiceBean.java (hunk 1 above)
Comment (dbojanek) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/FeaturedDataverseServiceBean.java:89]: Are you sure if that's what we want? Prior to this change we would have empty list for Dataverse A in your scenario. 
Just asking if we are not overdoing this.

**Review by madryk — APPROVED** [review]
