### PR TITLE
Closes #1787: Fix disappearing files

### LINKED ISSUE #1787: On upload, when I cancel the last uploading file, the message informing about drag and drop disappears
Thus, a user may not know where s/he should drag and drop files on her/his second attempt. 

Moreover, files already uploaded in this batch disappear – a user may unwillingly lose a lot of time.

### PR DESCRIPTION
**Pull request by wtr-icm**

### CODE REVIEW

File: dataverse-webapp/src/main/webapp/resources/js/fileupload.js [hunk 1]
```diff
@@ -39,8 +39,9 @@ function uploadStarted() {
 	observer.observe(files[0].parentElement,config);
 }
 
-function uploadFinished(fileupload) {
-    if (fileupload.files.length === 0) {
+function uploadFinished() {
+    var files = $('.ui-fileupload-files .ui-fileupload-row');
+    if (files.length === 1) {
```
Comment (dbojanek) [inline dataverse-webapp/src/main/webapp/resources/js/fileupload.js:44]: Shouldn't this be zero-length on removing last file?

**Review by dbojanek — APPROVED** [review]

File: dataverse-webapp/src/main/webapp/resources/js/fileupload.js (hunk 1 above)
Comment (wtr-icm) [reply dataverse-webapp/src/main/webapp/resources/js/fileupload.js:44]: In fact we have one additional element on that list, so it's never empty.
