### PR TITLE
Closes #129: Fix app settings + refactor

### LINKED ISSUE #129: Correct application settings
After last changes we have not correctly working application properties retrieval.
Most of them are related to retrieval empty string (in previous version it was null) when setting is not defined

### PR DESCRIPTION
**Pull request by madryk**

### CODE REVIEW

File: src/main/java/edu/harvard/iq/dataverse/settings/SettingsServiceBean.java [hunk 1]
```diff
@@ -486,9 +484,22 @@ public Long getValueForKeyAsLong(Key key){
...
             return null;
         }
-        
+
+    }
+    
+    public Integer getValueForKeyAsInt(Key key){
+        Long value = getValueForKeyAsLong(key);
+        if (value == null) {
+            return null;
```
Comment (MrK191) [inline src/main/java/edu/harvard/iq/dataverse/settings/SettingsServiceBean.java:493]: I understand that it's necessary to return null otherwise we would need big refactor? Otherwise I would return Optional or default value.

Comment (madryk) [reply src/main/java/edu/harvard/iq/dataverse/settings/SettingsServiceBean.java:493]: The problem with default value is picking the right one default value :)
If we for example choose 0 then we would have broke for example setting: SearchHighlightFragmentSize - currently null means do not override default solr setting but 0 is also correct value that means set solr param to 0 (functionality disabled)
It is not that it would be big refactor. But rather it will require to carefully pick the right one value.
Optional will require more changes in code.

Comment (MrK191) [reply src/main/java/edu/harvard/iq/dataverse/settings/SettingsServiceBean.java:493]: Yeah Optional seems more reasonable, but let's just leave it for refactoring tasks.

**Review by MrK191 — APPROVED** [review]
