### PR TITLE
Closes #2333: CSV Ingest Heuristics

### LINKED ISSUE #2333: Add some heuristics to CSV ingest
If standard ingest fails or if it succeeds with a single column containing semicolons, try to assume that a semicolon is a separator and try to ingest file again. 

If the second ingest succeeds – we take its results. 

If it does not, we take what the first ingest gives us (so a fail or a single column).

### PR DESCRIPTION
**Pull request by wtr-icm**

### CODE REVIEW

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/IngestServiceBean.java [hunk 1]
```diff
@@ -514,7 +515,7 @@ public boolean ingestAsTabular(Long datafile_id) {
 
         TabularDataIngest tabDataIngest;
         try (BufferedInputStream inputStream = new BufferedInputStream(new FileInputStream(localFile.get()))) {
-            tabDataIngest = ingestPlugin.read(inputStream, additionalData);
+            tabDataIngest = ingestPlugin.read(Tuple.of(inputStream, localFile.get()), additionalData);
```
Comment (madryk) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/IngestServiceBean.java:518]: IMO it would be cleaner if we would use only File in ingest plugin interface

**Review by madryk — CHANGES_REQUESTED** [review]

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/IngestServiceBean.java (hunk 1 above)
Comment (madryk) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/IngestServiceBean.java:518]: After discussion we have decided that we will leave it as is

**Review by madryk — APPROVED** [review]

**Review by madryk — APPROVED** [review]
