### PR TITLE
Closes #1842: Harvesting datasets no longer fail on parsing dataset fields

### LINKED ISSUE #1842: Prevent harvest fail caused by datasetfieldtypes mismatch

### PR DESCRIPTION
**Pull request by dbojanek**

### CODE REVIEW

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/imports/HarvestedJsonParser.java [hunk 1]
```diff
@@ -252,43 +194,49 @@ private Date parseTime(String str) throws ParseException {
...
         if (type.isCompound()) {
-            parsedFields.addAll(parseCompoundValue(type, json, testType));
+            parsedFields.addAll(parseCompoundValue(type, json));
         } else if (type.isControlledVocabulary()) {
             List<ControlledVocabularyValue> vals = parseControlledVocabularyValue(type, json);
-            for (ControlledVocabularyValue cvv : vals) {
-                cvv.setDatasetFieldType(type);
+            if (vals.size() > 0) {
+                for (ControlledVocabularyValue cvv : vals) {
+                    cvv.setDatasetFieldType(type);
```
Comment (madryk) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/imports/HarvestedJsonParser.java]: This is wrong. We shouldn't manipulate `ControlledVocabularyValue` entity in any way.

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/imports/HarvestedJsonParser.java [hunk 2]
```diff
@@ -252,43 +194,49 @@ private Date parseTime(String str) throws ParseException {
...
-
         } else {
             // primitive
             List<DatasetField> values = parsePrimitiveValue(type, json);
 
             if (values.size() == 1) {
                 datasetField.setFieldValue(values.get(0).getValue());
                 parsedFields.add(datasetField);
-            } else {
+            } else if (values.size() > 1) {
```
Comment (madryk) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/imports/HarvestedJsonParser.java]: The whole reason why you had to introduce some if's here, is because dataset field was created in the code above. When we skip that then the part in if and else is obsolete

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/imports/HarvestedJsonParser.java [hunk 3]
```diff
@@ -330,100 +280,133 @@ private Date parseTime(String str) throws ParseException {
...
+            for (String fieldName : obj.keySet()) {
+                JsonObject childFieldJson = obj.getJsonObject(fieldName);
+                List<DatasetField> childFields = parseField(childFieldJson);
+                if (childFields.isEmpty()) {
+                    continue;
                 }
+
+                DatasetField childField = childFields.get(0);
                 if (childField != null) {
+                    if (!compoundType.getChildDatasetFieldTypes().contains(childField.getDatasetFieldType())) {
```
Comment (madryk) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/imports/HarvestedJsonParser.java]: childField == null could only happen if we would add nulls to an list which is not the our case

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/imports/HarvestedJsonParser.java [hunk 4]
```diff
@@ -330,100 +280,133 @@ private Date parseTime(String str) throws ParseException {
...
 
-                for (String fieldName : obj.keySet()) {
-                    JsonObject childFieldJson = obj.getJsonObject(fieldName);
-                    DatasetField childField = null;
-                    try {
-                        childField = parseField(childFieldJson, testType).get(0);
-                    } catch (ControlledVocabularyException ex) {
-                        vocabExceptions.add(ex);
-                    }
+    private DatasetField parseCompoundSingleValueField(DatasetFieldType compoundType, JsonObject json)
```
Comment (madryk) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/imports/HarvestedJsonParser.java]: I can't see handling of situation when child field is not a part of available children defined by the parent. Like we did in multivalue counterpart

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/imports/HarvestedJsonParser.java [hunk 5]
```diff
@@ -330,100 +280,133 @@ private Date parseTime(String str) throws ParseException {
...
-            }
 
-            JsonArray value = json.getJsonArray("value");
-            System.out.println(value);
+        try {
+            if (compoundType.isAllowMultiples()) {
+                try {
+                    vals.addAll(parseCompoundMultiValueField(compoundType, json));
+                } catch (ClassCastException | NullPointerException exception) {
+                    vals.add(parseCompoundSingleValueField(compoundType, json));
```
Comment (madryk) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/imports/HarvestedJsonParser.java]: IMO instead of consecutive catching of `ClassCastException` and `NullPointerException` we should remove the cause why this situation happens and act accordingly. When we catch everywhere this kind of exceptions we kind of losing control on what are considering "normal" situation and what is not "normal" situation. We are basically telling: well if this method fails then maybe the other will not - it feels more like guessing than an actual coding. Catching NPE is especially dangerous because it can easily hide some defect's in the code that will be hard to track

File: dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/api/imports/HarvestedJsonParserTest.java [hunk 6]
```diff
@@ -1,359 +0,0 @@
...
-import java.util.stream.Collectors;
-
-import static org.junit.jupiter.api.Assertions.*;
-import static org.mockito.ArgumentMatchers.any;
-import static org.mockito.ArgumentMatchers.anyBoolean;
-import static org.mockito.ArgumentMatchers.anyString;
-
-@ExtendWith(MockitoExtension.class)
-@MockitoSettings(strictness = Strictness.LENIENT)
-public class HarvestedJsonParserTest {
```
Comment (madryk) [inline dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/api/imports/HarvestedJsonParserTest.java:31]: I'm kind of suprised that we are removing this unit test in favour of IT. As it would be the easiest solution to test some uncommon scenarios when parsing dataset fields (we are not bounded to the current db state - where it could be a little harder to find fields that have desired multiplicity/whether is compound or not/or is it have vocabulary or not). Not an issue - but it seems that we are pointing to direction that will be harder to test.

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/imports/HarvestedJsonParser.java [hunk 7]
```diff
@@ -330,100 +280,133 @@ private Date parseTime(String str) throws ParseException {
...
+        return vals;
+    }
+
+    private List<DatasetField> parsePrimitiveMultiValues(DatasetFieldType dft, JsonObject json)
+            throws ClassCastException, NullPointerException {
+        List<DatasetField> vals = new LinkedList<>();
+        for (JsonString val : json.getJsonArray("value").getValuesAs(JsonString.class)) {
             DatasetField datasetFieldValue = new DatasetField();
-            datasetFieldValue.setFieldValue(json.getString("value", "").trim());
+            datasetFieldValue.setDisplayOrder(vals.size() - 1);
```
Comment (madryk) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/imports/HarvestedJsonParser.java]: I think that `displayOrder` will be filled either way in further processing and it doesn't really matters but in current solution we will be starting from index `-1`

**Review by madryk — CHANGES_REQUESTED** [review]

File: dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/api/imports/HarvestedJsonParserTest.java (hunk 6 above)
Comment (dbojanek) [reply dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/api/imports/HarvestedJsonParserTest.java:31]: This is something what I've mentioned on a daily meeting. These unit tests were testing just `parseVocabulary` fields, so the method was left `public` just to be able to test it like that. 
Leaving it `private` and unit testing its parts (like `parseVocabulary`) by mocking whole Dataset is IMO not readable. 
I'm leaving it to your suggestion - leave the method `public` and keep unit tests or mock whole Dataset keep it private?

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/imports/HarvestedJsonParser.java (hunk 5 above)
Comment (dbojanek) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/imports/HarvestedJsonParser.java]: TBH I don't really know how to accomplish that.. 
Can you enlighten me how should I properly check if a given value is an array or a string?

Comment (madryk) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/imports/HarvestedJsonParser.java]: This is something that we already had in original code in one place:
`if (dft.isAllowMultiples() && json.get("value").getValueType().equals(JsonValue.ValueType.ARRAY))`
So: `JsonValue` have a method `.getValueType()`

File: dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/api/imports/HarvestedJsonParserTest.java (hunk 6 above)
Comment (madryk) [reply dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/api/imports/HarvestedJsonParserTest.java:31]: Ok. Let's leave IT way.

**Review by madryk — APPROVED** [review]
