### PR TITLE
Closes #1815: changed ingest error message, fixed ingest error message is always unknown.

### LINKED ISSUE #1815: Fix PL version of information that unknown error occurred during ingest
Is: 

Analiza danych tabelarycznych nie powiodła się. Wystąpił nieznany błąd wystąpił podczas analizy pliku.

Should be: 

Analiza danych tabelarycznych nie powiodła się. W trakcie analizy pliku wystąpił nieznany błąd.

### PR DESCRIPTION
**Pull request by MrK191**

### CODE REVIEW

File: dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/datafile/ingest/IngestReport.java [hunk 1]
```diff
@@ -141,10 +141,13 @@ public void setEndTime(Date endTime) {
...
-                .orElse(IngestError.UNKNOWN_ERROR)
-                .getErrorMessage(Optional.ofNullable(errorArguments).
-                        orElseGet(Collections::emptyList));
+        final IngestError errorKey = Optional.ofNullable(this.errorKey)
+                                             .orElse(IngestError.UNKNOWN_ERROR);
+
+        return Optional.of(errorArguments)
+                       .filter(args -> !args.isEmpty())
+                       .map(errorKey::getErrorMessage)
+                       .orElseGet(errorKey::getErrorMessage);
```
Comment (madryk) [inline dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/datafile/ingest/IngestReport.java]: IMO there is a problem in `IngestError.getErrorMessage(...)`. We shouldn't have to pick here, which version of `getErrorMessage` method to use. 
Maybe I am missing something, but in
```
    public String getErrorMessage(List<String> arguments) {
        return arguments.isEmpty() ? getDefaultErrorMessage() : BundleUtil.getStringFromBundle(ERROR_KEY_PREFIX + toString(), arguments.toArray());
    }
```
checking `arguments` param seems pointless and causes more confusion.
Moreover it forces that every non unknown ingest error must have some kind of arguments.

**Review by madryk — CHANGES_REQUESTED** [review]

File: dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/datafile/ingest/IngestError.java [hunk 2]
```diff
@@ -39,18 +39,14 @@
 
     // -------------------- LOGIC --------------------
 
-    public String getErrorMessage() {
-        return BundleUtil.getStringFromBundle(ERROR_KEY_PREFIX + toString());
-    }
-
     public String getErrorMessage(List<String> arguments) {
-        return arguments.isEmpty() ? getDefaultErrorMessage() : BundleUtil.getStringFromBundle(ERROR_KEY_PREFIX + toString(), arguments.toArray());
+        return arguments.isEmpty() ? getErrorMessage() : BundleUtil.getStringFromBundle(ERROR_KEY_PREFIX + toString(), arguments.toArray());
```
Comment (madryk) [inline dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/datafile/ingest/IngestError.java]: I don't think that there is any difference between:
`BundleUtil.getStringFromBundle(ERROR_KEY_PREFIX + toString(), arguments.toArray())` == `BundleUtil.getStringFromBundle(ERROR_KEY_PREFIX + toString())`

**Review by madryk — CHANGES_REQUESTED** [review]

File: dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/datafile/ingest/IngestError.java (hunk 2 above)
Comment (MrK191) [reply dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/datafile/ingest/IngestError.java]: Oh you mean if it's empty? I need to check it then.

**Review by madryk — APPROVED** [review]
