### PR TITLE
Closes #202: Fix translations when using dataverse.lang.directory, custom metadata blocks and metadata validation messages

### LINKED ISSUE #202: Fix translation problems with roles on manage permissions page and metadata values on dataset view/add page

### PR DESCRIPTION
**Pull request by madryk**

### CODE REVIEW

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/DatasetFieldValueValidator.java [hunk 1]
```diff
@@ -47,24 +51,28 @@ public boolean isValid(DatasetFieldValue value, ConstraintValidatorContext conte
                 && value.getDatasetField().getParentDatasetFieldCompoundValue().getParentDatasetField().getTemplate() != null) {
             lengthOnly = true;
         }
+        
+        if (lengthOnly) {
+            return true;
```
Comment (dbojanek) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/DatasetFieldValueValidator.java:50]: Why don't we do 'return true' instead of lengthOnly = true and then checking if(lengthOnly) ?
Looks like we don't need that variable anymore.

**Review by dbojanek — CHANGES_REQUESTED** [review]

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/DatasetFieldValueValidator.java (hunk 1 above)
Comment (madryk) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/DatasetFieldValueValidator.java:50]: Ok. You're right.

**Review by dbojanek — APPROVED** [review]
