### PR TITLE
Closes #2188: Fix rejecting dataset publication

### LINKED ISSUE #2188: Editing a dataset in multiple tabs causes errors when rejecting
```
Caused by: javax.persistence.OptimisticLockException: Exception [EclipseLink-5010] (Eclipse Persistence Services - 2.6.1.v20150605-31e8258): org.eclipse.persistence.exceptions.$
Exception Description: The object [[DatasetVersion id:723]] cannot be merged because it has changed or been deleted since it was last read.
Class> edu.harvard.iq.dataverse.persistence.dataset.DatasetVersion
        at org.eclipse.persistence.internal.jpa.EntityManagerImpl.mergeInternal(EntityManagerImpl.java:555)
        at org.eclipse.persistence.internal.jpa.EntityManagerImpl.merge(EntityManagerImpl.java:530)
        at com.sun.enterprise.container.common.impl.EntityManagerWrapper.merge(EntityManagerWrapper.java:305)
        at edu.harvard.iq.dataverse.engine.command.impl.ReturnDatasetToAuthorCommand.execute(ReturnDatasetToAuthorCommand.java:48)
        at edu.harvard.iq.dataverse.engine.command.impl.ReturnDatasetToAuthorCommand.execute(ReturnDatasetToAuthorCommand.java:20)
```

### PR DESCRIPTION
**Pull request by wtr-icm**
I've changed the moment when we send a command to unlock the dataset. I haven't noticed any strange behavior – returning dataset seems to work properly, also in the scenario with OptimisticLockException.

### CODE REVIEW

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/engine/command/impl/ReturnDatasetToAuthorCommand.java [hunk 1]
```diff
@@ -43,13 +43,13 @@ public Dataset execute(CommandContext ctxt)  {
...
         dataset.setModificationTime(getTimestamp());
 
-        ctxt.engine().submit(new RemoveLockCommand(getRequest(), getDataset(), DatasetLock.Reason.InReview));
         WorkflowComment workflowComment = new WorkflowComment(dataset.getEditVersion(), WorkflowComment.Type.RETURN_TO_AUTHOR, comment, (AuthenticatedUser) this.getUser());
         ctxt.datasets().addWorkflowComment(workflowComment);
 
         updateDatasetUser(ctxt);
         ctxt.em().flush();
         Dataset savedDataset = ctxt.em().merge(dataset);
+        ctxt.engine().submit(new RemoveLockCommand(getRequest(), getDataset(), DatasetLock.Reason.InReview));
```
Comment (madryk) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/engine/command/impl/ReturnDatasetToAuthorCommand.java]: Definitely it is a step in the right direction. What I would also try to do is apply a flush after the merge of dataset instead of before.
```
        ctxt.em().flush();
        Dataset savedDataset = ctxt.em().merge(dataset);
```
->
```
        Dataset savedDataset = ctxt.em().merge(dataset);
        ctxt.em().flush();
```
That way we will be more sure that everything is fine before execution of `RemoveLockCommand`

There still can be a chance of making `inconsistent` state of application when sendNotification or indexDataset will throw an exception (the whole transaction will be rolled back, but lock will turned off). But I think it is debatable whether we should worry about that.

**Review by madryk — CHANGES_REQUESTED** [review]

**Review by madryk — APPROVED** [review]
