### PR TITLE
Closes #1448: Fix not closing streams in s3

### LINKED ISSUE #1448: When trying to download files on RDS, 404 is thrown

### PR DESCRIPTION
**Pull request by madryk**

### CODE REVIEW

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/MapLayerMetadataServiceBean.java [hunk 1]
```diff
@@ -270,12 +267,6 @@ public boolean retrieveMapImageForIcon(MapLayerMetadata mapLayerMetadata) throws
             is = url.openStream();
```
Comment (wtr-icm) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/MapLayerMetadataServiceBean.java]: I'm not convinced that this stream will be closed when an `IOException` is thrown later from one of `saveInputStreamAsAux` implementations – maybe better to put this into try-with-resources clause.

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/DownloadInstanceWriter.java [hunk 2]
```diff
@@ -301,51 +301,53 @@ private void writeGuestbookResponse(DownloadInstance di) {
...
-        while ((bufsize = instream.read(bffr)) != -1) {
-            outstream.write(bffr, 0, bufsize);
-        }
+            while ((bufsize = instream.read(bffr)) != -1) {
+                outstream.write(bffr, 0, bufsize);
+            }
 
-        instream.close();
+        }
         outstream.close();
```
Comment (wtr-icm) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/DownloadInstanceWriter.java]: maybe inside `finally`?

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/dataaccess/DataConverter.java [hunk 3]
```diff
@@ -228,14 +179,19 @@ private File runFormatConversion(DataFile file, File tabFile, String formatReque
...
                     StorageIO<DataFile> storageIO = DataAccess.dataAccess().getStorageIO(file);
-                    long size = storageIO.getAuxObjectSize("orig");
-                    File origFile = downloadFromByteChannel((ReadableByteChannel) storageIO.openAuxChannel("orig"), size);
+                    File origFile = StorageIOUtils.obtainAuxAsLocalFile(storageIO, StorageIOConstants.SAVED_ORIGINAL_FILENAME_EXTENSION, storageIO.isRemoteFile());
+                    
+                    tmpOrigFile = storageIO.isRemoteFile() ? Optional.of(origFile) : Optional.empty();
+                    
                     resultInfo = dfs.directConvert(origFile, origFormat);
                 } catch (IOException ex) {
                     ex.printStackTrace();
```
Comment (wtr-icm) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/dataaccess/DataConverter.java]: We could get rid of that line and log the exception properly.

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/dataaccess/StoredOriginalFile.java [hunk 4]
```diff
@@ -33,66 +32,59 @@
...
+        if (mimeType.matches("application/x-dvn-.*-zip")) {
+            mimeType = "application/zip";
+        }
+        return mimeType;
+    }
 
+    private static String generateFileName(String storageFilename, String originalMimeType) {
+        if (originalMimeType != null) {
+            String origFileExtension = generateOriginalExtension(originalMimeType);
+            return storageFilename.replaceAll(".tab$", origFileExtension);
```
Comment (wtr-icm) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/dataaccess/StoredOriginalFile.java]: Dot in this regex will match any single character.

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/dataset/DatasetThumbnailService.java [hunk 5]
```diff
@@ -373,7 +328,7 @@ public boolean isDatasetLogoPresent(Dataset dataset) {
 
         try {
             storageIO = dataAccess.getStorageIO(dataset);
-            return storageIO.isAuxObjectCached(datasetLogoThumbnail + thumb48addedByImageThumbConverter);
+            return storageIO.isAuxObjectCached(datasetLogoThumbnail48);
         } catch (IOException ioex) {
         }
```
Comment (wtr-icm) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/dataset/DatasetThumbnailService.java]: Empty catch – we should log something at least.

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/IngestServiceBean.java [hunk 6]
```diff
@@ -825,6 +813,8 @@ public boolean ingestAsTabular(Long datafile_id) {
 
             logger.log(Level.WARNING, "Ingest failure.", ingestEx);
             return false;
+        } finally {
+            IOUtils.closeQuietly(inputStream);
```
Comment (wtr-icm) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/IngestServiceBean.java]: Couldn't we put that stream into try-with-resources?

**Review by wtr-icm — CHANGES_REQUESTED** [review]

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/IngestServiceBean.java (hunk 6 above)
Comment (madryk) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/IngestServiceBean.java]: There will be subtle difference in execution: If close will fail then in original code it won't cause the whole ingest to fail but it will be quietly ignored. If we make this with try-with-resources then fail when closing will cause whole ingest to fail. Although I think that your proposition is good. At least we would discover more quickly that we have some issues with closing streams.

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/DownloadInstanceWriter.java (hunk 2 above)
Comment (madryk) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/DownloadInstanceWriter.java]: Ok. But to be honest I don't think that closing this stream should be our responsibility (we didn't open this stream) at all.

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/MapLayerMetadataServiceBean.java (hunk 1 above)
Comment (madryk) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/MapLayerMetadataServiceBean.java]: Well. It won't be closed. I didn't focused on streams that was not s3 related. But we probably should close this stream

**Review by wtr-icm — APPROVED** [review]
