### PR TITLE
Closes #1677: Fix whole dataset downloading

### LINKED ISSUE #1677: Dataset files cannot be download sometimes
It seems that only dataset with tabular files can be downloaded when there is selection : orginal format and archival format

### PR DESCRIPTION
**Pull request by madryk**

### CODE REVIEW

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/datafile/file/FileDownloadAPIHandler.java [hunk 1]
```diff
@@ -264,158 +237,78 @@ private boolean isAccessAuthorized(DatasetVersion dsv, String apiToken) {
...
         return false;
     }
 
+    private User getApiTokenUserWithGuestFallbackOnInvalidToken() {
+        return Try.of(this::findUserOrDie)
+                .onFailure(throwable -> logger.log(Level.FINE, "Failed finding user with apiToken", throwable))
+                .getOrElse(GuestUser.get());
+    }
+
+    private User getSessionUserWithGuestFallback() {
```
Comment (dbojanek) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/datafile/file/FileDownloadAPIHandler.java:298]: Since method above uses functional-like style maybe consider it here as well with `Optional.ofNullable` or something from vavr?

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/engine/command/DataverseRequest.java [hunk 2]
```diff
@@ -69,4 +72,34 @@ public AuthenticatedUser getAuthenticatedUser() {
...
+    public boolean equals(Object obj) {
+        if (this == obj) {
+            return true;
+        }
+        if (obj == null) {
+            return false;
+        }
+        if (getClass() != obj.getClass()) {
+            return false;
+        }
```
Comment (dbojanek) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/engine/command/DataverseRequest.java]: Can be wrapped to `obj == null ||  getClass() != obj.getClass()`.

File: dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/api/AccessTest.java [hunk 3]
```diff
@@ -0,0 +1,194 @@
...
+import org.mockito.junit.jupiter.MockitoExtension;
+
+import javax.servlet.http.HttpServletRequest;
+
+import static org.assertj.core.api.Assertions.assertThat;
+import static org.junit.jupiter.api.Assertions.*;
+import static org.mockito.Mockito.*;
+
+@ExtendWith(MockitoExtension.class)
+public class AccessTest {
```
Comment (dbojanek) [inline dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/api/AccessTest.java:37]: Add a test case for `when(embargoAccessService.isRestrictedByEmbargo(dataset)).thenReturn(true);` ? To check if this logic is being taken care of as well?

**Review by dbojanek — CHANGES_REQUESTED** [review]
Why are we removing `key` from query params?

**Comment by madryk** [comment]
> Why are we removing `key` from query params?

Method `findUserOrDie` from AbstractApiBean is aware of this query param, so we don't need it in
method definition. With this removal we can additionally remove code like:
```
if (apiToken == null || apiToken.equals("")) {
  apiToken = headers.getHeaderString(API_KEY_HEADER);
}
```
`findUserOrDie` is also taking this into account

**Review by dbojanek — APPROVED** [review]
