### PR TITLE
Closes #1673: Fixed sources for file and dataset names in report

### LINKED ISSUE #1673: Name of dataset and of file should be per version in report
V1 dataset name = DS1
V2 dataset name = DS2

on report there is
V1  DS2
V2  DS2

same issue on file name

### PR DESCRIPTION
**Pull request by dbojanek**

### CODE REVIEW

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/dataset/DatasetReportService.java [hunk 1]
```diff
@@ -109,11 +108,19 @@ private Record createDatasetRecord(Dataset dataset) {
...
+
         for (FileMetadata fileMetadata : allFilesMetadataSorted) {
+            datasetVersionRecord.setFileName(fileMetadata.getLabel());
             processFile(fileMetadata, csvPrinter, datasetVersionRecord);
         }
     }
 
+    private String getDatasetTitleInVersion(DatasetVersion datasetVersion) {
+        return datasetVersion.getDatasetFieldByTypeName(DatasetFieldConstant.title).isPresent() ?
+            datasetVersion.getDatasetFieldByTypeName(DatasetFieldConstant.title).get().getValue() : datasetVersion.getDataset().getDisplayName();
```
Comment (MrK191) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/dataset/DatasetReportService.java]: Hmm aren't those two methods almost the same? That's the code for displayname -> getTitle 
```
or (DatasetField dsfv : this.getDatasetFields()) {
            if (dsfv.getDatasetFieldType().getName().equals(DatasetFieldConstant.title)) {
                retVal = dsfv.getDisplayValue();
            }
        }
```
I think I would just use datasetVersion.getDataset().getDisplayName() for simplicity.

**Review by MrK191 — CHANGES_REQUESTED** [review]

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/dataset/DatasetReportService.java (hunk 1 above)
Comment (dbojanek) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/dataset/DatasetReportService.java]: I'd rather avoid using `displayValue` methods in report if I can help it. They depend on field display format which is part of metadata. It's usually not a problem when a given field has format like `#VALUE` but if it changes the problem occurs - as I have lately raised this issue when we have changed display format for external Ids identifiers and exporters started to print data incorrectly..

Here I only fallback for `displayValue` and I can switch `datasetVersion.getDataset().getDisplayName();` to `datasetVersion.getTitle()`

Comment (MrK191) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/dataset/DatasetReportService.java]: Ahh ok then.

**Review by MrK191 — APPROVED** [review]
