### PR TITLE
Closes #2846 Periodo metadata field should allow for multiple selections

### LINKED ISSUE #2846: Periodo metadata field should allow for multiple selections
Now that we know that the Ariadne documentation is wrong and it is possible to have multiple periods per record, we can allow for selection of multiple periods from Periodo.

### PR DESCRIPTION
**Pull request by lbownik**

### CODE REVIEW

**Review by rscipien — APPROVED** [review]

File: fairchive-webapp/src/main/java/edu/harvard/iq/dataverse/search/SearchFields.java [hunk 1]
```diff
@@ -263,10 +263,10 @@ public class SearchFields {
     /**
      * Fields from perio.do distionary
      */
-    public static final String PERIODO_ID = "periodo_id_s";
+    public static final String PERIODO_ID = "periodo_id_ss";
     public static final String PERIODO_LABEL = "periodo_label_txt";
-    public static final String PERIODO_START = "periodo_start_l";
-    public static final String PERIODO_STOP = "periodo_stop_l";
+    public static final String PERIODO_START = "periodo_start_ls";
+    public static final String PERIODO_STOP = "periodo_stop_ls";
```
Comment (diasf) [inline fairchive-webapp/src/main/java/edu/harvard/iq/dataverse/search/SearchFields.java:269]: What's the purpose of those suffixes?

**Review by diasf — COMMENTED** [review]
> Periodo metadata field should allow for multiple selections

What was the actual task here? The effective change might be subtle, but I didn't see it.

**Comment by lbownik** [comment]
> > Periodo metadata field should allow for multiple selections
> 
> What was the actual task here? The effective change might be subtle, but I didn't see it.

The goal of this PR is to allow Datasets have multiple fields of Periodo type with various values.

File: fairchive-webapp/src/main/java/edu/harvard/iq/dataverse/search/SearchFields.java (hunk 1 above)
Comment (lbownik) [reply fairchive-webapp/src/main/java/edu/harvard/iq/dataverse/search/SearchFields.java:269]: these suffeixes are to allow indexed dataserts to have multiple fields of the Periodo type ( suffix "_l" means a "single dynamic field of long type", suffinx "_ls" means "potentially multiple dynamic fields of long type". Dynamic fields do not need to be specified in schema.xml.

Comment (diasf) [reply fairchive-webapp/src/main/java/edu/harvard/iq/dataverse/search/SearchFields.java:269]: Thanks for clarifying, I forgot about those dynamic fields.

**Review by diasf — APPROVED** [review]
