### PR TITLE
Closes #1131: Displaying embargoed dataset files table fix

### LINKED ISSUE #1131: Fix layout of "Files" tab for an embargoed dataset
Whole area marked in red should not be shown: 

image

### PR DESCRIPTION
**Pull request by dbojanek**

### CODE REVIEW

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/dataset/tab/DatasetFilesTab.java [hunk 1]
```diff
@@ -232,6 +234,10 @@ public void init(DatasetVersion workingVersion) {
         guestbookResponseDialog.initForDatasetVersion(workingVersion);
     }
 
+    public boolean isFilesTabDisplayable() {
+        return !embargoAccess.isRestrictedByEmbargo(dataset) && (!workingVersion.getFileMetadatas().isEmpty() || !fileMetadatasSearch.isEmpty() || !dataset.hasEverBeenPublished());
```
Comment (madryk) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/dataset/tab/DatasetFilesTab.java]: I don't think that condition after `&&` have any effect. Probably it would be the same if it would not be present

File: dataverse-webapp/src/main/webapp/filesFragment.xhtml [hunk 2]
```diff
@@ -31,7 +31,7 @@
         </div>
     </ui:fragment>
 
-    <ui:fragment rendered="#{!empty datasetFilesTab.workingVersion.fileMetadatas or !empty datasetFilesTab.fileMetadatasSearch or not datasetFilesTab.dataset.hasEverBeenPublished()}">
+    <ui:fragment rendered="#{datasetFilesTab.isFilesTabDisplayable()}">
```
Comment (madryk) [inline dataverse-webapp/src/main/webapp/filesFragment.xhtml:35]: When user with assigned good enough permissions (for example superadmin) will search in files something that will not return any results and dataset is under embargo then it will be rendered as:
Zrzut ekranu z 2020-07-07 10-28-45
I think that it would be more secure to add
`<ui:fragment rendered="#{!datasetFilesTab.isFilesTabDisplayable()}">` in fragment one above this (line 15).

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/dataset/tab/DatasetFilesTab.java [hunk 3]
```diff
@@ -8,6 +8,7 @@
 import edu.harvard.iq.dataverse.EjbDataverseEngine;
 import edu.harvard.iq.dataverse.PermissionServiceBean;
 import edu.harvard.iq.dataverse.PermissionsWrapper;
+import edu.harvard.iq.dataverse.api.EmbargoAccessService;
```
Comment (madryk) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/dataset/tab/DatasetFilesTab.java]: If we want to use `EmbargoAccessService` it shouldn't be in `api` package and it shouldn't extend from `AbstractApiBean`

**Review by madryk — CHANGES_REQUESTED** [review]

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/dataset/tab/DatasetFilesTab.java (hunk 1 above)
Comment (dbojanek) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/dataset/tab/DatasetFilesTab.java]: I didn't want to interfere with present logic, but You're probably right.

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/EmbargoAccessService.java [hunk 4]
```diff
@@ -1,17 +1,13 @@
-package edu.harvard.iq.dataverse.api;
+package edu.harvard.iq.dataverse;
```
Comment (madryk) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/EmbargoAccessService.java]: I guess that `edu.harvard.iq.dataverse.dataset` would be better since embargo is assigned on datasets

**Review by madryk — CHANGES_REQUESTED** [review]

**Review by madryk — APPROVED** [review]
