### PR TITLE
Closes #2508: Fix webapp integration tests

### LINKED ISSUE #2508: Fix integration tests

### PR DESCRIPTION
**Pull request by diasf**
Integration tests weren't getting executed, there were a couple of different issues mainly due to testcontainers library dependencies:

* Due to junit version conflict maven is not executing any integration tests. Not sure for how long it's already the case but never noticed it because I ran IT tests manually through the IDE when necessary.
* The testcontainers library includes in its JAR newer classes of jackson api which conflict with the ones provided by glassfish. This causes some tests which make use of jackson library (directly or indirectly) to fail.
* Some integration tests are not not up-to-date anymore with test data

To address above issues, I've removed testcontainers library and replaced it with `docker-maven-plugin` to start postgres and solr and the beginning of integration tests. They will be build, started and stopped automatically during normal maven builds (eg `verify` or `install`).

To build and start the containers in order to run individual tests within the IDE:

```
$ ./mvnw docker:build docker:start -pl dataverse-webapp
```

Containers need to be build only once after changing container configuration, afterwards `docker:start` will be enough. And to stop them:

```
$ ./mvnw docker:stop -pl dataverse-webapp
```

Note:
Further improvement to make integration tests faster could be to check out https://github.com/ingwarsw/arquillian-suite-extension which would allow to not need to fork a jvm for each test.

### CODE REVIEW

File: dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/search/TestSolrClientFactory.java [hunk 1]
```diff
@@ -26,31 +22,13 @@
...
-        SOLR_CONTAINER.start();
-    }
-    
     // -------------------- LOGIC --------------------
     
     @Produces
     @Specializes
     public SolrClient produceSolrClient() throws IOException {
-        String urlString = "http://localhost:" + SOLR_CONTAINER.getMappedPort(8983) + "/solr/collection1";
+        String urlString = "http://localhost:8983/solr/collection1";
```
Comment (madryk) [inline dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/search/TestSolrClientFactory.java]: I'm thinking if we should use 8983 port. When someone will run integration tests while it has the application running then there is a possibility that we will break user data that he currently have in solr. Maybe changing the port to let's say `8984` would be safer?

Comment (diasf) [reply dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/search/TestSolrClientFactory.java]: Yeah, good point. I've made it a generated port ( > 30000 ) with a fallback to `8984, should one want to run tests within the IDE and start solr beforehand. One can still use maven config to start the containers, although with a somewhat longer command line in order to specify the port:

```
$ ./mvnw docker:start -Dtest.solr.port=8984 -pl dataverse-webapp
```

I guess one could use maven profiles to make this easier.

**Review by madryk — APPROVED** [review]
