### PR TITLE
 Closes #1535: Fix memory issues on dataverse page 

### LINKED ISSUE #1535: Fix memory issues on dataverse page

### PR DESCRIPTION
**Pull request by madryk**

### CODE REVIEW

File: dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/dataverse/DataverseFeaturedDataverseRepository.java [hunk 1]
```diff
@@ -0,0 +1,25 @@
...
+
+@Stateless
+public class DataverseFeaturedDataverseRepository extends JpaRepository<Long, DataverseFeaturedDataverse> {
+
+    // -------------------- CONSTRUCTORS --------------------
+
+    public DataverseFeaturedDataverseRepository() {
+        super(DataverseFeaturedDataverse.class);
+    }
+
```
Comment (wtr-icm) [inline dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/dataverse/DataverseFeaturedDataverseRepository.java:17]: `// -------------------- LOGIC  --------------------`

File: dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/dataverse/DataverseRepository.java [hunk 2]
```diff
@@ -13,4 +15,10 @@ public DataverseRepository() {
         super(Dataverse.class);
     }
```
Comment (wtr-icm) [inline dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/dataverse/DataverseRepository.java:17]: `// -------------------- LOGIC --------------------`

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/FeaturedDataverseServiceBean.java [hunk 3]
```diff
@@ -6,81 +6,90 @@
...
-        try {
-            //searchResults = em.createNativeQuery("SELECT id, alias, name FROM dataverse WHERE id IN (select featureddataverse_id from DataverseFeaturedDataverse where dataverse_id = "+dataverseId+" order by displayOrder)").getResultList();
-            searchResults = em.createNativeQuery("SELECT d.id, d.alias, d.name FROM dataverse d, DataverseFeaturedDataverse f WHERE f.featureddataverse_id = d.id AND f.dataverse_id = " + dataverseId + " order by f.displayOrder").getResultList();
-        } catch (Exception ex) {
-            return null;
-        }
+        List<Object[]> searchResults = em.createNativeQuery("SELECT d.id, d.alias, d.name, dt.logo FROM DataverseFeaturedDataverse f "
+                + " JOIN dataverse d ON d.id = f.featureddataverse_id"
+                + " LEFT JOIN dataversetheme dt ON dt.dataverse_id = d.id"
+                + " WHERE f.dataverse_id = " + dataverseId + " order by f.displayOrder").getResultList();
```
Comment (wtr-icm) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/FeaturedDataverseServiceBean.java]: Better to set this parameter with a method.

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/dataverse/DataverseLinkingService.java [hunk 4]
```diff
@@ -0,0 +1,97 @@
+/*
+ * To change this license header, choose License Headers in Project Properties.
+ * To change this template file, choose Tools | Templates
+ * and open the template in the editor.
+ */
```
Comment (wtr-icm) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/dataverse/DataverseLinkingService.java]: To remove

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/dataverse/FeaturedDataversesDialog.java [hunk 5]
```diff
@@ -0,0 +1,85 @@
...
+    private Dataverse dataverse;
+
+    
+    public void init(Dataverse dataverse) {
+        canEditFeaturedDataverses = permissionWrapper.canIssueUpdateDataverseCommand(dataverse);
+        
+        if (canEditFeaturedDataverses) {
+            this.dataverse = dataverse;
+        }
+    }
```
Comment (wtr-icm) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/dataverse/FeaturedDataversesDialog.java]: Wrong section, unless we treat that method as a kind of constructor.

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/dataverse/LinkToDataverseDialog.java [hunk 6]
```diff
@@ -0,0 +1,231 @@
...
+    public void init(Dataverse dataverse, String searchQuery, List<String> searchFilterQueriesDebug) {
+        canLinkDataverse = session.getUser().isSuperuser() && !dataverse.isRoot();
+        canLinkSavedSearch = session.getUser().isSuperuser() && StringUtils.isNotEmpty(searchQuery);
+
+        if (canLinkDataverse || canLinkSavedSearch) {
+            this.dataverse = dataverse;
+            this.searchQuery = searchQuery;
+            this.searchFilterQueriesDebug = searchFilterQueriesDebug;
+        }
+    }
```
Comment (wtr-icm) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/dataverse/LinkToDataverseDialog.java]: Wrong section.

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/SearchIncludeFragment.java [hunk 7]
```diff
@@ -351,25 +372,26 @@ public void search() {
...
+                .append("dataverse.xhtml?alias=").append(dataverseAlias)
+                .append("&q=" + ((query == null) ? "" : query))
+                .append("&types=" + selectedTypesMap.entrySet().stream()
+                                    .filter(entry -> entry.getValue())
+                                    .map(entry -> entry.getKey().getSolrValue())
+                                    .collect(Collectors.joining(":")));
         
         for (int i=0; i< filterQueries.size(); i++) {
-            searchUrl += "&fq" + i + "=" + filterQueries.get(i);
+            searchUrlBuilder.append("&fq" + i + "=" + filterQueries.get(i));
```
Comment (wtr-icm) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/SearchIncludeFragment.java]: Better to make a chain of `append`s as `+` creates nested instance of `StringBuilder`.

**Review by wtr-icm — APPROVED** [review]

**Review by wtr-icm — APPROVED** [review]
