### PR TITLE
Closes #644: Empty to Unknown FileType fix

### LINKED ISSUE #644: Fix not displaying type of file for 'Unknown' case

### PR DESCRIPTION
**Pull request by dbojanek**

### CODE REVIEW

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/util/FileUtil.java [hunk 1]
```diff
@@ -165,39 +165,12 @@ public static String replaceExtension(String originalName, String newExtension)
...
-                // "uknown". 
-                // -- L.A. 4.0 alpha 1
-                //
-                // UPDATE, MH 4.9.2
-                // Since production is displaying both "tabulardata" and "Tabular Data"
-                // we are going to try to add capitalization here to this function
-                // in order to capitalize all the unknown types that are not called
-                // out in MimeTypeFacets.properties
-                String typeClass = fileType.split("/")[0];
-                return Character.toUpperCase(typeClass.charAt(0)) + typeClass.substring(1);
```
Comment (MrK191) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/util/FileUtil.java:190]: We don't need this anymore? It looks like they didn't want all friendly-facet missing values to be "Unknown".

**Review by MrK191 — CHANGES_REQUESTED** [review]

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/util/FileUtil.java (hunk 1 above)
Comment (dbojanek) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/util/FileUtil.java:190]: It didn't work this way and nobody noticed but I guess we can make this work 'as intended' :) 
For the "tabular data on production case" I would skip this. If we ever have similar issue I would fix it in some other way.

Comment (MrK191) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/util/FileUtil.java:190]: Well if we didn't need this before we can leave it then, if there is going to be need for new type of behaviour in tag naming, we can implement it then.

**Review by MrK191 — APPROVED** [review]
