### PR TITLE
Closes #2764 Fix search in "Periodization" dropdown

### LINKED ISSUE #2764: Fix search in "Periodization" dropdown
- it should not be case sensitive, 
- it will be much easier to read the content of the dropdown item if we more strongly separate individual pieces of information, for instance we could bold "Name", "Area", "Area (description)", "Start", "End" and "Source", and add ";" to the end of each section. 
- using two words or more from different parts of the dropdown item content often gives empty results, even if the entered phrase is a verbatim repetition of words that can be found in the dropdown, for instance for "Early" i get:

Image

for "Early Minoan" it still works fine:

Image

but then:

Image

and (for words from different areas of the item):

Image

### PR DESCRIPTION
**Pull request by lbownik**

### CODE REVIEW

**Review by rscipien — APPROVED** [review]

File: dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/dataset/PeriodoDictionary.java [hunk 1]
```diff
@@ -136,18 +141,23 @@ private static Collection<String> parseLocations(final JSONArray json) {
...
         return label;
     }
 
     private static Stream<Period> stream(final String query) {
-        final String sanitizedQuery = sanitizeQuery(query);
+        final List<String> sanitizedQuery = parseQuery(query);
         if (sanitizedQuery.isEmpty()) {
             return Stream.empty();
+        } else if (sanitizedQuery.size() == 1) {
+            // choose performance implementation if there is only one word
```
Comment (diasf) [inline dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/dataset/PeriodoDictionary.java]: Have you measured the gains obtained? Streams in Java are pretty good optimized already. Unless there is evidence of it giving significant gains, I would much prefer simplicity.

File: dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/dataset/PeriodoDictionary.java [hunk 2]
```diff
@@ -179,13 +196,27 @@ private Period(final String id, final String label,
...
-                    this.locations.stream().anyMatch(location -> location.contains(query));
+            return containsIgnoreCase(this.id, query) ||
+                    containsIgnoreCase(this.label, query) ||
+                    containsIgnoreCase(this.coverageName, query) ||
+                    containsIgnoreCase(this.authorityTitle, query) ||
+                    this.locations.stream()
+                            .anyMatch(location -> containsIgnoreCase(location, query));
+        }
+
+        private boolean matches(final List<String> query) {
```
Comment (diasf) [inline dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/dataset/PeriodoDictionary.java]: From the issue description it seems like we expect words to match different areas individually, instead of all the query words needing to match an area entirely.

image

File: dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/dataset/PeriodoDictionary.java (hunk 1 above)
Comment (lbownik) [reply dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/dataset/PeriodoDictionary.java:158]: yes - the difference is noticeable - unless the difference I observed was something else

Comment (lbownik) [reply dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/dataset/PeriodoDictionary.java]: fixed

File: dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/dataset/PeriodoDictionary.java (hunk 2 above)
Comment (lbownik) [reply dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/dataset/PeriodoDictionary.java]: fixed

File: dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/dataset/PeriodoDictionary.java [hunk 3]
```diff
@@ -181,11 +196,20 @@ private Period(final String id, final String label,
...
-                    this.locations.stream().anyMatch(location -> location.contains(query));
+            return containsIgnoreCase(this.id, query) ||
+                    containsIgnoreCase(this.label, query) ||
+                    containsIgnoreCase(this.coverageName, query) ||
+                    containsIgnoreCase(this.authorityTitle, query) ||
+                    this.locations.stream()
+                            .anyMatch(location -> containsIgnoreCase(location, query));
+        }
+
+        private boolean matches(final String[] query) {
```
Comment (diasf) [inline dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/dataset/PeriodoDictionary.java:207]: Any particular reason to change it to an array? The version you had before was perfectly fine and would have translated to:

```
return query.stream().allMatch(this:matches);
```

Comment (lbownik) [reply dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/dataset/PeriodoDictionary.java:207]: with List<String> a for loop creates a new iterator. since this methods is involeks for every period in dictionary there are abut 9000 itaretor objects created during every search.

for String[] for loop does not create a new iterator so less garbage gets created

Comment (diasf) [reply dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/dataset/PeriodoDictionary.java:207]: Fair enough, but there's already a stream created to iterate through locations.

To be fair, I'm not familiar with the use case for this `PeriodoDictionary` and why it was the done that way. Wouldn't it make sense to use a search engine instead? We already have lucene, and seems like a fitting use-case for it.

**Review by diasf — APPROVED** [review]
