### PR TITLE
Closes #1887: Fix ingest

### LINKED ISSUE #1887: Seemingly successful ingest produces saving error

### PR DESCRIPTION
**Pull request by wtr-icm**

### CODE REVIEW

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/IngestServiceBean.java [hunk 1]
```diff
@@ -766,182 +756,63 @@ public boolean ingestAsTabular(Long datafile_id) {
...
-
-                        dataFile = fileService.save(dataFile);
-                    }
-                }
-
-                if (!databaseSaveSuccessful) {
-                    logger.warning("Ingest failure (!databaseSaveSuccessful).");
-                    return false;
-                }
+        if (tabDataIngest == null) {
```
Comment (madryk) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/IngestServiceBean.java]: This is always false `if`. `tabDataIngest = ingestPlugin.read(inputStream, additionalData);` will either throw exception or will return value. We could safely remove this `if.

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/IngestServiceBean.java [hunk 2]
```diff
@@ -766,182 +756,63 @@ public boolean ingestAsTabular(Long datafile_id) {
...
+        // and change the mime type to "Tabular Data" on the final datafile,
+        // and replace (or add) the extension ".tab" to the filename:
+        dataFile.setContentType(TextMimeType.TSV_ALT.getMimeValue());
+        IngestUtil.modifyExistingFilename(
+                dataFile.getOwner().getLatestVersion(), dataFile.getFileMetadata(), FileUtil.replaceExtension(fileName, "tab"));
 
-                    /*end of save as backup */
+        tabDataIngest.getDataTable().setOriginalFileFormat(
+                TextMimeType.CSV_ALT.getMimeValue().equals(dataFile.getContentType())
+                        ? TextMimeType.CSV.getMimeValue() : originalContentType);
```
Comment (madryk) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/IngestServiceBean.java]: I think that this conditional is always false `TextMimeType.CSV_ALT.getMimeValue().equals(dataFile.getContentType())`. Above we have `dataFile.setContentType(TextMimeType.TSV_ALT.getMimeValue());` statement.

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/FinalizeIngestService.java [hunk 3]
```diff
@@ -0,0 +1,139 @@
...
+
+            StorageIO<DataFile> tabularStorageIO = dataAccess.getStorageIO(dataFile);
+            tabularStorageIO.open();
+
+            // and we want to save the original of the ingested file:
+            try {
+                tabularStorageIO.backupAsAux(StorageIOConstants.SAVED_ORIGINAL_FILENAME_EXTENSION);
+                logger.fine("Saved the ingested original as a backup aux file: " + StorageIOConstants.SAVED_ORIGINAL_FILENAME_EXTENSION);
+            } catch (IOException iox) {
+                logger.warning("Failed to save the ingested original! " + iox.getMessage());
```
Comment (madryk) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/FinalizeIngestService.java]: We most probably want to remove this catch. If original file failed to save then next line `tabularStorageIO.savePath` could potentially overwrite the original file (as a result we would end up without the file that was stored originally by the user).

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/FinalizeIngestService.java [hunk 4]
```diff
@@ -0,0 +1,139 @@
...
+            }
+
+            // Replace contents of the file with the tab-delimited data produced:
+            tabularStorageIO.savePath(Paths.get(tabFile.getAbsolutePath()));
+            // Reset the file size:
+            dataFile.setFilesize(tabularStorageIO.getSize());
```
Comment (madryk) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/FinalizeIngestService.java]: Probably we could remove this `setFilesize` (setFilesize was already done in IngestServiceBean).

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/FinalizeIngestService.java [hunk 5]
```diff
@@ -0,0 +1,139 @@
...
+                dataFile.SetIngestProblem();
+                dataFile.setIngestReport(IngestReport.createIngestFailureReport(dataFile, IngestError.DB_FAIL));
+
+                restoreIngestedDataFile(dataFile, tabDataIngest, originalFileSize, originalFileName, originalContentType);
+
+                fileService.save(dataFile);
+            }
+        } finally {
+            // delete the temp tab-file:
+            tabFile.delete();
```
Comment (madryk) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/FinalizeIngestService.java]: Probably it would be better if we would do this delete outside this method:
try {
  return finalizeIngestService.finalizeIngest(dataFile, additionalData, tabDataIngest, tabFile);
} finally {
  tabFile.delete();
}

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/FinalizeIngestService.java [hunk 6]
```diff
@@ -0,0 +1,139 @@
...
+            dataFile = fileService.find(dataFileId);
+
+            if (dataFile != null) {
+                dataFile.SetIngestProblem();
+                dataFile.setIngestReport(IngestReport.createIngestFailureReport(dataFile, IngestError.DB_FAIL));
+
+                restoreIngestedDataFile(dataFile, tabDataIngest, originalFileSize, originalFileName, originalContentType);
+
+                fileService.save(dataFile);
+            }
```
Comment (madryk) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/FinalizeIngestService.java:116]: Maybe `return false` would be a good option here? Just a proposition - it doesn't have any critical meaning. It only will change one logger statement in `IngestMessageBean` (`logger.warning("Error occurred during ingest job for file id " + datafile_id + "!");`)

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/IngestServiceBean.java [hunk 7]
```diff
@@ -766,182 +756,63 @@ public boolean ingestAsTabular(Long datafile_id) {
...
-                    tabFile.delete();
-                }
+            logger.warning("Ingest failure: post-ingest tasks.");
+        }
 
-                return true;
-            }
-        } else {
-            logger.warning("Ingest failed to produce data obect.");
+        if (!postIngestTasksSuccessful) {
```
Comment (madryk) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/IngestServiceBean.java]: This `if` will be true only in case when:
```
        try {
            produceSummaryStatistics(dataFile, tabFile);
            produceFrequencyStatistics(dataFile, tabFile);
```
will throw an exception. I would propose to get rid of this boolean and just return false in catch statement

**Review by madryk — CHANGES_REQUESTED** [review]

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/FinalizeIngestService.java (hunk 4 above)
Comment (wtr-icm) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/FinalizeIngestService.java]: It's not very clear why they're setting that size again, but indeed it seems redundant.
This also means that following `save(dataFile)` is not needed.

**Review by madryk — APPROVED** [review]
