### PR TITLE
Closes #998: Fixed ingest error messages.

### LINKED ISSUE #998: Information about errors regarding tabular data is produced in Ponglish
,,Przesyłanie zakończone z błędami. Analiza danych tabelarycznych nie powiodła się. Invalid header row. One of the cell is empty.''

image

### PR DESCRIPTION
**Pull request by MrK191**

### CODE REVIEW

File: dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/datafile/DataFile.java [hunk 1]
```diff
@@ -339,11 +340,24 @@ public void setIngestRequest(IngestRequest ingestRequest) {
...
+                    String bundleValue = BundleUtil.getStringFromBundle(ingestReport.getArgumentsBundleKey().get());
+
+                    return bundleValue.isEmpty() ? report : bundleValue;
+                } else if (ingestReport.getArgumentsBundleKey().isDefined() && !ingestReport.getReportArguments().isEmpty()) {
+                    String bundleValue = BundleUtil.getStringFromBundle(ingestReport.getArgumentsBundleKey().get(), ingestReport.getReportArguments());
+
+                    return bundleValue.isEmpty() ? report : bundleValue;
+                }
+
+                return report;
```
Comment (kaczynskid) [inline dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/datafile/DataFile.java]: Feature envy - this whole logic seems better placed in `IngestReport` class instead.

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/IngestException.java [hunk 2]
```diff
@@ -0,0 +1,48 @@
+package edu.harvard.iq.dataverse.ingest;
+
+import com.google.common.collect.Lists;
+import io.vavr.control.Option;
```
Comment (kaczynskid) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/IngestException.java]: Why not simply `java.util.Optional`?

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/IngestException.java [hunk 3]
```diff
@@ -0,0 +1,48 @@
...
+    private String bundleKey;
+    private List<String> bundleArguments = new ArrayList<>();
+
+    // -------------------- CONSTRUCTORS --------------------
+
+    public IngestException(String message) {
+        super(message);
+    }
+
+    public IngestException(String message, String bundleKey) {
```
Comment (kaczynskid) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/IngestException.java]: Seems redundant to pass both the message and the key it was resolved from? To avoid typing problems (both message and the key are `String`s a factory method pattern can be utilized to resolve the bundle key instead of requiring the caller to do the resolution.

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/IngestServiceBean.java [hunk 4]
```diff
@@ -850,21 +855,29 @@ public boolean ingestAsTabular(Long datafile_id) {
...
-            dataFile = fileService.save(dataFile);
 
-            logger.warning("Ingest failure (IO Exception): " + ingestEx.getMessage() + ".");
+            if (ex.getBundleKey().isDefined() && ex.getBundleArguments().isEmpty()) {
+                FileUtil.createIngestFailureReport(dataFile, ex.getMessage(), ex.getBundleKey().get());
+            } else if (ex.getBundleKey().isDefined() && !ex.getBundleArguments().isEmpty()) {
+                FileUtil.createIngestFailureReport(dataFile, ex.getMessage(), ex.getBundleKey().get(), ex.getBundleArguments().toArray(new String[0]));
+            } else {
+                FileUtil.createIngestFailureReport(dataFile, ex.getMessage());
+            }
```
Comment (kaczynskid) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/IngestServiceBean.java]: Why not instead have a method `FileUtil#createIngestFailureReport(DataFile, IngestException)` and do all those iffy logic inside it?

File: dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/datafile/ingest/IngestReport.java [hunk 5]
```diff
@@ -55,6 +60,12 @@ public void setId(Long id) {
     @Lob
     private String report;
 
+    private String argumentsBundleKey;
+
+    @ElementCollection
+    @OrderColumn
+    private List<String> reportArguments = new ArrayList<>();
```
Comment (kaczynskid) [inline dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/datafile/ingest/IngestReport.java]: It seems redundant to save both the key and it's value from arbitrarily chosen language. How about only saving the bundle key and arguments under `report` & `reportArguments` respectively? Value of the `report` field could be the fallback in case of unsolvable key, but I'd enforce the bundle key here, as we want to enforce i18n.

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/DataFileServiceBean.java [hunk 6]
```diff
@@ -1508,15 +1511,15 @@ public boolean isSameTermsOfUse(FileTermsOfUse termsOfUse1, FileTermsOfUse terms
                 // just clear the datafiles list and let
                 // ingest default to creating a single DataFile out
                 // of the unzipped file.
-                logger.warning("Unzipping failed; rolling back to saving the file as is.");
+                logger.log(Level.WARNING, "Unzipping failed; rolling back to saving the file as is.", ioex);
                 if (warningMessage == null) {
-                    warningMessage = BundleUtil.getStringFromBundle("dataset.file.zip.unzip.failure");
+                    errorMessageAndBundleKey = Tuple.of("Failed to unzip the file. Saving the file as is.", "dataset.file.zip.unzip.failure");
```
Comment (kaczynskid) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/DataFileServiceBean.java]: Why not use the same message for both the logger and persisted error?

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/IngestException.java [hunk 7]
```diff
@@ -0,0 +1,48 @@
...
+        super(message);
+        this.bundleKey = bundleKey;
+    }
+
+    public IngestException(String message, String bundleKey, String... bundleArguments) {
+        super(message);
+        this.bundleKey = bundleKey;
+        this.bundleArguments = Lists.newArrayList(bundleArguments);
```
Comment (kaczynskid) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/IngestException.java]: How about `java.util.Arrays.asList(...)` ?

**Review by kaczynskid — CHANGES_REQUESTED** [review]
Passing both the bundle key and it's English value seems redundant and introduces a lot of noise into already complex code. I think we should focus on passing the key only and lazily resolve, only when necessary. Optionally use the key as is as fallback in case of failed resolution.

File: dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/datafile/DataFile.java (hunk 1 above)
Comment (MrK191) [reply dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/datafile/DataFile.java]: I agree, I kinda wanted to stop myself from refactoring overall since it is very easy to sink into "Shotgun Surgery".

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/IngestException.java (hunk 2 above)
Comment (MrK191) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/IngestException.java]: I kinda like `Option` api more, it has an option to do `ifPresentOrElse()` like Optional in java 9. It also has method like `getOrNull` for legacy (ofc you can also do it in Optional). So just preference.

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/IngestException.java (hunk 3 above)
Comment (MrK191) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/IngestException.java]: We talked about it with Krzysiek, the idea is to have message as backup. If we ever do some kind of Bundle refactoring or anything happens to keys, this will be our backup message.

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/IngestException.java (hunk 2 above)
Comment (kaczynskid) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/IngestException.java]: Mentioned features are not used at all in `IngestServiceBean`. Instead anti-pattern of `isDefined()` and `get()` are used. Pulling Vavr here is simply overkill. Let's keep it simple and stick to JDK.

File: dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/datafile/DataFile.java (hunk 1 above)
Comment (kaczynskid) [reply dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/datafile/DataFile.java]: All that code was actually added here now and "extract method" refactoring is far from "shotgun surgery". Let's move this logic where it belongs.

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/IngestException.java (hunk 3 above)
Comment (kaczynskid) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/IngestException.java]: I'm not sure what could happen to the keys other then them being changed? A separate bundle can be created with extra info where it's used and that in case of changes a database change set needs to also update database values. From code perspective the actual message in any language is irrelevant. What's relevant is the error classification that is done by the keys. I18n messages are only translations of those keys that can always be re-created - we have a backup of those in git already.

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/IngestException.java (hunk 2 above)
Comment (MrK191) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/IngestException.java]: Yes, but if someone would want to use this api he would have to refactor the getter and all the method calls (although you can call it YAGNI, so I understand). Yes it is anti-pattern but in this case I thought it was more readable, your call.

File: dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/datafile/ingest/IngestReport.java (hunk 5 above)
Comment (MrK191) [reply dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/datafile/ingest/IngestReport.java]: The problem is that we already have reports in database, so we can't put the bundle key in `report` field.

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/IngestException.java (hunk 2 above)
Comment (kaczynskid) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/IngestException.java]: I'm not sure either `Option` or `Optional` are even needed here? You always call `get()` and then only pass the value to the setter of `IngestReport`. No logic is actually there and the field in `IngestReport` is nullable. Refactor `FileUtil#createIngestFailureReport(..)` as mentioned below and see if we can have a simple getter instead. Also only use `Optional` / `Option` if you mean to use it's API, if not, use regular null checks. Doing standard null checks using `Optional` / `Option` API, like it is now in `IngestServiceBean`, is much less readable than simple `if (x == null)` and not worth the trouble.

File: dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/datafile/ingest/IngestReport.java (hunk 5 above)
Comment (kaczynskid) [reply dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/datafile/ingest/IngestReport.java]: Do we already have a production installation with actual production data that cannot be changed? Or do you mean the test instances only? I though we didn't have a public release yet, did we? Even if we did, current values would follow the fallback scenario and still work just fine. And if we have existing records, don't we want translations for them too as a database changeset that converts raw messages into bundle keys?

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/IngestException.java (hunk 2 above)
Comment (MrK191) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/IngestException.java]: Ok I have to agree in the 1st part. About the 2nd I do not exactly agree, for me the benefit besides Optional API is information. For the dev who never worked in some part of code `Optional` gives information that this field can be missing. You don't even need to look inside the class (I'm talking overall about Optional). There are also article mentioned by Stuart Mark: [article](https://blog.joda.org/2015/08). I know this is controversial since I've had conversations about this before and people are divided. But this is my opinion :P.

File: dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/datafile/ingest/IngestReport.java (hunk 5 above)
Comment (MrK191) [reply dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/datafile/ingest/IngestReport.java]: We don't but during conversation with Krzysiek and Wojtek I received information that we have to think about reports that are present. I haven't asked why in this case. 

> Even if we did, current values would follow the fallback scenario and still work just fine.

But in the case of not finding a key in bundle if it is a key we would return useless key id to the user.

> And if we have existing records, don't we want translations for them too as a database changeset that converts raw messages into bundle keys?

 Well we were under the impression that converting messages to bundle keys is slippery slope. 

I think the best thing to do is talk about it during daily, I don't want to break the agreements that I made without them knowing, ok?

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/IngestException.java (hunk 2 above)
Comment (kaczynskid) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/IngestException.java]: Yes, `Optional` can be informative and useful, given proper context. If the only context it's usable is to convert it back into a nullable filed, than it's use is highly questionable. Also, my general preference is to use OOP encapsulation to avoid getters entirely wherever possible with all the problems they bring. But that's a story for another day ;)

File: dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/datafile/ingest/IngestReport.java (hunk 5 above)
Comment (kaczynskid) [reply dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/datafile/ingest/IngestReport.java]: Yep, let's talk it through with them tomorrow morning.

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/IngestException.java (hunk 2 above)
Comment (MrK191) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/IngestException.java]: I have to agree in this case, kinda lost big picture here. Well that's the story I would like to hear ;)

File: dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/datafile/ingest/IngestReport.java [hunk 8]
```diff
@@ -52,8 +57,12 @@ public void setId(Long id) {
...
     private DataFile dataFile;
 
-    @Lob
-    private String report;
+    @Enumerated(EnumType.STRING)
+    private IngestError errorKey;
+
+    @ElementCollection
+    @OrderColumn
+    private List<String> reportArguments = new ArrayList<>();
```
Comment (kaczynskid) [inline dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/datafile/ingest/IngestReport.java]: If we renamed the `report` field to `errorKey`, than this one could maybe be `errorArguments`?

File: dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/datafile/ingest/IngestReport.java [hunk 9]
```diff
@@ -121,6 +130,30 @@ public void setEndTime(Date endTime) {
...
+    }
+
+    // -------------------- LOGIC --------------------
+
+    public String getIngestReportMessage() {
+        IngestError errorKey = getErrorKey();
+        if (errorKey != null) {
+
+            if (!getReportArguments().isEmpty()) {
+                String errorMessage = IngestError.getErrorMessage(errorKey, getReportArguments());
```
Comment (kaczynskid) [inline dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/datafile/ingest/IngestReport.java]: Why not use the filed directly instead of via getter here?

File: dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/datafile/ingest/IngestError.java [hunk 10]
```diff
@@ -0,0 +1,52 @@
...
+    RTAB_UNREDABLE_BOOLEAN,
+    RTAB_VARQNTY_MISSING,
+    RTAB_VARQNTY_ZERO,
+    UNKNOWN_ERROR;
+
+    public static String ERROR_KEY_PREFIX = "ingest.error.";
+
+    // -------------------- LOGIC --------------------
+
+    public static String getErrorMessage(IngestError error) {
```
Comment (kaczynskid) [inline dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/datafile/ingest/IngestError.java]: Why is this method `static`? It should be an instance method.

File: dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/datafile/ingest/IngestError.java [hunk 11]
```diff
@@ -0,0 +1,52 @@
...
+        return BundleUtil.getStringFromBundle(ERROR_KEY_PREFIX + error.toString());
+    }
+
+    public static String getErrorMessage(IngestError error, List<String> arguments) {
```
Comment (kaczynskid) [inline dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/datafile/ingest/IngestError.java]: Why is this method `static`? It should be an instance method.

File: dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/datafile/ingest/IngestReport.java [hunk 12]
```diff
@@ -121,6 +130,30 @@ public void setEndTime(Date endTime) {
...
     }
 
+    public List<String> getReportArguments() {
+        return reportArguments;
+    }
+
+    // -------------------- LOGIC --------------------
+
+    public String getIngestReportMessage() {
+        IngestError errorKey = getErrorKey();
```
Comment (kaczynskid) [inline dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/datafile/ingest/IngestReport.java]: Why not use the filed directly instead of via getter here?

File: dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/datafile/ingest/IngestReport.java [hunk 13]
```diff
@@ -121,6 +130,30 @@ public void setEndTime(Date endTime) {
...
+
+                return errorMessage.isEmpty() ? IngestError.getDefaultErrorMessage() : errorMessage;
+            }
+
+            String errorMessage = IngestError.getErrorMessage(errorKey);
+
+            return errorMessage.isEmpty() ? IngestError.getDefaultErrorMessage() : errorMessage;
+        }
+
+        return IngestError.getDefaultErrorMessage();
```
Comment (kaczynskid) [inline dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/datafile/ingest/IngestReport.java]: This looks like a great use case for `Optional` and Null Object Pattern. I'd see this whole method simply like this:
```
return Optional.ofNullable(errorKey)
        .orElse(IngestError.UNKNOWN_ERROR)
        .getMessage(Optional.ofNullable(errorArguments)
                .orElseGet(Collections::emptyList));
```
And `getMessage(..)` should handle empty arguments and never return empty `String`.

File: dataverse-persistence/src/main/resources/Bundle_pl.properties [hunk 14]
```diff
@@ -2041,10 +2041,20 @@ file.versionDifferences.fileUnrestricted=Niezastrze\u017Cony
 file.versionDifferences.fileGroupTitle=Plik
 
 # File Ingest
-ingest.csv.invalidHeader=Niepoprawny wiersz nag\u0142\u00F3wka. Jedna z kom\u00F3rek jest pusta.
-ingest.csv.lineMismatch=Niezgodno\u015B\u0107 liczby linii odnalezionych w pierwszym i ostatnim przebiegu. W pierwszym przebiegu odnaleziono {0} linii, a w ostatnim {1}.
-ingest.csv.recordMismatch=B\u0142\u0105d odczytu linii {0} w pliku danych: oczekiwano {1} oddzielonych warto\u015Bci, odnaleziono {2}.
+ingest.error.INVALID_HEADER=Niepoprawny wiersz nag\u0142\u00F3wka. Jedna z kom\u00F3rek jest pusta.
+ingest.error.LINE_MISMATCH=Niezgodno\u015B\u0107 liczby linii odnalezionych w pierwszym i ostatnim przebiegu. W pierwszym przebiegu odnaleziono {0} linii, a w ostatnim {1}.
+ingest.error.RECORD_MISMATCH=B\u0142\u0105d odczytu linii {0} w pliku danych: oczekiwano {1} oddzielonych warto\u015Bci, odnaleziono {2}.
```
Comment (kaczynskid) [inline dataverse-persistence/src/main/resources/Bundle_pl.properties]: Why not keep the CSV prefix for those few? It seems to have been kept for `EXCEL` & `RTAB` above.

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/DataFileServiceBean.java [hunk 15]
```diff
@@ -1508,15 +1510,15 @@ public boolean isSameTermsOfUse(FileTermsOfUse termsOfUse1, FileTermsOfUse terms
                 // just clear the datafiles list and let
                 // ingest default to creating a single DataFile out
                 // of the unzipped file.
-                logger.warning("Unzipping failed; rolling back to saving the file as is.");
+                logger.log(Level.WARNING, "Failed to unzip the file. Saving the file as is.", ioex);
                 if (warningMessage == null) {
```
Comment (kaczynskid) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/DataFileServiceBean.java]: Maybe rather `errorKey != null` ?

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/DataFileServiceBean.java [hunk 16]
```diff
@@ -1241,6 +1242,7 @@ public boolean isSameTermsOfUse(FileTermsOfUse termsOfUse1, FileTermsOfUse terms
         List<DataFile> datafiles = new ArrayList<>();
 
         String warningMessage = null;
+        IngestError errorKey = null;
```
Comment (kaczynskid) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/DataFileServiceBean.java:1244]: Shouldn't `errorKey` replace `warningMessage` entierly? There are still 2 usages of `warningMessage` below that seem like they should be replaced by `errorKey`?

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/IngestException.java [hunk 17]
```diff
@@ -0,0 +1,43 @@
...
+import javax.ejb.ApplicationException;
+import java.util.ArrayList;
+import java.util.Arrays;
+import java.util.List;
+
+@ApplicationException(rollback = true)
+public class IngestException extends RuntimeException {
+
+    private IngestError errorKey;
+    private List<String> bundleArguments = new ArrayList<>();
```
Comment (kaczynskid) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/IngestException.java]: `reportArguments` in `IngestReport` and `bundleArguments` here while at the same goes in pair with `errorKey`? Wouldn't it sound better with the same prefix everywhere? I.e. `errorKey` & `errorArguments` ? Or simply `error` and `arguments` ?

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/IngestException.java [hunk 18]
```diff
@@ -0,0 +1,43 @@
...
+
+    // -------------------- CONSTRUCTORS --------------------
+
+    public IngestException(IngestError errorKey) {
+        super("");
```
Comment (kaczynskid) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/IngestException.java]: If you pass empty string to the `super` constructor, when this exception gets logged it will have an empty message. That's rather undesirable. Let's replace it with some generic message containing the error key and arguments instead.

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/tabulardata/impl/plugins/csv/CSVFileReader.java [hunk 19]
```diff
@@ -195,7 +196,7 @@ public int readFile(BufferedReader csvReader, DataTable dataTable, PrintWriter f
                     List<String> args = Arrays.asList("" + (parser.getCurrentLineNumber() - 1),
                                                       "" + headers.size(),
                                                       "" + record.size());
-                    throw new IOException(BundleUtil.getStringFromBundle("ingest.csv.recordMismatch", args));
+                    throw new IngestException(IngestError.RECORD_MISMATCH, args.toArray(new String[0]));
```
Comment (kaczynskid) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/tabulardata/impl/plugins/csv/CSVFileReader.java]: Consider a constructor accepting a `List` instead of calling `toArray` and than building a list from that array in the constructor.

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/tabulardata/impl/plugins/dta/DTAFileReader.java [hunk 20]
```diff
@@ -529,7 +531,7 @@ public TabularDataIngest read(BufferedInputStream stream, File dataFile) throws
 
             ingesteddata.setDataTable(dataTable);
         } catch (IllegalArgumentException iaex) {
-            throw new IOException(iaex.getMessage());
+            throw new IngestException(IngestError.UNKNOWN_ERROR, iaex);
```
Comment (kaczynskid) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/tabulardata/impl/plugins/dta/DTAFileReader.java:534]: Are you sure you want to pass `iaex.toString()` as argument, while it was `iaex.getMessage()`?
Alternatively, why not allow `IngestException` to accept a causing exception and handle that cause message as argument in there?

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/tabulardata/impl/plugins/xlsx/XLSXFileReader.java [hunk 21]
```diff
@@ -129,16 +132,30 @@ public TabularDataIngest read(BufferedInputStream stream, File dataFile) throws
             valueTokens = line.split("" + delimiterChar, -2);
 
             if (valueTokens == null) {
-                throw new IOException(BundleUtil.getStringFromBundle("xlsxfilereader.ioexception.failed", Arrays.asList(Integer.toString(lineCounter + 1))));
+                String message = MessageFormat.format("Failed to read line {0} during the second pass.",
```
Comment (kaczynskid) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/tabulardata/impl/plugins/xlsx/XLSXFileReader.java]: Unused variable?

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/tabulardata/impl/plugins/xlsx/XLSXFileReader.java [hunk 22]
```diff
@@ -129,16 +132,30 @@ public TabularDataIngest read(BufferedInputStream stream, File dataFile) throws
...
+                                                      Arrays.asList(Integer.toString(lineCounter + 1)));
+
+                throw new IngestException(IngestError.EXCEL_READ_FAIL,
+                                          Integer.toString(lineCounter + 1));
             }
 
             if (valueTokens.length != varQnty) {
-                throw new IOException(BundleUtil.getStringFromBundle("xlsxfilereader.ioexception.mismatch", Arrays.asList(Integer.toString(lineCounter + 1), Integer.toString(varQnty), Integer.toString(valueTokens.length))));
+                String message = MessageFormat.format(
```
Comment (kaczynskid) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/tabulardata/impl/plugins/xlsx/XLSXFileReader.java]: Unused variable?

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/tabulardata/impl/plugins/xlsx/XLSXFileReader.java [hunk 23]
```diff
@@ -161,7 +178,12 @@ public TabularDataIngest read(BufferedInputStream stream, File dataFile) throws
                             Double testDoubleValue = new Double(valueTokens[i]);
                             caseRow[i] = testDoubleValue.toString();
                         } catch (Exception ex) {
-                            throw new IOException("Failed to parse a value recognized as numeric in the first pass! column: " + i + ", value: " + valueTokens[i]);
+                            String message = MessageFormat.format(
```
Comment (kaczynskid) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/tabulardata/impl/plugins/xlsx/XLSXFileReader.java]: Unused variable?

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/util/FileUtil.java [hunk 24]
```diff
@@ -554,18 +558,29 @@ public static String generateStorageIdentifier() {
         return storageIdentifier;
     }
 
-    public static void createIngestFailureReport(DataFile dataFile, String message) {
-        createIngestReport(dataFile, IngestReport.INGEST_STATUS_FAILURE, message);
+    public static void createIngestFailureReport(DataFile dataFile, IngestException ingestException) {
+        FileUtil.createIngestFailureReport(dataFile,
+                                           ingestException.getErrorKey(),
+                                           ingestException.getBundleArguments().toArray(new String[0]));
```
Comment (kaczynskid) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/util/FileUtil.java]: `toArray` straight into `Arrays.asList`...

File: dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/ingest/tabulardata/impl/plugins/csv/CSVFileReaderTest.java [hunk 25]
```diff
@@ -397,15 +404,15 @@ public void testVariableUNFs() {
...
             fail("IOException not thrown on null csv");
         } catch (NullPointerException ex) {
-            assertEquals(null, ex.getMessage());
-        } catch (IOException ex) {
-            String expMessage = BundleUtil.getStringFromBundle("ingest.csv.nullStream");
-            assertEquals(expMessage, ex.getMessage());
+            assertNull(ex.getMessage());
+        } catch (IngestException ex) {
+            IngestError expError = IngestError.UNKNOWN_ERROR;
+            assertEquals(expError, ex.getErrorKey());
```
Comment (kaczynskid) [inline dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/ingest/tabulardata/impl/plugins/csv/CSVFileReaderTest.java:439]: Bonus points for replacing with `@Rule ExpectedException` ;)

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/DataFileServiceBean.java [hunk 26]
```diff
@@ -1508,15 +1510,15 @@ public boolean isSameTermsOfUse(FileTermsOfUse termsOfUse1, FileTermsOfUse terms
                 // just clear the datafiles list and let
                 // ingest default to creating a single DataFile out
                 // of the unzipped file.
-                logger.warning("Unzipping failed; rolling back to saving the file as is.");
+                logger.log(Level.WARNING, "Failed to unzip the file. Saving the file as is.", ioex);
```
Comment (kaczynskid) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/DataFileServiceBean.java]: Bonus points for replacing with Slf4j ;)

**Review by kaczynskid — CHANGES_REQUESTED** [review]
I think there is a bug in `DataFileServiceBean` - see comments in that file. Other than that rather minor comments. Also a few totally optional bonus proposals.

File: dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/datafile/ingest/IngestReport.java (hunk 9 above)
Comment (MrK191) [reply dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/datafile/ingest/IngestReport.java]: Well I would have to duplicate the internals of the method, I just didn't see a reason to.

Comment (kaczynskid) [reply dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/datafile/ingest/IngestReport.java]: I meant `reportArguments` instead of `getReportArguments()` - there's no internals there to speak of ;)

Comment (MrK191) [reply dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/datafile/ingest/IngestReport.java]: Ohh, there is no real reason, is there a reason you prefer direct field call instead of calling getter? You think it's more readable (One thing I can think of, is that in getter there could be some kind of logic, if you call it directly you are sure there won't be)?

Comment (kaczynskid) [reply dataverse-persistence/src/main/java/edu/harvard/iq/dataverse/persistence/datafile/ingest/IngestReport.java]: The reason is encapsulation. Getters are meant to expose object internal state to the outside. Additionally non final getters can be affected by inheritance. In general they are a tool to break encapsulation. Meanwhile I'd like to keep the object method implementation well encapsulated, operate on internal object state directly and keep it closed to modification. Sure, there are use cases to use methods to get internal state instead, but that's rather when you expect sub-classes to contribute, not when it's just a plain getter.

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/DataFileServiceBean.java (hunk 15 above)
Comment (MrK191) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/DataFileServiceBean.java]: You mean `errorKey == null`? Since we don't want to override if there is key already assigned.

Comment (kaczynskid) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/DataFileServiceBean.java]: Yep. In general the condition on `errorKey` rather than on `warningMessage`.

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/tabulardata/impl/plugins/dta/DTAFileReader.java (hunk 20 above)
Comment (MrK191) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/tabulardata/impl/plugins/dta/DTAFileReader.java:534]: It is actually passed as `Throwable cause` here.

Comment (kaczynskid) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/tabulardata/impl/plugins/dta/DTAFileReader.java:534]: Yes, it is, you're right.

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/DataFileServiceBean.java (hunk 26 above)
Comment (MrK191) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/DataFileServiceBean.java]: We had the discussion long time ago with the team, the reason we are using java logger is that it is supported by glassfish. We wanted to use Slf4j but it wouldn't work with glassfish afair.

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/util/FileUtil.java (hunk 24 above)
Comment (MrK191) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/util/FileUtil.java]: Most callers are using single argument, I could overload the method but is it actually worth it?

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/tabulardata/impl/plugins/csv/CSVFileReader.java (hunk 19 above)
Comment (MrK191) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/tabulardata/impl/plugins/csv/CSVFileReader.java]: If I would accept `List` then in a lot of method calls I would have to wrap arguments with `Arrays.asList()`. So in the end it wouldn't change much.

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/util/FileUtil.java (hunk 24 above)
Comment (kaczynskid) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/util/FileUtil.java]:
```
void createIngestFailureReport(DataFile dataFile, IngestError errorKey, String... arguments) {
    List<String> args = Optional.ofNullable(arguments).map(Arrays::asList).orElseGet(Collections::emptyList);
    createIngestFailureReport(dataFile, errorKey, args);
}

void createIngestFailureReport(DataFile dataFile, IngestError errorKey, List<String> arguments) {
    IngestReport errorReport = new IngestReport();
    errorReport.setFailure();
    errorReport.setErrorKey(errorKey);
    errorReport.setDataFile(dataFile);
    errorReport.setReportArguments(arguments);
    dataFile.setIngestReport(errorReport);
}
```
The below 2 methods I'd replace with the two above.

Also, now that I look at it, wouldn't it make more sense to have those factory methods in `IngestReport` class? And drop coupling with `DataFile` by dropping the last line, just return `IngestReport` and let the caller use the object as desired?

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/tabulardata/impl/plugins/csv/CSVFileReader.java (hunk 19 above)
Comment (kaczynskid) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/tabulardata/impl/plugins/csv/CSVFileReader.java]: Why not have both? One accepting a `List` and another with varags converted to a `List`?

Comment (MrK191) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/ingest/tabulardata/impl/plugins/csv/CSVFileReader.java]: Hmm, I felt like wrapping stuff wasn't a big deal, but creating additional constructor also isn't, so now that I think about it I don't see why not.

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/DataFileServiceBean.java (hunk 26 above)
Comment (kaczynskid) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/DataFileServiceBean.java]: Hmm... that's odd. I've been using Slf4J and I can see those logs being logged no problem, at least locally. With SLF4J we can re-route the logs into JUL framework used by Glassfish. I can see we have `slf4j-log4j12` in dependencies, which seems to be the problem, as Glassfish uses JUL, not Log4j. When replaced with `slf4j-jdk14` than SLF4J should properly route to JUL. Since it would likely require config changes, let's create a separate task for that to check it out.

Comment (MrK191) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/DataFileServiceBean.java]: That's interesting let's mention that on daily, it was something we knew it was a problem but there were just other stuff to clean up so we haven't dig deep.

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/util/FileUtil.java (hunk 24 above)
Comment (MrK191) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/util/FileUtil.java]: > The below 2 methods I'd replace with the two above.

I could add another with `List<String>` but I'm hesitant about removing `reateIngestFailureReport(DataFile dataFile, IngestError errorKey)`.
It would force the caller to either pass empty list every time or pass null which is kinda an anti-pattern.

> Also, now that I look at it, wouldn't it make more sense to have those factory methods in IngestReport class? And drop coupling with DataFile by dropping the last line, just return IngestReport and let the caller use the object as desired?

Makes sense, but I also have some doubts. Is making those kind of methods in Entities is correct? I always thought about it more of like an model.

File: dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/ingest/tabulardata/impl/plugins/csv/CSVFileReaderTest.java (hunk 25 above)
Comment (MrK191) [reply dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/ingest/tabulardata/impl/plugins/csv/CSVFileReaderTest.java:439]: Hmm, or maybe expected exception in `@Test`? I can't check the IngestError anyway.

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/DataFileServiceBean.java (hunk 26 above)
Comment (kaczynskid) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/DataFileServiceBean.java]: Fixed configuration is already waiting on a PR for acceptance, so you can safely use Slf4J.

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/util/FileUtil.java (hunk 24 above)
Comment (kaczynskid) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/util/FileUtil.java]: Varargs variant also covers the 2-argument call. You don't need to pass `null` as third parameter. In fact you event can't do that as it'd result in an ambiguous call error, as it would not know if by `null` you mean a `List<String>` or a varargs `String`.

As for placing factory method inside the class it's fabricating, it seems much more natural than an arbitrary placement in some utils class with very unclear responsibility. Even if said class is also an entity, factory methods are a kind of constructors, and you place constructors inside the class you're constructing.

File: dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/ingest/tabulardata/impl/plugins/csv/CSVFileReaderTest.java (hunk 25 above)
Comment (kaczynskid) [reply dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/ingest/tabulardata/impl/plugins/csv/CSVFileReaderTest.java:439]: Why not? In this case you assert for `IngestError.UNKNOWN_ERROR` and lower you assert for `IngestError.RECORD_MISMATCH`. It's already in the code, so not sure what you mean...

Comment (MrK191) [reply dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/ingest/tabulardata/impl/plugins/csv/CSVFileReaderTest.java:439]: I mean if I changed the code from `catch (IngestException ex) to ```expectedException.expect(IngestException.class);``` I won't be able to access exception in order to get the Key. I can always assert the message but it was probably not what you meant.

Comment (kaczynskid) [reply dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/ingest/tabulardata/impl/plugins/csv/CSVFileReaderTest.java:439]: Ugh... right, must have been thinking about how Spock handles it nicely... I guess we have Junit5 at least: https://stackoverflow.com/questions/40268446/junit-5-how-to-assert-an-exception-is-thrown Anyways, not a big deal, just `try/catch` looks odd to me in a test.

Comment (MrK191) [reply dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/ingest/tabulardata/impl/plugins/csv/CSVFileReaderTest.java:439]: Yeah when writing new tests we are using Junit5 so there we can use Assert.throws. But afair you also cannot access the internal of the exception there.

Comment (madryk) [reply dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/ingest/tabulardata/impl/plugins/csv/CSVFileReaderTest.java:439]: assertThrows() method returns an exception that was throwed

**Review by kaczynskid — APPROVED** [review]
