### PR TITLE
Closes #1606: Fix citation block for harvested datasets

### LINKED ISSUE #1606: Make a (wholesale) change of the way the "citations" of harvested datasets are presented in search results
Let's keep it simple: 

Fundacja Centrum Badania Opinii Społecznej, 2021, "Aktualne problemy i wydarzenia (220). Wrzesień 2008", https://doi.org/10.18150/YW3VXV

So: 

[authors], [year], "[title]", [url with PID]

### PR DESCRIPTION
**Pull request by dbojanek**
Actually not 100% sure if that's what this task is all about..

### CODE REVIEW

**Comment by madryk** [comment]
Not quite. We have two implementations of citations format converter. One in this repo and one in rds-extension. The one in rds can produce quite weird citations in case of harvested dataset. You can look into test env of rds. Harvested datasets there can have some values in citation like n/a etc. In standard implementation it can happen that instead of publisher there will be distributor instead

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/citation/AbstractCitationFormatsConverter.java [hunk 1]
```diff
@@ -157,9 +157,12 @@ public RISCitationBuilder line(String value) {
         }
 
         public RISCitationBuilder line(String label, String value) {
-            sb.append(label)
-                    .append("  - ");
-            return line(value);
+            if(value != null && !value.equals("null")) {
```
Comment (madryk) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/citation/AbstractCitationFormatsConverter.java]: Remove the cause of comparing string to string null. It would be safer also to use isNotEmpty from StringUtils

Comment (madryk) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/citation/AbstractCitationFormatsConverter.java]: If we are omiting empty values here then probably we should also make modification to the method with the same name above to be consistent

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/citation/AbstractCitationFormatsConverter.java [hunk 2]
```diff
@@ -200,9 +203,11 @@ public void end() throws XMLStreamException {
         }
 
         public EndNoteCitationBuilder addTagWithValue(String tag, String value) throws XMLStreamException {
-            writer.writeStartElement(tag);
-            writer.writeCharacters(value);
-            writer.writeEndElement();
+            if (value != null && !value.equals("null")) {
```
Comment (madryk) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/citation/AbstractCitationFormatsConverter.java]: Same as above. Remove the cause of comparing to string null

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/citation/CitationDataExtractor.java [hunk 3]
```diff
@@ -66,27 +65,32 @@ public CitationData create(FileMetadata fileMetadata, boolean direct) {
...
+            data.getOtherIds().addAll(dsv.getDatasetFieldValuesByTypeName(DatasetFieldConstant.otherIdValue));
+
+            data.setDate(dataDate)
+                    .setProductionPlace(extractField(dsv, DatasetFieldConstant.productionPlace))
+                    .setProductionDate(extractProductionDate(dsv))
+                    .setReleaseYear(extractReleaseYear(dsv))
+                    .setRootDataverseName(dsv.getRootDataverseNameforCitation())
+                    .setSeriesTitle(dsv.getSeriesTitle())
+                    .setPublisher(extractPublisher(dsv))
+                    .setVersion(extractVersion(dsv));
```
Comment (madryk) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/citation/CitationDataExtractor.java:92]: `extractPublisher` and `extractVersion` methods additionally check if dataset is harvested. We could simplify that logic

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/citation/StandardCitationFormatsConverter.java [hunk 4]
```diff
@@ -46,9 +46,21 @@ public String toString(CitationData data, Locale locale, boolean escapeHtml) {
...
+        } else {
+            citation.endPart();
+        }
+
+        if(data.getPublisher() != null) {
+            citation.value(data.getPublisher()).endPart();
+        }
+        if(data.getVersion() != null) {
+            citation.rawValue(data.getVersion()).endPartEmpty();
+        }
```
Comment (madryk) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/citation/StandardCitationFormatsConverter.java]: Probably it would be a little easier to understand what's going on if we would switch logic here a little: Defining what should be before each part instead of what should be at the end:
```
citation.urlValue(pid, pid).endPartEmpty()
    .add(", ").value(data.getPublisher()).endPartEmpty()
    .add(", ").rawValue(data.getVersion()).endPartEmpty()
```

File: dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/citation/CitationTestUtils.java [hunk 5]
```diff
@@ -57,6 +58,16 @@ public DatasetVersion createATestDatasetVersion(String withTitle, boolean withAu
         return datasetVersion;
     }
 
+    public DatasetVersion createHarvestedTestDatasetVersion(String withTitle, boolean withAuthor) {
+        try {
+            DatasetVersion datasetVersion = createATestDatasetVersion(withTitle, withAuthor);
+            datasetVersion.getDataset().setHarvestedFrom(new HarvestingClient());
+            return datasetVersion;
+        } catch (ParseException pe) {
+            return null;
```
Comment (madryk) [inline dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/citation/CitationTestUtils.java:67]: I would avoid catching exceptions in code for tests. Simply adding throws in method declaration will cause that when something is wrong in the code it would be easier to detect the cause of it

File: dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/citation/CitationDataExtractorTest.java [hunk 6]
```diff
@@ -52,4 +75,23 @@ void getDataCiteMetadata() throws ParseException {
...
+        CitationData citationData = dataExtractor.create(datasetVersion);
+
+        //when
+        Map<String, String> properties = citationData.getDataCiteMetadata();
+
+        //then
+        assertThat(properties).hasSize(4);
+        assertThat(properties)
+                .extractingByKeys("datacite.creator", "datacite.publisher", "datacite.title", "datacite.publicationyear")
+                .containsExactly("First Last", ":unav", "Dataset Title", "2021");
```
Comment (madryk) [inline dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/citation/CitationDataExtractorTest.java]: assertion is dependent on current year

File: dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/citation/CitationDataExtractorTest.java [hunk 7]
```diff
@@ -35,6 +38,26 @@ void create() throws ParseException {
...
+
+        // then
+        assertThat(citationData.getAuthorsString()).isEqualTo("First Last");
+        assertThat(citationData.getFileTitle()).isNull();
+        assertThat(citationData.getPersistentId().asString()).isEqualTo("doi:10.5072/FK2/LK0D1H");
+        assertThat(citationData.getPublisher()).isNull();
+        assertThat(citationData.getTitle()).isEqualTo("Dataset Title");
+        assertThat(citationData.getUNF()).isNull();
+        assertThat(citationData.getVersion()).isNull();
+        assertThat(citationData.getYear()).isEqualTo(String.valueOf(Year.now().getValue()));
```
Comment (madryk) [inline dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/citation/CitationDataExtractorTest.java:76]: Maybe we could add a test that will have `.getYear` taken from `ProductionDate` metadataField ?

**Review by madryk — CHANGES_REQUESTED** [review]

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/citation/StandardCitationFormatsConverter.java (hunk 4 above)
Comment (dbojanek) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/citation/StandardCitationFormatsConverter.java]: Didn't know that `,` would not be added if value was missing.

File: dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/citation/CitationDataExtractorTest.java (hunk 7 above)
Comment (dbojanek) [reply dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/citation/CitationDataExtractorTest.java:76]: I'm guessing you mean `DistributionDate`.

**Review by madryk — APPROVED** [review]
