### PR TITLE
Closes #3069: Fix displaying ORCiD number twice when logged in through ORCiD service

### LINKED ISSUE #3069: Fix displaying ORCiD number twice when user is logging in through ORCiD (create account; account details and edit account details pages)
Image

### PR DESCRIPTION
**Pull request by madryk**
I've also removed some methods from the AuthenticationProvider interface. They were used only by ORCiD provider and now they are obsolete.

### CODE REVIEW

File: fairchive-webapp/src/main/java/edu/harvard/iq/dataverse/authorization/providers/common/ExternalIdpFirstLoginPage.java [hunk 1]
```diff
@@ -129,6 +130,8 @@ public class ExternalIdpFirstLoginPage extends BaseUserPage {
 
     private boolean isSamlUser;
 
+    private boolean disableOrcidEdit = false;
```
Comment (sniewczas) [inline fairchive-webapp/src/main/java/edu/harvard/iq/dataverse/authorization/providers/common/ExternalIdpFirstLoginPage.java]: [Minor nitpick] If we rename the field to `orcidEditDisabled`, the getter becomes `isOrcidEditDisabled`, which reads correctly and flows naturally in English.

**Review by sniewczas — APPROVED** [review]
