### PR TITLE
Closes #2420: Filter out un-supported metadata formats when creating an harvesting client

### LINKED ISSUE #2420: Harvesting with oai_datacite and DATACITE metadata schema always fails
We encounter this problem while harvesting repod.icm.edu.pl

image

### PR DESCRIPTION
**Pull request by diasf**
When creating a harvesting client no check was being performed to ensure that we have a matching importer for the selected metadata format.

We have 3 importers:
- DDI (oai_ddi, ddi exporters)
- Dublin Core (oai_dc exporter)
- Dataverse Json

In this change, the list of formats is filtered out to show only those which we are able to import.

For existing client configurations, nothing changes. The user needs to go to the client settings page and change the format manually. 

Issue: #2420

### CODE REVIEW

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/harvest/client/oai/OaiHandler.java [hunk 1]
```diff
@@ -188,17 +205,17 @@ public List<String> runListMetadataFormats() throws OaiHandlerException, IdDoesN
...
             if (!StringUtils.isEmpty(formatName)) {
-                formats.add(formatName);
+                formats.add(format);
             }
         }
 
-        if (formats.size() < 1) {
+        if (formats.isEmpty()) {
             return null;
         }
```
Comment (madryk) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/harvest/client/oai/OaiHandler.java]: IMO we shouldn't return `null` instead of empty list, but just return the list - if it's empty then okay.

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/harvest/client/HarvestingClientsPage.java [hunk 2]
```diff
@@ -483,9 +487,15 @@ public boolean validateServerUrlOAI() {
 
             // First, we'll try to obtain the list of supported metadata formats:
             try {
-                List<String> formats = oaiHandler.runListMetadataFormats();
-                if (formats != null && formats.size() > 0) {
-                    createOaiMetadataFormatSelectItems(formats);
+                List<MetadataFormat> formats = oaiHandler.runListMetadataFormats();
+                if (formats != null && !formats.isEmpty()) {
```
Comment (madryk) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/harvest/client/HarvestingClientsPage.java]: If we are okay with note above (that `oaiHandler.runListMetadataFormats();` shouldn't return `null` in any case) then we could omit `formats` null checking.

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/harvest/client/oai/OaiHandler.java (hunk 1 above)
Comment (diasf) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/harvest/client/oai/OaiHandler.java]: Fair point. Changed it.

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/harvest/client/HarvestingClientsPage.java (hunk 2 above)
Comment (diasf) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/harvest/client/HarvestingClientsPage.java]: Adapted it.

**Review by madryk — APPROVED** [review]
