### PR TITLE
Closes #2226: Change the way license filters work

### LINKED ISSUE #2226: Change the way license filters work
What we would like to change: 

* For files and datasets, include two "other terms": 1) "All rights reserved" and 2) "Restricted access". Note that "Restricted access" has additional flavors, but we don't want to bother with it – "Restricted access" is the only level we are interested in. 

* For datasets, we should filter results according to the information given on the dataset page here (also with the exception for "Restricted access", where we also want to have less granularity): 

image

Currently, this information is not stored anywhere, so we should start storing it (per version) and then add it to index. For datasets we should also include another possible result, namely "Different licenses for individual files".

Consequently, in results filtered by "CC BY" we should have datasets having **all files** on "CC BY" license and not datasets having **only some** files having this license. If the result are filtered by "Different licenses for individual files", we should have only datasets with mixed licenses/other terms and **no files** (as this filter does not make sense for files).

### PR DESCRIPTION
**Pull request by tomaszblazejczyk**

### CODE REVIEW

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/SearchServiceBean.java [hunk 1]
```diff
@@ -636,7 +636,10 @@ private String getNonDatasetFieldFacetLabelName(String facetLabelName, String fo
         if(formattedFacetCategoryName.equals(SearchFields.LICENSE)) {
             return licenseRepository.findLicenseByName(facetLabelName)
                 .map(l -> l.getLocalizedName(BundleUtil.getCurrentLocale()))
-                .orElse(facetLabelName);
+                .orElseGet(() -> {
+                    String label = BundleUtil.getStringFromBundle("facets.search.license." + facetLabelName);
```
Comment (wtr-icm) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/SearchServiceBean.java]: It's better to use some intermediate mapping here (for example static map with keys from allowed `faceLabelName`s and values being the bundle keys), in order to not have partial bundle keys in code (as this makes finding usages of bundle keys problematic).

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/index/IndexServiceBean.java [hunk 2]
```diff
@@ -814,8 +833,18 @@ private String addOrUpdateDataset(IndexableDataset indexableDataset) {
                     datafileSolrInputDocument.addField(SearchFields.CATEGORY_OF_DATAVERSE, dataset.getDataverseContext().getIndexableCategoryName());
                     datafileSolrInputDocument.addField(SearchFields.ACCESS,
                                                        fileMetadata.getTermsOfUse().getTermsOfUseType() == TermsOfUseType.RESTRICTED ? SearchConstants.RESTRICTED : SearchConstants.PUBLIC);
+                    
+                    if (!dataset.hasActiveEmbargo()) {
+                        if (fileMetadata.getTermsOfUse().getTermsOfUseType() == TermsOfUseType.LICENSE_BASED && fileMetadata.getTermsOfUse().getLicense() != null) {
```
Comment (wtr-icm) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/index/IndexServiceBean.java]: Suggestion: we can store `fileMetadata.getTermsOfUse().getTermsOfUseType()` or at least  `fileMetadata.getTermsOfUse()` in a variable, so we have more readable code here.

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/index/IndexServiceBean.java [hunk 3]
```diff
@@ -1032,13 +1061,44 @@ private String addOrUpdateDataset(IndexableDataset indexableDataset) {
...
+            }
+
+            if (!dataset.hasActiveEmbargo() && firstFileTermsOfUse != null) {
+                if (sameLicenseForAllFiles) {
+                    if (firstFileTermsOfUse.getTermsOfUseType() == TermsOfUseType.LICENSE_BASED && firstFileTermsOfUse.getLicense() != null) {
+                        solrInputDocument.addField(SearchFields.LICENSE, firstFileTermsOfUse.getLicense().getName());
+                    } else if (firstFileTermsOfUse.getTermsOfUseType() == TermsOfUseType.ALL_RIGHTS_RESERVED) {
+                        solrInputDocument.addField(SearchFields.LICENSE, IndexedTermOfUse.ALL_RIGHTS_RESERVED.getName());
+                    } else if (firstFileTermsOfUse.getTermsOfUseType() == TermsOfUseType.RESTRICTED) {
+                        solrInputDocument.addField(SearchFields.LICENSE, IndexedTermOfUse.RESTRICTED.getName());
```
Comment (wtr-icm) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/index/IndexServiceBean.java]: Suggestion: also here we can store `firstFileTermsOfUse.getTermsOfUseType()` and `fileMetadata.getTermsOfUse()` in variables. in order to improve readability.

File: dataverse-persistence/src/main/resources/Bundle_pl.properties [hunk 4]
```diff
@@ -2854,6 +2854,9 @@ facets.search.fieldtype.fileAccess.public.label=Publiczny
 facets.search.fieldtype.fileAccess.restricted.label=Ograniczony
 facets.search.fieldtype.metadataSource.label=\u0179r\u00F3d\u0142o metadanych
 facets.search.fieldtype.license.label=Licencja
+facets.search.license.restricted=Ograniczony dost\u0119p
+facets.search.license.multiple=R�\u017Cne licencje dla poszczeg�lnych plik�w
```
Comment (wtr-icm) [inline dataverse-persistence/src/main/resources/Bundle_pl.properties]:
```suggestion
facets.search.license.multiple=R\u00F3\u017Cne licencje dla poszczeg\u00F3lnych plik\u00F3w
```

**Review by wtr-icm — APPROVED** [review]
