### PR TITLE
Closes #3116: Fix import core dataverse using json, fix problem with …

### LINKED ISSUE #3116: Diagnose and solve problem with OAI-PMH imports
We are unable to import anything from vanilla Dataverse installations (for instance from RODBUK or Harvard), neither via Dataverse JSON, nor via simple Dublin Core.

It does not seem to be a natwork problem, as the sets are available and the importer sees the number of datasets.
It must be a relatively recent bug, as on older production version we are able to harvest something (not all, but at lest more than zero datasets).

### PR DESCRIPTION
**Pull request by rscipien**
…validation on required geo localization field. Removed setting NA value for invalid fields and replace it with removing invalid fields from datasets

### CODE REVIEW

File: fairchive-webapp/src/main/java/edu/harvard/iq/dataverse/api/imports/ImportServiceBean.java [hunk 1]
```diff
@@ -210,6 +229,23 @@ private Dataset importDatasetDTOJson(DataverseRequest dataverseRequest, Harvesti
         }
     }
 
+    private void removeInvalidFieldsFromDataset(DatasetVersion  datasetVersion) {
+        int maxValidationCount = 0;
```
Comment (madryk) [inline fairchive-webapp/src/main/java/edu/harvard/iq/dataverse/api/imports/ImportServiceBean.java]: Maybe `validationAttemptNumber` would be more appropriate?

File: fairchive-webapp/src/main/java/edu/harvard/iq/dataverse/api/imports/ImportServiceBean.java [hunk 2]
```diff
@@ -210,6 +229,23 @@ private Dataset importDatasetDTOJson(DataverseRequest dataverseRequest, Harvesti
...
+        while (maxValidationCount <= 10) {
+            List<FieldValidationResult> fieldValidationResults = fieldValidationService.validateFieldsOfDatasetVersion(datasetVersion);
+            if (fieldValidationResults == null || fieldValidationResults.isEmpty()) {
```
Comment (madryk) [inline fairchive-webapp/src/main/java/edu/harvard/iq/dataverse/api/imports/ImportServiceBean.java]: `validateFieldsOfDatasetVersion` should never return null. In general it is considered a bad style to return null when return type is a collection. Although in Fairchive sometimes it is the case. But this method should be ok.
Given that I would get of nullcheck

File: fairchive-webapp/src/main/java/edu/harvard/iq/dataverse/api/imports/ImportServiceBean.java [hunk 3]
```diff
@@ -210,6 +229,23 @@ private Dataset importDatasetDTOJson(DataverseRequest dataverseRequest, Harvesti
         }
     }
 
+    private void removeInvalidFieldsFromDataset(DatasetVersion  datasetVersion) {
+        int maxValidationCount = 0;
+        while (maxValidationCount <= 10) {
```
Comment (madryk) [inline fairchive-webapp/src/main/java/edu/harvard/iq/dataverse/api/imports/ImportServiceBean.java]: IMO `while (!fieldValidationResults.isEmpty())` or `do { } while (!fieldValidationResults.isEmpty())` would be safe enough and cleaner.

But If we go with maximum attempts then probably it would be a good idea to include some comment telling that we assume that 10 attempts will be enough to remove every invalid field. And if it would not then what are consequences of that

Comment (rscipien) [reply fairchive-webapp/src/main/java/edu/harvard/iq/dataverse/api/imports/ImportServiceBean.java]: Yes I was thinks about this at first but since we can't control what is inside validation some bug could create infinite loop

**Review by madryk — APPROVED** [review]
