### PR TITLE
Closes #60: Fix unexpected behavior when switching text/options type after guestbook validation errors

### LINKED ISSUE #60: Find out why you can't change question type on guestbook edit page after validation error and fix it.

### PR DESCRIPTION
**Pull request by madryk**

### CODE REVIEW

File: src/main/java/edu/harvard/iq/dataverse/GuestbookPage.java [hunk 1]
```diff
@@ -143,96 +118,71 @@ public String init() {
...
-        this.editMode = editMode;
-    }
 
     public String save() {
         boolean create = false;
+        
+        if (StringUtils.isEmpty(guestbook.getName())) {
+            FacesContext.getCurrentInstance().validationFailed();
+            FacesContext.getCurrentInstance().addMessage(guestbookName.getClientId(),
+                    new FacesMessage(SEVERITY_ERROR, null, BundleUtil.getStringFromBundle("guestbook.name.empty")));
```
Comment (MrK191) [inline src/main/java/edu/harvard/iq/dataverse/GuestbookPage.java]: We can pass StringUtils.Empty instead of null

File: src/main/java/edu/harvard/iq/dataverse/GuestbookPage.java [hunk 2]
```diff
@@ -143,96 +118,71 @@ public String init() {
...
+            return null;
```
Comment (MrK191) [inline src/main/java/edu/harvard/iq/dataverse/GuestbookPage.java]: We can use StringUtils.Empty instead of null

**Review by MrK191 — CHANGES_REQUESTED** [review]

File: src/main/java/edu/harvard/iq/dataverse/GuestbookPage.java (hunk 1 above)
Comment (madryk) [reply src/main/java/edu/harvard/iq/dataverse/GuestbookPage.java]: ok

File: src/main/java/edu/harvard/iq/dataverse/GuestbookPage.java (hunk 2 above)
Comment (madryk) [reply src/main/java/edu/harvard/iq/dataverse/GuestbookPage.java]: ok

**Review by MrK191 — APPROVED** [review]
