### PR TITLE
Closes #2100: Refactor and fix Datacite export

### LINKED ISSUE #2100: Fix ampersand escaping in dataset title in DATACITE metadata schema

### PR DESCRIPTION
**Pull request by wtr-icm**

### CODE REVIEW

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/globalid/DOIDataCiteRegisterService.java [hunk 1]
```diff
@@ -110,101 +93,41 @@ public String registerIdentifier(String identifier, Map<String, String> metadata
...
-        metadataTemplate.setTitle(title);
-        String producerString = ":unav";
-
-        metadataTemplate.setPublisher(producerString);
-        metadataTemplate.setPublisherYear(metadata.get("datacite.publicationyear"));
-
-        String xmlMetadata = metadataTemplate.generateXML(dvObject);
-        logger.log(Level.FINE, "XML to send to DataCite: {0}", xmlMetadata);
-        return xmlMetadata;
+    public String getMetadataForDeactivateId(String identifier, Map<String, String> metadata, DvObject dvObject) {
```
Comment (madryk) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/globalid/DOIDataCiteRegisterService.java]: From what I can track by what is filled in `Map<String, String> metadata` in case of this method it seems that it is filled only with static values in: `AbstractGlobalIdServiceBean.getDOIMetadataForDestroyedDataset`.
`metadata.get("datacite.title")` is always `This item has been removed from publication` and `metadata.get("datacite.publicationyear")` is always `9999`.
I don't see the point of passing it along the way and basically including some data into produced xml in two steps.
We just can enter this values here and stop passing `Map<String, String> metadata` and `DvObject dvObject` since we don't need it.
Also we can further modify `deactivateIdentifier(String identifier, Map<String, String> metadata, DvObject dvObject)` in this class (metadata and dvObject is not needed)
And at the end simplify (in `DOIDataCiteServiceBean`):
```
                case "public":
                    Map<String, String> metadata = getDOIMetadataForDestroyedDataset();
                    metadata.put("_status", "registered");
                    metadata.put("_target", getTargetUrl(dvObject));
                    doiDataCiteRegisterService.deactivateIdentifier(identifier, metadata, dvObject);
                    break;
```
to simple:
```
                case "public":
                    doiDataCiteRegisterService.deactivateIdentifier(identifier, metadata, dvObject);
                    break;
```
`getDOIMetadataForDestroyedDataset` will not be needed anymore

File: dataverse-webapp/src/test/resources/exportdata/testDatacite.xml [hunk 2]
```diff
@@ -1,18 +1 @@
...
-</resource>
+<resource xsi:schemaLocation="http://datacite.org/schema/kernel-4 http://schema.datacite.org/meta/kernel-4/metadata.xsd" xmlns="http://datacite.org/schema/kernel-4" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><identifier identifierType="DOI">10.5072/FK2/05NAR1</identifier><creators><creator><creatorName>Admin, Dataverse</creatorName><affiliation affiliationIdentifier="https://ror.org/024yc3q36" affiliationIdentifierScheme="ROR">Dataverse.org</affiliation></creator></creators><titles><title>Export test</title></titles><publisher>Root</publisher><publicationYear>2019</publicationYear><resourceType resourceTypeGeneral="Dataset"/><descriptions><description descriptionType="Abstract">EXPORT</description></descriptions><contributors><contributor contributorType="ContactPerson"><contributorName>Admin, Dataverse</contributorName><affiliation>Dataverse.org</affiliation></contributor></contributors><fundingReferences><fundingReference><funderName>Grant Agency</funderName><funderIdentifier funderIdentifierType="ROR">https://ror.org/00e0c0q64</funderIdentifier><awardNumber>grant-123</awardNumber></fundingReference></fundingReferences></resource>
```
Comment (madryk) [inline dataverse-webapp/src/test/resources/exportdata/testDatacite.xml]: Maybe instead of modifying this xml we could do `assertEquals(XmlPrinter.prettyPrintXml(expectedXml), XmlPrinter.prettyPrintXml(actualXml))` in unit test? That way we don't rely so much on formatting of the xml

File: dataverse-webapp/pom.xml [hunk 3]
```diff
@@ -32,10 +32,6 @@
         <!-- Must be defined before dataverse-test-common -->
         <!-- this ensures that xml writing will use this implementation -->
         <!-- in tests instead of the one provided in embedeed glassfish -->
-        <dependency>
```
Comment (madryk) [inline dataverse-webapp/pom.xml:35]: The comment above seems pointless right now

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/export/datacite/ResourceDTOCreator.java [hunk 4]
```diff
@@ -0,0 +1,182 @@
...
+            return Collections.singletonList(new Description(fileDescription != null ? fileDescription : ""));
+        }
+        return Collections.emptyList();
+    }
+
+    private List<Contributor> extractContributors(Dataset dataset) {
+        List<Contributor> contributors = new ArrayList<>();
+        List<Contributor> contacts = dataset.getLatestVersion().getDatasetContacts().stream()
+                .filter(c -> StringUtils.isNotEmpty(c[0]))
+                .map(c -> new Contributor("ContactPerson", c[0],
```
Comment (madryk) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/export/datacite/ResourceDTOCreator.java]: Maybe instead of simple string for contributor type in `Contributor` class we should have an enum (http://schema.datacite.org/meta/kernel-4.1/include/datacite-contributorType-v4.xsd) ?

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/export/datacite/ResourceDTOCreator.java [hunk 5]
```diff
@@ -0,0 +1,182 @@
...
+        if (!contacts.isEmpty() || !producers.isEmpty()) {
+            contributors.addAll(contacts);
+            contributors.addAll(producers);
+        }
+        return contributors;
+    }
+
+    private List<FundingReference> extractFundingReferences(Dataset dataset) {
+        List<DatasetFundingReference> fundingReferencesFromDataset = dataset.getLatestVersion().getFundingReferences();
+        if (fundingReferencesFromDataset == null || fundingReferencesFromDataset.isEmpty()) {
```
Comment (madryk) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/export/datacite/ResourceDTOCreator.java]: Check could be ommited (`getFundingReferences` doesn't return nulls and in case of empty list the code below will still work the same)

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/export/datacite/ResourceDTOCreator.java [hunk 6]
```diff
@@ -0,0 +1,182 @@
...
+import java.util.Collections;
+import java.util.List;
+import java.util.Map;
+import java.util.stream.Collectors;
+
+public class ResourceDTOCreator {
+
+    // -------------------- LOGIC --------------------
+
+    public ResourceDTO create(String identifier, Map<String, String> metadata, DvObject dvObject) {
```
Comment (madryk) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/export/datacite/ResourceDTOCreator.java]: Instead of passing a map of metadata I would change it to just `String publicationYear` if thats all what we need. Right now keepiing track of what's inside a map is cumbersome. If further down the line it will turn out that we need something more, then we can always add a new param. When we change it to `String publicationYear` right now then we will simplify for us further refactors.

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/export/DataCiteExporter.java [hunk 7]
```diff
@@ -53,9 +56,14 @@ public String exportDataset(DatasetVersion version) {
...
                 .getCitationData()
                 .getDataCiteMetadata();
-
-        return DOIDataCiteRegisterService.getMetadataFromDvObject(
-                version.getDataset().getGlobalId().asString(), metadata, version.getDataset());
+        try {
+            XmlMapper mapper = new XmlMapper();
+            mapper.setSerializationInclusion(JsonInclude.Include.NON_EMPTY);
+            return mapper.writeValueAsString(new ResourceDTOCreator()
+                    .create(version.getDataset().getGlobalId().asString(), metadata, version.getDataset()));
```
Comment (madryk) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/export/DataCiteExporter.java]: If we would change it as in comment above we could obtain only `CitationData` from `citationFactor` and just do `citationData.getYear()` here.

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/engine/command/impl/DuraCloudSubmitToArchiveCommand.java [hunk 8]
```diff
@@ -81,8 +85,17 @@ public WorkflowStepResult performArchiveSubmission(DatasetVersion dv, ApiToken t
...
                             .getDataCiteMetadata();
-                    String dataciteXml = DOIDataCiteRegisterService.getMetadataFromDvObject(
-                            dv.getDataset().getGlobalId().asString(), metadata, dv.getDataset());
+
+                    String dataciteXml;
+                    try {
+                        XmlMapper mapper = new XmlMapper();
+                        mapper.setSerializationInclusion(JsonInclude.Include.NON_EMPTY);
+                        dataciteXml = mapper.writeValueAsString(new ResourceDTOCreator()
+                                .create(dv.getDataset().getGlobalId().asString(), metadata, dv.getDataset()));
```
Comment (madryk) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/engine/command/impl/DuraCloudSubmitToArchiveCommand.java]: same case as above. (if we will do it then we could get rid of `CitationData.getDataCiteMetadata()` as well)

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/export/datacite/ResourceDTO.java [hunk 9]
```diff
@@ -0,0 +1,487 @@
...
+import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
+import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;
+import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlText;
+
+import java.util.List;
+
+@JacksonXmlRootElement(localName = "resource")
+@JsonPropertyOrder({ "xsiSchemaLocation", "xmlns", "xmlnsXsi", "identifier", "creators", "titles", "publisher",
+        "publicationYear", "resourceType", "relatedIdentifiers", "descriptions", "contributors", "fundingReferences" })
+public class ResourceDTO {
```
Comment (madryk) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/export/datacite/ResourceDTO.java]: I feel that we are overusing a little `*DTO` postfix. Maybe we could rename it to something more associated with the resulting format like `DataCiteResource`? When we naming it `*DTO` I strongly feel that it is used somwhere on the UI or it is exposed over api.

**Review by madryk — CHANGES_REQUESTED** [review]

File: dataverse-webapp/src/test/resources/exportdata/testDatacite.xml (hunk 2 above)
Comment (madryk) [reply dataverse-webapp/src/test/resources/exportdata/testDatacite.xml]: Actually: `assertThat()..isEqualToIgnoringWhitespace` have one weak point. It will not check whitespaces in tag values (`<tag> test test</tag>` is not the same as `<tag>testtest</tag>`. But we can leave it as is right now. Although in future we should talk about how we want to handle xml comparing (maybe we could find some suitable library)

**Review by madryk — APPROVED** [review]
