### PR TITLE
Closes #1362: Fix DublinCore exporter.

### LINKED ISSUE #1362: Exporting metadata in Dublin Core format sometimes results in 403
https://rds.icm.edu.pl/dataset.xhtml?persistentId=doi%3A10.18150/ZMEMRB

https://rds.icm.edu.pl/api/datasets/export?exporter=DCTERMS&persistentId=doi%3A10.18150/ZMEMRB

### PR DESCRIPTION
**Pull request by wtr-icm**
- Now in places where exporter expects an internal json array we check that expectation against received value's multiplicity, and in case of single value we handle that, not allowing export to fail.
- Some refactors were made, especially in tests (some empty and non-finished were removed). Also a heavy cleaning of unnecessary `HashSet`s that were produced by an incorrect method signature was carried out.

### CODE REVIEW

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/dto/FieldDTO.java [hunk 1]
```diff
@@ -1,28 +1,60 @@
...
+    String typeClass;
+
+    /**
+    * The contents of value depend on the field attributes
+    * if single/primitive, value is a String
+    * if multiple, value is a JSonArray
+    *      multiple/primitive: each JSonArray element will contain String
+    *      multiple/compound: each JSonArray element will contain Set of FieldDTOs
+    */
+    JsonElement value;
```
Comment (MrK191) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/dto/FieldDTO.java]: If we have getters shouldn't all of this be private fields? (I know you just moved the fields :P)

**Review by MrK191 — CHANGES_REQUESTED** [review]

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/dto/FieldDTO.java (hunk 1 above)
Comment (wtr-icm) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/api/dto/FieldDTO.java]: Yes. I forgot to add `private` after removing direct access to those fields in other places :)

**Review by MrK191 — APPROVED** [review]
