### PR TITLE
Closes #2433: Fix errors in advanced search with empty bbox filters and back button

### LINKED ISSUE #2433: Advanced search results in "Internal Dataverse Search Engine Error"
1. I enter the page with "Advanced search". 
2. I enter something into one of the search fields (or not – it does not matter) and click "Find". 
3.  I get: 

image

4. I go back and try different search. Then I get: 

image

### PR DESCRIPTION
**Pull request by diasf**
Fixes 2 issues:
1. Executing search with empty coordinates produced invalid solr query.
2. Using browsers back-button to the search criteria page would result in un-initialized @ViewScoped bean. 

Issue: #2433

### CODE REVIEW

File: dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/AdvancedSearchPage.java [hunk 1]
```diff
@@ -100,6 +101,7 @@ public AdvancedSearchPage(DataverseDao dataverseDao, DatasetFieldServiceBean dat
 
     // -------------------- LOGIC --------------------
 
+    @PostConstruct
     public void init() {
```
Comment (madryk) [inline dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/AdvancedSearchPage.java:105]: When we are entering the page in a classic way (using link from homepage). Will this code execute once or twice? There is also code that executes this method in `advanced.xhtml` file: `<f:viewAction action="#{AdvancedSearchPage.init}"/>`

Comment (diasf) [reply dataverse-webapp/src/main/java/edu/harvard/iq/dataverse/search/AdvancedSearchPage.java:105]: Good catch. It was indeed called twice. I removed the `viewAction` as now in all the cases `@PostConstruct` is called reliably for the `@ViewScoped` bean.

**Review by madryk — APPROVED** [review]
