### PR TITLE
Closes #700: Make DatasetVersionDTOTest actually run and complete successfully

### LINKED ISSUE #700: Unit test DatasetVersionDTOTest fails silently because FileNotFoundException is swallowed
Partial stack trace:
```
java.io.FileNotFoundException: src/test/java/edu/harvard/iq/dataverse/util/json/JsonDatasetVersion.txt (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.util.Scanner.<init>(Scanner.java:611)
	at edu.harvard.iq.dataverse.util.json.DatasetVersionDTOTest.testReadDataSet(DatasetVersionDTOTest.java:60)
```

Full stack trace: https://travis-ci.com/chopeen/dataverse/builds/150642204#L7462

### PR DESCRIPTION
**Pull request by chopeen**
## Build

https://travis-ci.com/chopeen/dataverse/branches

## Related Issues

- connects to #700 

## Pull Request Checklist

- [X] Unit [tests][] completed
- [X] Integration [tests][]: None
- [X] Deployment requirements, [SQL updates][], [Solr updates][], etc.: None
- [X] [Documentation][docs] completed
- [X] Merged latest from "develop" [branch][] and resolved conflicts

[tests]: http://guides.dataverse.org/en/latest/developers/testing.html
[SQL updates]: http://guides.dataverse.org/en/latest/developers/sql-upgrade-scripts.html
[Solr updates]: https://github.com/IQSS/dataverse/blob/develop/conf/solr/7.3.0/schema.xml
[docs]: http://guides.dataverse.org/en/latest/developers/documentation.html
[branch]: http://guides.dataverse.org/en/latest/developers/branching-strategy.html

### CODE REVIEW

File: dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/util/json/DatasetVersionDTOTest.java [hunk 1]
```diff
@@ -51,50 +50,40 @@ public void setUp() {
     public void tearDown() {
     }
 
-
     @Test
-    public void testReadDataSet() {
-        try {
+    public void testReadDataSet() throws IOException {
+        String filePath = "src/test/resources/json/JsonDatasetVersion.txt";
```
Comment (MrK191) [inline dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/util/json/DatasetVersionDTOTest.java]: This path should be relative, since if you package the application into distributed format (jar/war) the path will change. It should be done in similar manner to ExportServiceTest where the resources are also taken.

File: dataverse-webapp/src/test/resources/json/JsonDatasetVersion.txt [hunk 2]
```diff
@@ -0,0 +1,293 @@
+{
```
Comment (MrK191) [inline dataverse-webapp/src/test/resources/json/JsonDatasetVersion.txt]: I don't think txt file should be in json folder :P but since it is json, the filename extension should be changed to .json.

**Review by MrK191 — CHANGES_REQUESTED** [review]

File: dataverse-webapp/src/test/resources/json/JsonDatasetVersion.txt (hunk 2 above)
Comment (chopeen) [reply dataverse-webapp/src/test/resources/json/JsonDatasetVersion.txt]: It turns out there already was a copy of the file in `src/test/resources/txt/util/`. I removed the one I added unnecessarily.

File: dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/util/json/DatasetVersionDTOTest.java [hunk 3]
```diff
@@ -51,50 +50,40 @@ public void setUp() {
     public void tearDown() {
     }
 
-
     @Test
-    public void testReadDataSet() {
-        try {
+    public void testReadDataSet() throws IOException {
+        String filePath = "src/test/resources/txt/util/JsonDatasetVersion.txt";
```
Comment (MrK191) [inline dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/util/json/DatasetVersionDTOTest.java]: https://github.com/CeON/dataverse/pull/702#discussion_r385021271

**Review by MrK191 — CHANGES_REQUESTED** [review]

File: dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/util/json/DatasetVersionDTOTest.java (hunk 1 above)
Comment (chopeen) [reply dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/util/json/DatasetVersionDTOTest.java]: Done.

File: dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/util/json/DatasetVersionDTOTest.java [hunk 4]
```diff
@@ -51,50 +50,43 @@ public void setUp() {
...
-            Assert.assertEquals(expected, result);
-
-        } catch (IOException e) {
-            e.printStackTrace();
-        }
+        assertEquals(expected, result);
     }
 
-
+    private String readFileToString(String resourcePath) throws IOException {
```
Comment (chopeen) [inline dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/util/json/DatasetVersionDTOTest.java:89]: @MrK191 I copied the function here from `ExportServiceTest`, but I don't like this code duplication. Is there a class for helper functions where I could move `readFileToString` to?

Comment (MrK191) [reply dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/util/json/DatasetVersionDTOTest.java:89]: Valid point, atm we don't have any util test classes. At the other hand this is just an delegation to library code so using this line in the main test method wouldn't be "wrong" and then you can't really call it duplicate. So I'm not sure if it is worth to extract to another class. But I'm kinda 50/50 on that.

**Review by MrK191 — CHANGES_REQUESTED** [review]

File: dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/util/json/DatasetVersionDTOTest.java (hunk 4 above)
Comment (chopeen) [reply dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/util/json/DatasetVersionDTOTest.java:89]: Your call then - if it's OK for you, I'm fine with merging the code as it it.

I could add a TODO or FIXME note, but I'm not sure if its value will outweigh the clutter.

Comment (MrK191) [reply dataverse-webapp/src/test/java/edu/harvard/iq/dataverse/util/json/DatasetVersionDTOTest.java:89]: I think I'm fine with it, I wouldn't add any TODO, just check for yourself how many todo's are in the project, and then check the date's near todo using git annotate ;).

**Review by MrK191 — APPROVED** [review]
